import { site } from '../assets/config.js';
import { pageHead, photos } from './layout.mjs';

const address = `<address>Anna-Lena Korb<br>Babyschlafberatung<br>Müllersweg 15<br>97249 Eisingen<br>Deutschland<br><a href="mailto:${site.email}">${site.email}</a><br><a href="tel:${site.telephone}">${site.telephoneDisplay}</a></address>`;
function legal(label, title, body) {
  return { label, title: `${title} | Anna-Lena Korb`, description: `${title} der Babyschlafberatung Anna-Lena Korb in Eisingen bei Würzburg.`, noindex: true,
    content: `${pageHead(title, '')}<article class="wrap prose legal-section">${body}<p class="small">Stand: 13. September 2026</p></article>` };
}

export const legalPages = {
  'impressum.html': legal('Impressum', 'Impressum', `<h2>Angaben gemäß § 5 DDG</h2>${address}<h2>Kontakt</h2><p>Du erreichst mich per E-Mail und Telefon. Gesprächszeiten: Montag bis Freitag 17–19 Uhr, Samstag 9–13 Uhr. Persönliche Termine nur nach Vereinbarung.</p><h2>Tätigkeit</h2><p>Schlafberatung für Familien mit Babys und Kindern. Das Angebot ist keine medizinische oder psychotherapeutische Behandlung.</p><h2>Verbraucherstreitbeilegung</h2><p>Ich bin nicht bereit und nicht verpflichtet, an Streitbeilegungsverfahren vor einer Verbraucherschlichtungsstelle teilzunehmen.</p><h2>Inhalte und Bildrechte</h2><p>Quellen und Lizenzinformationen der verwendeten Fotos und Schriften findest du unter <a href="bildnachweise.html">Bildnachweise</a>. Die abgebildeten Personen auf Symbolfotos sind keine Kundenreferenzen.</p>`),
  'datenschutz.html': legal('Datenschutz', 'Datenschutzhinweise', `<h2>1. Verantwortliche</h2>${address}
    <h2>2. Aufruf der Website und Hosting</h2><p>Diese Website liegt bei Hostinger. Anbieter ist Hostinger, UAB, Švitrigailos g. 34, 03230 Vilnius, Litauen. Die Server stehen in Frankfurt am Main. Beim Seitenaufruf verarbeitet Hostinger technische Verbindungsdaten, insbesondere die IP-Adresse, Datum und Uhrzeit sowie die abgerufene Seite. Dies ist für die Auslieferung und Sicherheit der Website erforderlich. Grundlage ist mein berechtigtes Interesse an einer funktionsfähigen und sicheren Website nach Art. 6 Abs. 1 Buchstabe f DSGVO.</p><p>Weitere Informationen enthält die <a href="https://www.hostinger.com/legal/privacy-policy">Datenschutzerklärung von Hostinger</a>.</p>
    <h2>3. Terminanfrage über das Formular</h2><p>Wenn du das Formular auf der Kontaktseite absendest, werden Name, E-Mail-Adresse, Angebotsauswahl, Gesprächsformat, Wunschtermine und deine optionale Nachricht an den Formulardienst Web3Forms übertragen und von dort als E-Mail an mein Postfach weitergeleitet. Anbieter ist Web3Creative, Indien. Web3Forms speichert die Anfrage für höchstens 7 Tage und löscht sie danach. Für die Übermittlung in ein Land außerhalb der EU nutzt der Anbieter EU-Standardvertragsklauseln. Einzelheiten beschreibt die <a href="https://web3forms.com/privacy">Datenschutzerklärung von Web3Forms</a>. Rechtsgrundlage ist Art. 6 Abs. 1 Buchstabe b DSGVO.</p><p>Der Kalender ruft keine privaten Kalenderdaten ab und reserviert keine Termine. Beim bloßen Aufruf der Kontaktseite wird keine Verbindung zu Web3Forms aufgebaut, sondern erst beim Absenden.</p><p>Falls der Versand einmal nicht klappt, bietet die Seite an, die Anfrage als E-Mail-Entwurf zu öffnen. Mit „Im E-Mail-Programm öffnen“ übergibst du ihn an dein Mailprogramm, mit „In Gmail öffnen“ an Google. Diese E-Mail sendest du dann selbst ab.</p>
    <h2>4. E-Mail, Telefon und Anfragen</h2><p>Wenn du Kontakt aufnimmst, verarbeite ich deine Kontaktdaten, Nachricht und gegebenenfalls die ausgewählten Termine zur Beantwortung und Vorbereitung der Beratung. Rechtsgrundlage ist Art. 6 Abs. 1 Buchstabe b DSGVO für vorvertragliche und vertragliche Anliegen; bei sonstigen Anfragen mein berechtigtes Interesse an der Bearbeitung nach Art. 6 Abs. 1 Buchstabe f DSGVO.</p><p>Das angegebene Postfach nutzt Gmail. Google verarbeitet die E-Mail-Kommunikation als beteiligter Dienstanbieter. Für Nutzer im Europäischen Wirtschaftsraum benennt Google grundsätzlich Google Ireland Limited, Gordon House, Barrow Street, Dublin 4, Irland. Eine Verarbeitung außerhalb der EU ist möglich. Einzelheiten zu Zwecken, Speicherdauer, Empfängern und Übermittlungsgrundlagen beschreibt die <a href="https://policies.google.com/privacy?hl=de">Datenschutzerklärung von Google</a>.</p><p>Bitte übermittle bei der ersten Anfrage keine medizinischen Befunde oder ausführlichen Gesundheitsdaten deines Kindes. Für sensible Informationen wird vor der Beratung ein geeigneter Kommunikationsweg abgestimmt.</p><p>Anfragedaten werden gelöscht, sobald die Bearbeitung abgeschlossen ist und keine weitere Aufbewahrung erforderlich ist. Gesetzliche Aufbewahrungspflichten sowie die Durchsetzung oder Abwehr von Ansprüchen können eine längere Aufbewahrung erfordern.</p>
    <h2>5. Zoom und WhatsApp während einer Beratung</h2><p>Zoom und WhatsApp sind auf dieser Website nicht eingebettet. Beim bloßen Seitenbesuch werden deshalb keine Daten an diese Dienste übermittelt. Wenn ihr sie im Rahmen einer vereinbarten Beratung nutzen möchtet, werden Kommunikationsweg und entsprechende Datenschutzhinweise vorab abgestimmt. Die Kontaktaufnahme ist auch per Telefon oder E-Mail möglich.</p>
    <h2>6. Bilder, Schrift, Cookies und externe Links</h2><p>Fotos, Zertifikat und die Schriften Manrope und Newsreader werden vom selben Hosting wie die Website geladen. Es sind keine externen Schriften, Karten, Social-Media-Feeds, Analyse- oder Werbedienste eingebunden. Die Website setzt keine Cookies und legt keine Browser-Webspeichereinträge an.</p><p>Erst beim Anklicken eines externen Links rufst du den jeweiligen Drittanbieter auf. Es gelten dessen Datenschutzhinweise. Das betrifft insbesondere Gmail, das Kinderkörbchen und die verlinkten Fachinformationen.</p>
    <h2>7. Deine Rechte</h2><p>Unter den gesetzlichen Voraussetzungen hast du Rechte auf Auskunft, Berichtigung, Löschung, Einschränkung der Verarbeitung und Datenübertragbarkeit (Art. 15 bis 20 DSGVO). Eine erteilte Einwilligung kannst du jederzeit mit Wirkung für die Zukunft widerrufen.</p><p>Widerspruch: Soweit Daten aufgrund berechtigter Interessen verarbeitet werden, kannst du aus Gründen deiner besonderen Situation nach Art. 21 DSGVO widersprechen. Wende dich dafür an die oben genannte E-Mail-Adresse.</p>
    <h2>8. Beschwerderecht</h2><p>Du kannst dich bei einer Datenschutzaufsichtsbehörde beschweren. Für nichtöffentliche Stellen in Bayern ist das <a href="https://www.lda.bayern.de/">Bayerische Landesamt für Datenschutzaufsicht (BayLDA)</a> zuständig.</p>`),
  'agb.html': legal('AGB', 'Allgemeine Geschäftsbedingungen', `<h2>1. Anbieterin und Geltungsbereich</h2>${address}<p>Diese Bedingungen gelten für individuell vereinbarte Leistungen im Bereich Babyschlafberatung. Individuelle Vereinbarungen haben Vorrang.</p>
    <h2>2. Anfrage und Vertragsschluss</h2><p>Die Website informiert über Leistungen und Preise. Die Terminauswahl und die Paketlinks bereiten unverbindliche Anfragen vor; sie lösen keine Zahlungspflicht aus. Nach der Anfrage erhältst du ein konkretes Angebot einschließlich Leistungsumfang, Preis, Terminabsprachen und Vertragsinformationen. Ein Vertrag entsteht durch gesonderte Vereinbarung auf dieser Grundlage.</p>
    <h2>3. Umfang der Beratung</h2><p>Maßgeblich ist der im Angebot vereinbarte Umfang. Die Beratung berücksichtigt eure Angaben und euren Familienalltag. Sie beinhaltet keine medizinische Diagnostik oder Therapie. Ein bestimmtes Schlafverhalten oder ein Erfolg innerhalb einer bestimmten Zeit wird nicht geschuldet.</p><p>WhatsApp-Begleitung gilt im vereinbarten Zeitraum. Antworten erfolgen in der Regel innerhalb von 24 Stunden; sonntags und an Feiertagen am nächsten Beratungstag. Sie bedeutet keine ununterbrochene Erreichbarkeit und ist kein Notfalldienst.</p>
    <h2>4. Preise und Zahlung</h2><p>Die ausgewiesenen Preise sind Gesamtpreise. Die Zahlung ist vor Leistungsbeginn fällig, sofern im Angebot nichts anderes vereinbart wird. Zahlungsweg und gegebenenfalls eine Ratenzahlung werden im Angebot geregelt. Zusätzliche Leistungen oder Kosten werden nur nach vorheriger Vereinbarung berechnet.</p>
    <h2>5. Termine und Beendigung</h2><p>Bitte teile notwendige Terminänderungen frühzeitig mit. Bis 24 Stunden vor einem Termin ist eine Verschiebung kostenfrei möglich. Im Übrigen gelten die individuellen Vereinbarungen und gesetzlichen Regelungen. Gesetzliche Widerrufs- und Kündigungsrechte bleiben unberührt. Es gibt keine automatische Verlängerung der Begleitung.</p>
    <h2>6. Mitwirkung und Vertraulichkeit</h2><p>Für die Beratung sind zutreffende Informationen über eure Situation erforderlich. Die praktische Umsetzung bleibt in eurer Verantwortung. Persönliche Angaben werden vertraulich und nach Maßgabe der Datenschutzhinweise verarbeitet.</p>
    <h2>7. Haftung</h2><p>Es gelten die gesetzlichen Haftungsregelungen.</p>
    <h2>8. Widerruf und Verbraucherrechte</h2><p>Bei Fernabsatzverträgen steht Verbrauchern grundsätzlich ein gesetzliches Widerrufsrecht zu. Die <a href="widerruf.html">Widerrufsbelehrung und das Muster-Widerrufsformular</a> sind gesondert aufgeführt und werden im Rahmen des Vertragsschlusses zur Verfügung gestellt.</p>
    <h2>9. Beratungsunterlagen</h2><p>Schlafpläne und Unterlagen sind für den persönlichen Gebrauch innerhalb der beratenen Familie bestimmt. Gesetzlich erlaubte Nutzungen bleiben unberührt.</p>
    <h2>10. Anwendbares Recht</h2><p>Es gilt deutsches Recht. Zwingender Verbraucherschutz des Staates deines gewöhnlichen Aufenthalts bleibt erhalten. Für den Gerichtsstand gelten die gesetzlichen Vorschriften.</p>`),
  'widerruf.html': legal('Widerruf', 'Widerrufsrecht', `<h2>Widerrufsbelehrung für Dienstleistungen</h2><p>Sie haben das Recht, binnen vierzehn Tagen ohne Angabe von Gründen diesen Vertrag zu widerrufen. Die Widerrufsfrist beträgt vierzehn Tage ab dem Tag des Vertragsabschlusses.</p><p>Um Ihr Widerrufsrecht auszuüben, müssen Sie uns (Anna-Lena Korb, Müllersweg 15, 97249 Eisingen, Telefon: ${site.telephoneDisplay}, E-Mail: ${site.email}) mittels einer eindeutigen Erklärung (z. B. einem mit der Post versandten Brief oder einer E-Mail) über Ihren Entschluss, diesen Vertrag zu widerrufen, informieren. Sie können dafür das unten stehende Muster-Widerrufsformular verwenden, das jedoch nicht vorgeschrieben ist.</p><p>Zur Wahrung der Widerrufsfrist reicht es aus, dass Sie die Mitteilung über die Ausübung des Widerrufsrechts vor Ablauf der Widerrufsfrist absenden.</p>
    <h2>Folgen des Widerrufs</h2><p>Wenn Sie diesen Vertrag widerrufen, haben wir Ihnen alle Zahlungen, die wir von Ihnen erhalten haben, einschließlich der Lieferkosten (mit Ausnahme der zusätzlichen Kosten, die sich daraus ergeben, dass Sie eine andere Art der Lieferung als die von uns angebotene, günstigste Standardlieferung gewählt haben), unverzüglich und spätestens binnen vierzehn Tagen ab dem Tag zurückzuzahlen, an dem die Mitteilung über Ihren Widerruf dieses Vertrags bei uns eingegangen ist. Für diese Rückzahlung verwenden wir dasselbe Zahlungsmittel, das Sie bei der ursprünglichen Transaktion eingesetzt haben, es sei denn, mit Ihnen wurde ausdrücklich etwas anderes vereinbart; in keinem Fall werden Ihnen wegen dieser Rückzahlung Entgelte berechnet.</p><p>Haben Sie verlangt, dass die Dienstleistungen während der Widerrufsfrist beginnen sollen, so haben Sie uns einen angemessenen Betrag zu zahlen, der dem Anteil der bis zu dem Zeitpunkt, zu dem Sie uns von der Ausübung des Widerrufsrechts hinsichtlich dieses Vertrags unterrichten, bereits erbrachten Dienstleistungen im Vergleich zum Gesamtumfang der im Vertrag vorgesehenen Dienstleistungen entspricht.</p>
    <h2>Vorzeitiges Erlöschen</h2><p>Bei einer entgeltlichen Dienstleistung erlischt das Widerrufsrecht bei vollständiger Leistungserbringung nur unter den gesetzlichen Voraussetzungen. Dazu gehören insbesondere Ihre ausdrückliche Zustimmung zum Beginn vor Ablauf der Widerrufsfrist und Ihre Bestätigung der Kenntnis, dass das Widerrufsrecht bei vollständiger Vertragserfüllung erlischt.</p>
    <h2>Muster-Widerrufsformular</h2><p>Wenn Sie den Vertrag widerrufen wollen, füllen Sie bitte dieses Formular aus und senden Sie es zurück.</p><div class="note"><p>An Anna-Lena Korb, Müllersweg 15, 97249 Eisingen, ${site.email}</p><p>Hiermit widerrufe(n) ich/wir (*) den von mir/uns (*) abgeschlossenen Vertrag über den Kauf der folgenden Waren (*) / die Erbringung der folgenden Dienstleistung (*):</p><p>Bestellt am (*) / erhalten am (*):<br>Name des/der Verbraucher(s):<br>Anschrift des/der Verbraucher(s):<br>Unterschrift des/der Verbraucher(s) (nur bei Mitteilung auf Papier):<br>Datum:</p><p>(*) Unzutreffendes streichen.</p></div><p>Auf dieser Website werden ausschließlich unverbindliche Anfragen vorbereitet. Kostenpflichtige Verträge werden gesondert vereinbart.</p>`),
  'barrierefreiheit.html': legal('Barrierefreiheit', 'Hinweise zur Zugänglichkeit', `<h2>Eine Website, die zugänglich sein soll</h2><p>Die Website bietet eine logische Überschriftenstruktur, beschriftete Formularfelder, alternative Bildbeschreibungen und sichtbare Tastaturfokussierungen.</p><h2>Bedienung</h2><p>Über „Zum Inhalt springen“ gelangst du per Tastatur direkt zum Hauptinhalt. Links, Menü, Terminauswahl und aufklappbare Fragen lassen sich mit der Tastatur bedienen. Alle Tage und Uhrzeiten sind einzeln beschriftete Schaltflächen. Alternativ kann das Datum direkt eingegeben werden. Die Darstellung passt sich an kleinere Bildschirme an und berücksichtigt reduzierte Bewegung.</p><p>Ohne JavaScript sind die Informationen und Kontaktlinks weiterhin verfügbar. Die interaktive Terminauswahl benötigt JavaScript; eine Anfrage ist alternativ per E-Mail oder Telefon möglich.</p><h2>Stand der Bewertung</h2><p>Diese freiwillige Beschreibung ist kein Zertifikat und keine Erklärung einer vollständig geprüften WCAG- oder BFSG-Konformität. Die tatsächliche Nutzung mit unterschiedlichen Hilfsmitteln kann zu abweichenden Ergebnissen führen. Das eingescannte Zertifikat ist nicht als barrierefreies PDF aufbereitet; die wesentlichen Angaben stehen als HTML-Text auf der Über-mich-Seite.</p><h2>Eine Barriere melden</h2><p>Wenn du eine Information nicht erreichen oder die Terminauswahl nicht nutzen kannst, schreibe an <a href="mailto:${site.email}">${site.email}</a> oder rufe unter <a href="tel:${site.telephone}">${site.telephoneDisplay}</a> an. Nenne möglichst die betroffene Seite und das Problem. Ich helfe dir gerne persönlich weiter.</p>`),
  'bildnachweise.html': legal('Bildnachweise', 'Bildnachweise & Lizenzen', `<p>Die Fotografien illustrieren familiäre Nähe. Abgebildete Personen sind keine Darstellung von Anna-Lena Korb und keine Kundenreferenzen.</p><h2>Fotografien von Unsplash</h2><ul>${Object.values(photos).map(p => `<li>${p.subject}: Foto von ${p.author}, Unsplash.</li>`).join('')}</ul><p>Alle Aufnahmen wurden unter der kostenlosen Unsplash-Lizenz bezogen und werden lokal eingebunden, ohne Verbindung zu Unsplash beim Seitenaufruf. Die Lizenz erlaubt die kostenlose kommerzielle Nutzung ohne Namensnennung; die Urheber werden hier trotzdem genannt. Sie hebt Rechte abgebildeter Personen und Marken nicht pauschal auf.</p><h2>Schriften</h2><p>Manrope und Newsreader, lokal eingebunden unter der SIL Open Font License 1.1 (<a href="assets/MANROPE-LICENSE.txt">Lizenz Manrope</a>, <a href="assets/NEWSREADER-LICENSE.txt">Lizenz Newsreader</a>). Beim Seitenaufruf wird keine Verbindung zu Google Fonts aufgebaut.</p><h2>Logo</h2><p>Das bestehende Geborgenheitsmotiv wurde für den ursprünglichen Website-Entwurf mit KI-Unterstützung erstellt. Die Wortmarke wird mit Manrope dargestellt.</p><h2>Zertifikat</h2><p>Das Abschlusszertifikat wurde von Anna-Lena Korb für diese Website bereitgestellt. Die Bilddatei zeigt das Originaldokument unverändert. Es wurden keine Aussagen oder Siegel hinzugefügt.</p><h2>Bestehende Projektbibliothek</h2><p>Im Repository ist weiterhin PHPMailer enthalten, Lizenz LGPL 2.1, Quelle: <a href="https://github.com/PHPMailer/PHPMailer">PHPMailer</a>. Die aktuelle statische Website verwendet diese Bibliothek nicht und versendet keine Formulare über PHP.</p>`),
};
