import { site, offers } from '../assets/config.js';
import { contact, link, arrow, closing, pageHead, portrait, photo, questions, childcare, updated } from './layout.mjs';

const faq = [
  ['Für welches Alter ist die Beratung gedacht?', 'Ich begleite Familien mit Kindern von 0 bis 6 Jahren; ältere Kinder nach Absprache. Bei Neugeborenen geht es um Orientierung, sichere Schlafbedingungen und die Entlastung der Eltern – nicht darum, selbstständiges Einschlafen oder Durchschlafen zu verlangen. Ziele und Vorgehen richten sich nach Alter und Entwicklung.'],
  ['Muss mein Kind alleine weinen?', 'Nein. Kontrolliertes Schreienlassen gehört nicht zu meiner Beratung. Wir entwickeln einen klaren Plan und begleiten Veränderungen. Wenn euer Kind Trost braucht, bleibt ihr ansprechbar. Nähe ist kein Fehler.'],
  ['Müssen wir abstillen oder alles sofort verändern?', 'Nein. Stillen, Schnuller oder Einschlafbegleitung sind nicht automatisch ein Problem. Wir schauen ehrlich darauf, was euch belastet und was ihr verändern möchtet. Es gibt keine pauschale Pflicht zum Abstillen oder zum Wechsel des Schlafplatzes. Bei Säuglingen haben Ernährung und sichere Schlafbedingungen Vorrang.'],
  ['Versprichst du, dass unser Kind danach durchschläft?', 'Nein. Ich verspreche euch eine persönliche Begleitung und nachvollziehbare Schritte, aber keinen bestimmten Erfolg in einer festen Zahl von Nächten. Schlaf entwickelt sich individuell. Wir vereinbaren realistische Ziele und prüfen gemeinsam, was euch hilft.'],
  ['Wie funktioniert das Kennenlernen?', 'Ihr fragt einen Termin mindestens sieben Tage im Voraus an. Das Gespräch dauert 20 Minuten und ist kostenlos. Danach entscheidet ihr in Ruhe, ob ihr weitermachen möchtet und welches Angebot zu euch passt. Eine Anfrage löst keine Zahlungspflicht aus.'],
  ['Funktioniert die Beratung auch, wenn wir nicht in der Nähe wohnen?', 'Ja. Die Gespräche finden per Zoom oder Telefon statt, deshalb ist es egal, wo in Deutschland ihr wohnt. In Würzburg und im Umkreis von etwa 10 bis 15 Kilometern sind zusätzlich persönliche Termine nach Absprache möglich, ohne zusätzliche Anfahrtskosten.'],
  ['Wann bekomme ich eine Antwort?', 'Beratungszeiten sind Montag bis Freitag von 17 bis 19 Uhr und Samstag von 9 bis 13 Uhr. Auf Anfragen und begleitende WhatsApp-Nachrichten antworte ich in der Regel innerhalb von 24 Stunden; sonntags und an Feiertagen erfolgt die Antwort am nächsten Beratungstag. Chatbegleitung ist keine ständige Erreichbarkeit.'],
  ['Was ist bei gesundheitlichen Beschwerden?', 'Meine Schlafberatung ersetzt keine ärztliche Untersuchung, Diagnose oder Behandlung. Bei möglichen gesundheitlichen Ursachen ist eure Kinderarztpraxis die richtige Anlaufstelle. Die Beratung ist kein Notfalldienst.'],
];

const onlineFaq = [
  ['Brauchen wir für Zoom ein eigenes Konto?', 'Nein. Ihr bekommt einen Link und könnt über Smartphone, Tablet oder Laptop teilnehmen. Wenn euch ein Videogespräch nicht liegt, sprechen wir bei den Begleitungspaketen auch gern per Telefon.'],
  ['Ist eine Beratung per Video genauso persönlich?', 'Für Schlafberatung ja. Wir sprechen ausführlich über euren Alltag, euren Abend und eure Nächte. Ihr sitzt dabei in eurer gewohnten Umgebung und müsst mit Baby nirgendwohin fahren. Wenn ihr möchtet, könnt ihr mir den Schlafplatz auch kurz per Kamera zeigen.'],
  ['Können beide Elternteile teilnehmen?', 'Sehr gern, auch von zwei verschiedenen Orten aus. Gerade wenn ihr euch das Einschlafen künftig besser aufteilen möchtet, ist es hilfreich, wenn beide dabei sind.'],
  ['Wie bekommen wir den Schlafplan?', 'Bei Basis, Intensiv und Premium erhaltet ihr euren schriftlichen Plan innerhalb von 24 Stunden nach dem Beratungsgespräch, sofern die vereinbarten Unterlagen vollständig vorliegen. Rückfragen klären wir in der vereinbarten Begleitzeit per WhatsApp.'],
  faq[1], faq[3],
];

const packages = [
  { id: 'basis', name: 'Basis', price: 149, kicker: 'Ein klarer Anfang', duration: 'Beratung + 7 Tage Begleitung', text: 'Ihr möchtet eure Situation verstehen und mit einem konkreten Plan loslegen.', items: ['Ausführlicher Fragebogen und Auswertung', '60 Minuten per Zoom oder Telefon', 'Individueller schriftlicher Schlafplan innerhalb von 24 Stunden nach dem Gespräch', '7 Tage WhatsApp-Begleitung für Rückfragen'] },
  { id: 'intensiv', name: 'Intensiv', price: 299, kicker: 'Veränderung mit Begleitung', duration: '3 Wochen an eurer Seite', text: 'Ihr möchtet neue Routinen ausprobieren und dabei regelmäßig Rückmeldung bekommen.', items: ['Fragebogen, Schlafprotokoll und Auswertung', '60 Minuten Erstberatung per Zoom oder Telefon', 'Individueller Plan innerhalb von 24 Stunden', '3 Folgegespräche à 30 Minuten', '3 Wochen WhatsApp-Begleitung', 'Anpassungen des Plans während der Begleitung'] },
  { id: 'premium', name: 'Premium', price: 479, kicker: 'Mehr Zeit für euren Weg', duration: '6 Wochen persönliche Begleitung', text: 'Ihr wünscht euch über einen längeren Zeitraum Orientierung und kontinuierlichen Austausch.', items: ['Fragebogen, Schlafprotokoll und Auswertung', '60 Minuten Erstberatung per Zoom oder Telefon', 'Individueller Plan innerhalb von 24 Stunden', '5 Folgegespräche à 30 Minuten', '6 Wochen WhatsApp-Begleitung', 'Regelmäßige Auswertung und Plananpassungen'] },
];

const check = `<svg class="icon-check" aria-hidden="true" viewBox="0 0 20 20" width="18" height="18"><path d="M4.5 10.5l3.5 3.5 7.5-8" fill="none" stroke="currentColor" stroke-width="1.7" stroke-linecap="round" stroke-linejoin="round"/></svg>`;
const cross = `<svg class="icon-cross" aria-hidden="true" viewBox="0 0 20 20" width="18" height="18"><path d="M6 6l8 8M14 6l-8 8" fill="none" stroke="currentColor" stroke-width="1.7" stroke-linecap="round"/></svg>`;

const priceCards = () => `<div class="price-cards">${packages.map(p => `<article class="price-card${p.id === 'intensiv' ? ' featured' : ''}" id="${p.id}" data-reveal><p class="kicker">${p.kicker}</p><h2>${p.name}</h2><p class="price-value">${p.price}<span> €</span></p><p class="price-duration">${p.duration}</p><p class="package-description">${p.text}</p><ul class="check-list">${p.items.map(item => `<li>${check}<span>${item}</span></li>`).join('')}</ul>${contact(`${p.name} anfragen`, `button${p.id === 'intensiv' ? '' : ' secondary'}`, `?paket=${p.name}#anfrage`)}<p class="tiny">Gesamtpreis · kein Abo</p></article>`).join('')}</div>`;

const steps = [
  ['Erst einmal erzählen.', '20 Minuten kostenlos kennenlernen. Was ist gerade schwierig? Was wünscht ihr euch? Danach entscheidet ihr, ob ihr eine Beratung möchtet.'],
  ['Eure Situation verstehen.', 'Fragebogen, Schlafprotokoll und ein persönliches Gespräch helfen uns, genauer hinzusehen. Auch eure Familiengeschichte darf dabei Raum bekommen.'],
  ['Einen klaren Plan bekommen.', 'Bei Basis, Intensiv und Premium bekommt ihr innerhalb von 24 Stunden nach dem Gespräch euren schriftlichen Plan mit konkreten nächsten Schritten.'],
  ['Ausprobieren. Nachfragen. Anpassen.', 'Je nach Angebot bleibe ich sieben Tage, drei oder sechs Wochen an eurer Seite. Ein Plan soll im echten Leben funktionieren – nicht nur auf Papier.'],
];
const process = () => `<ol class="steps">${steps.map(([h, p], i) => `<li data-reveal style="--i:${i}"><span class="step-dot" aria-hidden="true">${i + 1}</span><h3>${h}</h3><p>${p}</p></li>`).join('')}</ol>`;

const facts = `<section class="facts" aria-label="Erfahrung und Qualifikation"><div class="wrap facts-grid"><div data-reveal><strong>seit 2010</strong><span>in der Kindertagespflege tätig</span></div><div data-reveal style="--i:1"><strong>≈ 100</strong><span>Kinder im Alltag begleitet</span></div><div data-reveal style="--i:2"><strong>0–6 Jahre</strong><span>Babys, Kleinkinder, Kindergartenkinder</span></div><div data-reveal style="--i:3"><strong>zertifiziert</strong><span>Ausbildung zur Babyschlafberaterin 2026</span></div></div></section>`;

const promise = `<section class="section wrap promise"><div class="section-heading" data-reveal><p class="kicker">Meine Haltung</p><h2>Klar in der Sache. <em>Warm im Umgang.</em></h2><p>Ihr sollt vorher wissen, worauf ihr euch einlasst. Deshalb steht hier, was ihr von mir bekommt – und was es bei mir nicht gibt.</p></div><div class="promise-grid"><div class="promise-card" data-reveal><h3>Darauf könnt ihr euch verlassen</h3><ul><li>${check}<span>Ein Plan, der zu Alter, Entwicklung und eurem Alltag passt</span></li><li>${check}<span>Begleitung bei der Umsetzung, nicht nur ein PDF</span></li><li>${check}<span>Ehrliche, verständliche Worte statt Fachchinesisch</span></li><li>${check}<span>Höchstens drei Familien gleichzeitig, damit Zeit für euch bleibt</span></li></ul></div><div class="promise-card muted" data-reveal style="--i:1"><h3>Was es bei mir nicht gibt</h3><ul><li>${cross}<span>Kein kontrolliertes Schreienlassen</span></li><li>${cross}<span>Keine Durchschlafgarantie in X Nächten</span></li><li>${cross}<span>Kein pauschales Abstillen oder Umziehen ins Kinderzimmer</span></li><li>${cross}<span>Keine Schuldzuweisungen – Nähe ist kein Fehler</span></li></ul></div></div></section>`;

const guides = [
  ['baby-einschlafen.html', 'Einschlafen', 'Baby einschlafen: sanft begleiten statt jeden Abend kämpfen', 'Müdigkeitszeichen, ein tragfähiges Abendritual und kleine Schritte, wenn Einschlafen nur noch mit einer Person klappt.'],
  ['baby-durchschlafen.html', 'Durchschlafen', 'Baby schläft nicht durch: Was normal ist und was helfen kann', 'Warum nächtliches Aufwachen dazugehört, welche Gründe es haben kann und wann ihr ärztlich abklären solltet.'],
  ['schlafwissen.html', 'Sicherheit', 'Sicherer Babyschlaf und verlässliche Quellen', 'Rückenlage, Schlafsack, eigenes Bett im Elternschlafzimmer: die wichtigsten Empfehlungen und wo ihr sie nachlest.'],
];
const guideCards = (exclude = '') => `<div class="guide-grid">${guides.filter(([href]) => href !== exclude).map(([href, tag, h, p], i) => `<a class="guide-card" href="${href}" data-reveal style="--i:${i}"><span class="tag">${tag}</span><h3>${h}</h3><p>${p}</p><span class="guide-more">Weiterlesen${arrow}</span></a>`).join('')}</div>`;

const certificate = (cls = '') => `<figure class="certificate ${cls}" data-reveal><a href="assets/zertifikat-anna-lena-korb.pdf" aria-label="Abschlusszertifikat als PDF öffnen"><img src="assets/zertifikat-anna-lena-korb.png" alt="Abschlusszertifikat: Anna-Lena Korb hat die Ausbildung zur Babyschlafberaterin am 11.03.2026 erfolgreich absolviert. Ausbildungsleitung Melanie Heift-Budde." width="1200" height="849" loading="lazy"></a><figcaption>Abschlusszertifikat vom 11. März 2026. Laut Zertifikat ist die Ausbildung vom Gesundheitsamt der Stadt Aachen zertifiziert. <a href="assets/zertifikat-anna-lena-korb.pdf">Als PDF ansehen</a></figcaption></figure>`;

function article({ minutes, toc, body, related, image }) {
  return `<div class="wrap article-layout"><aside class="article-aside"><div class="byline"><img src="assets/logo.png" alt="" width="44" height="44" loading="lazy"><div><strong>Anna-Lena Korb</strong><span>Zertifizierte Babyschlafberaterin</span></div></div><p class="meta">Aktualisiert am <time datetime="${updated}">9. Oktober 2026</time> · ${minutes} Min. Lesezeit</p><nav class="toc" aria-label="Inhalt dieses Artikels"><p>Inhalt</p><ol>${toc.map(([id, t]) => `<li><a href="#${id}">${t}</a></li>`).join('')}</ol></nav></aside><article class="prose article-body">${image ? `<figure class="article-figure">${photo(image, { sizes: '(max-width: 760px) 100vw, 680px', cls: 'rounded' })}</figure>` : ''}${body}<aside class="callout"><p><strong>Wichtig:</strong> Dieser Ratgeber ersetzt keine individuelle Beratung und keine ärztliche Untersuchung. Bei gesundheitlichen Fragen ist eure Kinderarztpraxis die richtige Anlaufstelle.</p></aside></article></div><section class="section wrap"><div class="section-heading compact" data-reveal><p class="kicker">Weiterlesen</p><h2>Mehr aus dem <em>Ratgeber</em></h2></div>${guideCards(related)}</section>`;
}

const einschlafenFaq = [
  ['Ist es schlimm, wenn mein Baby nur an der Brust oder mit Fläschchen einschläft?', 'Nein. Gerade in den ersten Lebensmonaten ist das sehr verbreitet und kein Fehler. Es wird erst dann ein Thema, wenn es euch belastet oder ihr euch mehr Flexibilität wünscht. Dann lassen sich die Abläufe schrittweise verändern, ohne abzustillen.'],
  ['Wie lange darf das Einschlafen dauern?', 'Eine feste Norm gibt es nicht. Wenn das Einschlafen über Wochen regelmäßig sehr lange dauert und euch den Abend kostet, lohnt ein Blick auf Schlafenszeit, Tagschlaf und den Ablauf davor. Oft liegt der Schlüssel im Timing.'],
  ['Ab wann kann ein Kind selbstständig einschlafen?', 'Dafür gibt es kein festes Alter. Manche Kinder schlafen früh allein ein, andere brauchen lange Begleitung. Selbstständigeres Einschlafen kann ein Ziel sein, ist aber keine Pflicht und bei Neugeborenen kein sinnvolles Ziel.'],
];
const durchschlafenFaq = [
  ['Ab wann schlafen Babys durch?', 'Das ist sehr unterschiedlich. Viele Kinder wachen im ersten Lebensjahr und auch danach nachts noch auf. Das ist entwicklungsbedingt normal. Wichtiger als ein Stichtag ist, ob die Nächte für eure Familie tragbar sind.'],
  ['Muss ich abstillen, damit mein Kind durchschläft?', 'Nein. Stillen ist nicht automatisch der Grund für häufiges Aufwachen, und Abstillen ist keine Voraussetzung für eine Schlafberatung. Wenn nächtliches Stillen euch belastet, finden wir gemeinsam Wege, die zu euch passen.'],
  ['Kann eine Schlafberatung Durchschlafen garantieren?', 'Nein, und niemand sollte das versprechen. Schlaf entwickelt sich individuell. Was eine gute Beratung leisten kann: eure Situation verstehen, realistische Ziele setzen und euch bei der Umsetzung begleiten.'],
];

export const pages = {
  'index.html': {
    title: 'Babyschlafberatung online & deutschlandweit | Anna-Lena Korb', label: 'Startseite',
    description: 'Zertifizierte Babyschlafberatung ohne Schreienlassen: persönliche Begleitung per Zoom und Telefon in ganz Deutschland. Kostenloses 20-Minuten-Kennenlernen.',
    faq: [faq[1], faq[2], faq[3], faq[5], faq[4]],
    content: `<section class="hero wrap"><div class="hero-copy"><h1><span class="hero-kicker">Babyschlafberatung · online in ganz Deutschland</span>Ruhigere Nächte. <em>Mit Nähe</em> und einem klaren Plan.</h1><p class="lead">Wenn das Einschlafen den ganzen Abend bestimmt, braucht ihr nicht noch mehr gut gemeinte Tipps. Sondern jemanden, der zuhört, ehrlich hinschaut und euch Schritt für Schritt begleitet.</p><div class="hero-actions">${contact()}${link('preise.html', 'Angebote & Preise')}</div><ul class="assurance"><li>${check}Ohne Schreienlassen</li><li>${check}Per Zoom oder Telefon</li><li>${check}20 Minuten kostenlos</li></ul></div><figure class="hero-media"><div class="hero-frame">${photo('hero', { priority: true, sizes: '(max-width: 760px) 100vw, 44vw' })}</div><figcaption class="hero-badge"><img src="assets/logo.png" alt="" width="40" height="40"><span><strong>Anna-Lena Korb</strong>Zertifizierte Babyschlafberaterin</span></figcaption></figure></section>
    ${facts}
    <section class="section wrap recognise"><div class="recognise-media" data-reveal>${photo('nacht', { sizes: '(max-width: 760px) 100vw, 40vw', cls: 'rounded' })}</div><div class="recognise-copy"><div data-reveal><p class="kicker">Kommt euch das bekannt vor?</p><h2>Wenn Schlaf <em>alles andere</em> bestimmt.</h2><p class="lead">Ihr seid müde. Und vielleicht auch müde von widersprüchlichen Ratschlägen. Wir schauen auf eure Situation – ohne Schuldzuweisungen und ohne ein Programm für alle.</p></div><ul class="voices"><li data-reveal><q>Der Abend zieht sich über Stunden.</q><span>Sobald ich aufstehe, beginnt alles von vorn.</span></li><li data-reveal><q>Die Nächte sind zerstückelt.</q><span>Unser Kind wacht häufig auf, und ich finde selbst kaum noch in den Schlaf.</span></li><li data-reveal><q>Einschlafen klappt nur mit mir.</q><span>Wir wünschen uns, dass auch der andere Elternteil übernehmen kann.</span></li><li data-reveal><q>Kita-Start, Tagschlaf, neuer Alltag.</q><span>Was passt jetzt zu unserem Kind?</span></li></ul><p class="small">Für Familien mit Kindern von 0 bis 6 Jahren. Bei Neugeborenen stehen Orientierung und sichere Schlafbedingungen im Mittelpunkt.</p></div></section>
    ${promise}
    <section class="soft-section"><div class="wrap personal-layout">${portrait()}<div class="personal-copy" data-reveal><p class="kicker">Die Person an eurer Seite</p><h2>Ich bin Anna-Lena. <em>Herzlich, ehrlich</em> und ganz nah am Alltag.</h2><p>Seit 2010 begleite ich als qualifizierte Kindertagespflegeperson Babys und Kleinkinder. Rund 100 Kinder habe ich in dieser Zeit beim Ankommen, Wachsen und Zur-Ruhe-Kommen erlebt.</p><p>Als Mutter eines 2005 geborenen Kindes kenne ich lange Einschlafabende auch selbst. Heute verbinde ich diese Erfahrung mit meiner Ausbildung zur Babyschlafberaterin.</p><p>Ihr bekommt von mir klare Worte, einen konkreten Plan und Unterstützung bei der Umsetzung. Mit Verständnis für eure Erschöpfung – und Respekt vor eurem Kind.</p><div class="inline-actions">${link('ueber-mich.html', 'Meine Geschichte')}${link('ueber-mich.html#qualifikationen', 'Qualifikationen & Zertifikat')}</div></div></div></section>
    <section class="section wrap"><div class="section-heading" data-reveal><p class="kicker">So arbeiten wir zusammen</p><h2>Von „Was sollen wir tun?“ <em>zu eurem nächsten Schritt.</em></h2><p>Ein persönlicher Weg statt einer Sammlung weiterer Schlaftipps. ${link('schlafberatung.html', 'Mehr über die Beratung')}</p></div>${process()}</section>
    <section class="online-band"><div class="wrap online-layout"><div data-reveal><p class="kicker">Online-Beratung</p><h2>Wo immer ihr wohnt. <em>Beratung bei euch zu Hause.</em></h2><p>Ob Hamburg, Berlin, Köln, München oder ein Dorf auf dem Land: Die Gespräche laufen per Zoom oder Telefon. Ihr bleibt in eurer gewohnten Umgebung, beide Elternteile können dabei sein – auch von zwei Orten aus. Im Raum Würzburg treffen wir uns auf Wunsch auch persönlich.</p>${link('online-schlafberatung.html', 'So funktioniert die Online-Beratung')}</div><ul class="online-points"><li data-reveal><strong>Keine Anfahrt</strong><span>Kein Packen, kein Termin außer Haus mit müdem Baby.</span></li><li data-reveal style="--i:1"><strong>Feste Gesprächszeiten</strong><span>Mo–Fr 17–19 Uhr und Sa 9–13 Uhr.</span></li><li data-reveal style="--i:2"><strong>Begleitung zwischen den Terminen</strong><span>Rückfragen per WhatsApp im gebuchten Zeitraum.</span></li></ul></div></section>
    <section class="section wrap"><div class="section-heading" data-reveal><p class="kicker">Angebote</p><h2>Ein überschaubarer Start. <em>Klare Gesamtpreise.</em></h2><p>Das Kennenlernen ist kostenlos. Danach entscheidet ihr euch für eine einzelne Sprechstunde oder eine persönliche Begleitung. Ohne Abo, ohne automatische Verlängerung.</p></div><div class="price-preview">${offers.slice(1).map((o, i) => `<a href="preise.html#${o.id.toLowerCase()}" class="preview-row" data-reveal style="--i:${i}"><span class="preview-name"><strong>${o.name}</strong><span>${['45 Minuten für ein konkretes Thema', '60 Minuten Beratung + 7 Tage Begleitung', '3 Wochen mit regelmäßigen Folgegesprächen', '6 Wochen mit persönlicher Begleitung'][i]}</span></span><span class="preview-value">${o.price} €</span>${arrow}</a>`).join('')}</div>${link('preise.html', 'Alle Leistungen im Detail')}</section>
    <section class="soft-section"><div class="wrap"><div class="section-heading" data-reveal><p class="kicker">Ratgeber</p><h2>Erste Orientierung <em>für müde Eltern.</em></h2><p>Eigenständig geschrieben, mit Verweisen auf verlässliche Quellen. Kein Ersatz für eine Beratung, aber ein guter Anfang.</p></div>${guideCards()}</div></section>
    <section class="section wrap faq-layout"><div data-reveal><p class="kicker">Bevor wir sprechen</p><h2>Eure Fragen <em>haben Platz.</em></h2><p>Unsicherheit gehört dazu. Hier findet ihr erste Antworten. ${link('schlafberatung.html#fragen', 'Alle Fragen')}</p></div>${questions([faq[1], faq[2], faq[3], faq[5], faq[4]])}</section>${closing()}`,
  },
  'online-schlafberatung.html': {
    title: 'Babyschlafberatung online – deutschlandweit per Zoom | Anna-Lena Korb', label: 'Online-Beratung',
    description: 'Online-Schlafberatung für Babys und Kleinkinder: persönlich per Zoom oder Telefon, egal wo in Deutschland ihr wohnt. Ohne Schreienlassen. Jetzt kostenlos kennenlernen.',
    faq: onlineFaq,
    service: { name: 'Babyschlafberatung online', offers: offers.slice(1) },
    content: `${pageHead('Online-Beratung · deutschlandweit', 'Babyschlafberatung online: <em>persönlich begleitet</em>, wo immer ihr wohnt.', 'Ihr müsst nicht in meiner Nähe wohnen, um von mir begleitet zu werden. Kennenlernen, Beratung und Folgegespräche laufen per Zoom oder Telefon, Rückfragen in der Begleitzeit per WhatsApp.', `<figure class="page-head-media" data-reveal>${photo('online', { priority: true, sizes: '(max-width: 760px) 100vw, 40vw', cls: 'rounded' })}</figure>`)}
    <section class="section-bottom wrap"><div class="section-heading" data-reveal><p class="kicker">Ablauf</p><h2>So läuft die <em>Online-Beratung</em></h2><p>Von der ersten Nachricht bis zur Begleitung: Ihr wisst jederzeit, was als Nächstes kommt.</p></div>${process()}</section>
    <section class="soft-section"><div class="wrap feature-grid"><div class="section-heading compact" data-reveal><p class="kicker">Warum online gut funktioniert</p><h2>Schlafberatung findet <em>im Alltag</em> statt.</h2></div><div class="features"><article data-reveal><h3>Bei euch zu Hause</h3><p>Ihr sprecht in eurer gewohnten Umgebung. Wenn ihr möchtet, zeigt ihr mir Schlafplatz und Abendablauf kurz per Kamera.</p></article><article data-reveal style="--i:1"><h3>Beide Eltern dabei</h3><p>Auch von zwei Orten aus. Das hilft, wenn ihr das Einschlafen künftig besser aufteilen möchtet.</p></article><article data-reveal style="--i:2"><h3>Keine Anfahrt</h3><p>Kein Termin außer Haus mit müdem Baby, keine Fahrtzeit. Ihr braucht nur Smartphone, Tablet oder Laptop.</p></article><article data-reveal style="--i:3"><h3>Begleitung im Alltag</h3><p>In den Paketen könnt ihr Fragen per WhatsApp stellen. Antwort in der Regel innerhalb von 24 Stunden.</p></article></div></div></section>
    <section class="section wrap region"><div data-reveal><p class="kicker">Deutschlandweit und regional</p><h2>Online für ganz Deutschland. <em>Vor Ort im Raum Würzburg.</em></h2></div><div data-reveal style="--i:1"><p>Familien aus allen Bundesländern können die Beratung vollständig online nutzen – ob in Hamburg, Berlin, Köln, Frankfurt, Stuttgart, München oder auf dem Land.</p><p>Ich lebe in Eisingen bei Würzburg. Innerhalb von Würzburg und im Umkreis von etwa 10 bis 15 Kilometern sind persönliche Termine nach Absprache möglich, ohne zusätzliche Anfahrtskosten. Eine offene Sprechstunde vor Ort gibt es nicht.</p><p class="small">Gesprächszeiten: Montag bis Freitag 17–19 Uhr, Samstag 9–13 Uhr.</p></div></section>
    <section class="section-bottom wrap faq-layout" id="fragen"><div data-reveal><p class="kicker">Häufige Fragen</p><h2>Gut zu wissen <em>vor dem ersten Gespräch.</em></h2></div>${questions(onlineFaq)}</section>${closing('Euer erstes Gespräch: <em>20 Minuten, kostenlos.</em>')}`,
  },
  'ueber-mich.html': {
    title: 'Über Anna-Lena Korb – Babyschlafberaterin & Tagesmutter', label: 'Über mich',
    description: 'Zertifizierte Babyschlafberaterin aus Eisingen bei Würzburg: Kindertagespflege seit 2010, rund 100 betreute Kinder, Montessori-Diplom und Kinderyoga. Beratung online in ganz Deutschland.',
    content: `${pageHead('Anna-Lena Korb', 'Echte Erfahrung. <em>Ein ehrlicher Blick.</em> Ein offenes Ohr.', 'Zertifizierte Babyschlafberaterin, qualifizierte Kindertagespflegeperson und Mama seit 2005. Zu Hause in Eisingen bei Würzburg, als Beraterin online für Familien in ganz Deutschland da.')}
    <section class="wrap personal-layout section-bottom">${portrait()}<div class="personal-copy" data-reveal><h2>Ich kenne Kinder <em>nicht nur aus Lehrbüchern.</em></h2><p>Seit 2010 bin ich Tagesmutter im Kinderkörbchen. Rund 100 Kinder, überwiegend zwischen null und drei Jahren, habe ich seitdem begleitet. Jedes bringt sein eigenes Tempo, seine Gewohnheiten und sein Bedürfnis nach Nähe mit.</p><p>Im Alltag gehören Schlafen und Ruhen genauso dazu wie Spielen und Entdecken. Ich erlebe, wie unterschiedlich Kinder zur Ruhe finden – und wie wichtig es ist, aufmerksam hinzusehen.</p><p>Meine Ausbildung zur Babyschlafberaterin habe ich gemacht, um Eltern auch über den Betreuungsalltag hinaus gezielt unterstützen zu können.</p>${childcare}</div></section>
    <section class="soft-section"><div class="wrap story" data-reveal><p class="kicker">Was ich aus eigener Erfahrung mitbringe</p><h2>Auch bei uns war Einschlafen <em>nicht einfach „Augen zu“.</em></h2><p class="lead">Als mein Kind etwa eineinhalb Jahre alt war, klappte das Einschlafen nur mit mir. Ich kenne das Gefühl, gebraucht zu werden – und sich gleichzeitig Entlastung zu wünschen.</p><p>Diese Erfahrung macht nicht jede Familiengeschichte gleich. Sie erinnert mich daran, erst zuzuhören. Ich möchte verstehen, was euch belastet, bevor wir über Veränderungen sprechen.</p><p class="signature">Anna-Lena<span>ehrlich · direkt · authentisch</span></p></div></section>
    <section class="section wrap" id="qualifikationen"><div class="section-heading" data-reveal><p class="kicker">Das bringe ich mit</p><h2>Praxis und Ausbildung. <em>Beides zählt.</em></h2><p>Die langjährige Erfahrung stammt aus der Kindertagespflege. Meine zusätzliche Qualifikation für die Schlafberatung habe ich 2026 abgeschlossen.</p></div><div class="credential-layout"><dl class="credentials" data-reveal><div><dt>Zertifizierte Babyschlafberaterin</dt><dd>Ausbildung erfolgreich abgeschlossen am 11. März 2026. Ausbildungsleitung: Melanie Heift-Budde.</dd></div><div><dt>Qualifizierte Kindertagespflegeperson</dt><dd>Seit 2010 tätig. Rund 100 Kinder in der Tagespflege begleitet.</dd></div><div><dt>Montessori-Diplom</dt><dd>Absolviert in Schweinfurt. Ergänzende pädagogische Qualifikation.</dd></div><div><dt>Kinderyogalehrerin</dt><dd>Ausbildung 2017. Bewegung und Ruhe als Teil des Alltags.</dd></div><div><dt>Fortbildungen & Erste Hilfe</dt><dd>Regelmäßige Fortbildungen und alle zwei Jahre ein Erste-Hilfe-Kurs für Kinder.</dd></div></dl>${certificate()}</div></section>
    ${promise}${closing()}`,
  },
  'schlafberatung.html': {
    title: 'Schlafberatung für Babys & Kleinkinder: Ablauf | Anna-Lena Korb', label: 'Beratung',
    description: 'Persönliche Schlafberatung für Familien mit Kindern von 0 bis 6 Jahren: Fragebogen, Schlafprotokoll, individueller Plan und Begleitung ohne Schreienlassen. Online in ganz Deutschland.',
    faq,
    service: { name: 'Schlafberatung für Babys und Kleinkinder', offers: offers.slice(1) },
    content: `${pageHead('So helfe ich euch', 'Schlaf verstehen. <em>Veränderung begleiten.</em>', 'Euer Ziel muss nicht „perfekt durchschlafen“ heißen. Es darf erst einmal heißen: weniger Belastung, mehr Orientierung und ein Abend, der sich wieder bewältigen lässt.')}
    <section class="wrap advice-intro section-bottom"><div data-reveal><h2>Was soll für euch <em>leichter werden?</em></h2><p>Vielleicht möchtest du nicht mehr jeden Abend stundenlang begleiten. Vielleicht soll auch ein anderer Elternteil beim Einschlafen helfen können. Oder ihr braucht einen Blick von außen auf euren Tagesablauf.</p><p>Wir vereinbaren ein Ziel, das zu Alter, Entwicklung und Bedürfnissen eures Kindes passt. Selbstständigeres Einschlafen kann ein Ziel sein – ist aber keine Pflicht für jedes Kind und nicht das Ziel der Neugeborenenberatung.</p></div><figure data-reveal style="--i:1">${photo('troesten', { cls: 'rounded' })}</figure></section>
    <section class="soft-section"><div class="wrap"><div class="section-heading" data-reveal><p class="kicker">Für wen</p><h2>Jedes Alter <em>braucht etwas anderes.</em></h2><p>Für Kinder von 0 bis 6 Jahren, ältere Kinder nach Absprache.</p></div><div class="age-grid"><article data-reveal><span class="age">0–3 Monate</span><h3>Neugeborene</h3><p>Orientierung, sichere Schlafbedingungen und Entlastung für euch. Kein Schlaftraining.</p></article><article data-reveal style="--i:1"><span class="age">4–12 Monate</span><h3>Babys</h3><p>Tagesrhythmus, Einschlafbegleitung und häufiges nächtliches Aufwachen.</p></article><article data-reveal style="--i:2"><span class="age">1–3 Jahre</span><h3>Kleinkinder</h3><p>Einschlafen nur mit einer Person, Tagschlaf, Kita-Start und neue Abläufe.</p></article><article data-reveal style="--i:3"><span class="age">3–6 Jahre</span><h3>Kindergartenkinder</h3><p>Abendroutinen, Ängste beim Einschlafen und nächtliches Wandern ins Elternbett.</p></article></div></div></section>
    <section class="section wrap"><div class="section-heading" data-reveal><p class="kicker">Vom Kennenlernen zur Umsetzung</p><h2>Ein nachvollziehbarer Ablauf. <em>Kein Rätselraten.</em></h2><p>Die Schlafsprechstunde beantwortet eine einzelne Frage. Bei den Begleitungspaketen gehen wir ausführlicher vor.</p></div>${process()}</section>
    <section class="soft-section"><div class="wrap two-col"><div data-reveal><p class="kicker">Ein genauer Blick – ohne Druck</p><h2>Eure Geschichte <em>gehört dazu.</em></h2></div><div data-reveal style="--i:1"><p>Der Fragebogen beschäftigt sich mit eurem Alltag, Schlafgewohnheiten und euren Wünschen. Schwangerschaft, Geburt und die erste Zeit mit eurem Kind können dabei ebenfalls angesprochen werden, soweit sie für eure Beratung relevant sind und ihr darüber sprechen möchtet.</p><p>Aus einer Geburtsgeschichte allein lässt sich keine Ursache für ein Schlafproblem ableiten. Die Schlafberatung stellt keine Diagnosen und ersetzt keine medizinische oder therapeutische Behandlung.</p><p>Vertrauliche Informationen gehören nicht in die öffentliche Terminanfrage. Den passenden Rahmen für ausführliche Angaben stimmen wir persönlich ab.</p></div></div></section>
    <section class="section wrap two-col"><div data-reveal><p class="kicker">Persönlich erreichbar</p><h2>Ein fester Rahmen. <em>Auch für Rückfragen.</em></h2></div><div data-reveal style="--i:1"><p>In den Begleitungspaketen könnt ihr Fragen per WhatsApp stellen. Ich antworte in der Regel innerhalb von 24 Stunden; sonntags und an Feiertagen am nächsten Beratungstag. Die Begleitung ist kein Live-Chat und keine Rund-um-die-Uhr-Betreuung.</p><p>Gespräche: Montag bis Freitag 17–19 Uhr und Samstag 9–13 Uhr, per Zoom oder Telefon in ganz Deutschland. Innerhalb Würzburgs und im Umkreis von etwa 10 bis 15 Kilometern sind persönliche Termine nach Absprache ohne zusätzliche Anfahrtskosten möglich.</p>${link('preise.html', 'Begleitung auswählen')}</div></section>
    <section class="section-bottom wrap faq-layout" id="fragen"><div data-reveal><p class="kicker">Häufige Fragen</p><h2>Gut zu wissen, <em>bevor wir starten.</em></h2></div>${questions(faq)}</section>${closing()}`,
  },
  'preise.html': {
    title: 'Babyschlafberatung Preise: ab 89 € | Anna-Lena Korb', label: 'Preise',
    description: 'Klare Gesamtpreise ohne Abo: Schlafsprechstunde 89 €, Basis 149 €, Intensiv 299 €, Premium 479 €. Persönlicher Schlafplan, Begleitung per WhatsApp, kostenloses Kennenlernen.',
    service: { name: 'Babyschlafberatung', offers: offers.slice(1) },
    content: `${pageHead('Angebote & Preise', 'Ein guter Anfang. <em>So viel Begleitung,</em> wie ihr braucht.', 'Ein konkretes Thema oder Unterstützung über mehrere Wochen: Ihr entscheidet nach dem kostenlosen Kennenlernen in Ruhe. Alle genannten Beträge sind Gesamtpreise.')}
    <section class="wrap intro-band" data-reveal><div><p class="kicker">20 Minuten nur für euch</p><h2>Das Kennenlernen <em>geht auf mich.</em></h2><p>Wir besprechen eure Situation und schauen, ob mein Angebot passt. Keine Zahlungspflicht, keine Paketpflicht.</p></div>${contact()}</section>
    <section class="wrap section-bottom" aria-label="Beratungspakete">${priceCards()}<article class="single-offer" id="sprechstunde" data-reveal><div><p class="kicker">Lieber erst eine konkrete Frage klären?</p><h2>Schlafsprechstunde</h2><p>45 Minuten per Zoom, ein klar abgegrenztes Thema und eine kurze schriftliche Zusammenfassung. Ohne vollständigen Schlafplan und ohne anschließende WhatsApp-Begleitung.</p></div><div class="single-price"><p class="price-value">89<span> €</span></p>${contact('Sprechstunde anfragen', 'button secondary', '?paket=Sprechstunde#anfrage')}<p class="tiny">Gesamtpreis</p></div></article></section>
    <section class="soft-section"><div class="wrap two-col"><div data-reveal><p class="kicker">Damit alles transparent bleibt</p><h2>Klare Leistungen. <em>Klare Grenzen.</em></h2></div><div class="terms" data-reveal style="--i:1"><h3>Persönlich, aber nicht rund um die Uhr.</h3><p>WhatsApp-Begleitung gilt nur im gebuchten Zeitraum. Antworten in der Regel innerhalb von 24 Stunden; sonntags und an Feiertagen am nächsten Beratungstag. Keine Live- oder Notfallbetreuung.</p><h3>Ein Plan, der auf eure Angaben aufbaut.</h3><p>Der schriftliche Schlafplan folgt innerhalb von 24 Stunden nach dem Beratungsgespräch, sofern die vereinbarten Unterlagen vollständig vorliegen. Die Begleitdauer startet zum gemeinsam vereinbarten Termin.</p><h3>Keine automatische Verlängerung.</h3><p>Vor einer kostenpflichtigen Vereinbarung erhaltet ihr Leistungsumfang, Preis und Vertragsinformationen. Zahlungsweise, eine mögliche Ratenzahlung und Terminänderungen werden persönlich vereinbart. Die Anfrage auf dieser Seite ist noch kein Vertrag.</p><p>Ich begleite höchstens drei Familien gleichzeitig. Ob gerade ein Platz frei ist, klären wir persönlich.</p><p class="small"><a href="agb.html">AGB</a> · <a href="widerruf.html">Widerrufsrecht</a></p></div></div></section>${closing()}`,
  },
  'kontakt.html': {
    title: 'Kostenlos kennenlernen & Termin anfragen | Anna-Lena Korb', label: 'Kennenlernen',
    description: 'Kostenloses 20-Minuten-Gespräch zur Babyschlafberatung anfragen. Per Zoom oder Telefon aus ganz Deutschland. Mo–Fr 17–19 Uhr, Sa 9–13 Uhr.',
    content: `${pageHead('Ein erster Schritt', 'Erzählt mir <em>von euch.</em>', '20 Minuten kostenlos kennenlernen. Ihr müsst noch nicht wissen, welches Angebot zu euch passt. Wir schauen gemeinsam darauf.')}
    <section class="wrap contact-grid section-bottom"><aside class="contact-aside"><h2>Hier ist Zeit für <em>eure Fragen.</em></h2><dl class="contact-details"><div><dt>Gesprächszeiten</dt><dd>Montag–Freitag: 17–19 Uhr<br>Samstag: 9–13 Uhr<br>Sonntag: geschlossen</dd></div><div><dt>Wo wir sprechen</dt><dd>Per Zoom oder Telefon, deutschlandweit.<br>Vor Ort in Würzburg und ca. 10–15 km Umkreis nach Absprache.</dd></div><div><dt>Rückmeldung</dt><dd>In der Regel innerhalb von 24 Stunden; sonntags und an Feiertagen am nächsten Beratungstag.</dd></div></dl><p>Du kannst mir auch direkt schreiben oder mich zu den Gesprächszeiten anrufen:</p><a class="email" href="mailto:${site.email}">${site.email}</a><a class="phone" href="tel:${site.telephone}">${site.telephoneDisplay}</a><p class="small">Eine Anfrage ist keine feste Buchung und löst keine Zahlungspflicht aus.</p></aside>
    <div id="anfrage"><div data-booking hidden><form id="booking-form" class="booking-form"><div class="form-heading"><p class="kicker">Deine Terminanfrage</p><h2>Was passt in euren Alltag?</h2><p>Wähle bis zu drei Wunschzeiten. Ich bestätige dir anschließend einen passenden Termin per E-Mail.</p></div>
    <div class="field"><label for="interest">Worum geht es?</label><select id="interest" name="interest">${offers.map(o => `<option value="${o.id}">${o.name} · ${o.price ? `${o.price} €` : 'kostenlos'}</option>`).join('')}</select></div>
    <fieldset class="calendar-fieldset"><legend>1. Wunschtermine auswählen</legend><p id="calendar-help" class="form-help">Mindestens sieben Tage Vorlauf. Alle Zeiten sind deutsche Ortszeit. Die angezeigten Zeiten sind anfragbar, aber noch nicht reserviert.</p><div class="calendar"><div class="calendar-toolbar"><button type="button" class="icon-button" data-prev aria-label="Vorheriger Monat">←</button><h3 id="calendar-month" aria-live="polite"></h3><button type="button" class="icon-button" data-next aria-label="Nächster Monat">→</button></div><div class="weekdays" aria-hidden="true"><span>Mo</span><span>Di</span><span>Mi</span><span>Do</span><span>Fr</span><span>Sa</span><span>So</span></div><div class="calendar-days" id="calendar-days" role="group" aria-label="Tag auswählen"></div></div><details class="date-alternative"><summary>Datum direkt eingeben</summary><label for="request-date">Wunschdatum</label><input type="date" id="request-date" aria-describedby="calendar-help"></details><div id="time-options" class="time-options" role="group" aria-label="Uhrzeit auswählen"></div><p id="time-hint" class="form-help" aria-live="polite"></p><div class="proposals"><h3>Deine Wunschzeiten <span id="proposal-count">0 / 3</span></h3><ul id="proposal-list"></ul><p id="selection-status" role="status" aria-live="polite" class="small">Noch keine Zeit ausgewählt.</p></div></fieldset>
    <fieldset><legend>2. So erreiche ich dich</legend><div class="form-row"><div class="field"><label for="name">Dein Name</label><input id="name" name="name" autocomplete="name" required minlength="2" maxlength="100"></div><div class="field"><label for="email">Deine E-Mail-Adresse</label><input id="email" name="email" type="email" autocomplete="email" required maxlength="254"></div></div><div class="field"><label for="format">Gesprächsformat</label><select id="format" name="format"><option>Zoom</option><option>Telefon</option></select><p class="form-help">Bei einem Telefongespräch stimmen wir die Rufnummer per E-Mail ab.</p></div><div class="field"><label for="message">Was möchtest du mir vorab sagen? <span>(optional)</span></label><textarea id="message" name="message" rows="3" maxlength="1200" placeholder="Zum Beispiel: Das Einschlafen dauert gerade sehr lange."></textarea><p class="form-help">Bitte keine Diagnosen, Befunde oder Details zu Schwangerschaft und Geburt. Ausführliche Angaben besprechen wir vertraulich im Beratungsprozess.</p></div></fieldset>
    <p class="form-help">Diese Auswahl wird nur in deinem Browser vorbereitet. Erst wenn du die E-Mail in deinem Mailprogramm oder Gmail selbst absendest, erreicht sie Anna-Lena. <a href="datenschutz.html">Datenschutzhinweise</a></p><button type="submit" class="button full">Anfrage als E-Mail vorbereiten${arrow}</button><p id="booking-status" class="form-status" role="status" tabindex="-1"></p></form>
    <section id="request-result" class="request-result" aria-labelledby="result-title" hidden><p class="kicker">Schritt 3 · Noch nicht versendet</p><h2 id="result-title" tabindex="-1">Deine Anfrage ist vorbereitet.</h2><p>Öffne den Entwurf und sende die E-Mail selbst ab. Erst nach Anna-Lenas persönlicher Bestätigung ist ein Termin vereinbart.</p><label for="request-preview">Dein E-Mail-Entwurf</label><textarea id="request-preview" readonly rows="12"></textarea><div class="actions"><a id="open-mail" class="button" href="mailto:${site.email}">Im E-Mail-Programm öffnen</a><a id="open-gmail" class="button secondary" href="https://mail.google.com/" target="_blank" rel="noopener noreferrer">In Gmail öffnen</a><button type="button" class="button secondary" id="copy-request">Text kopieren</button><button type="button" class="text-button" id="edit-request">Auswahl bearbeiten</button></div><p class="small">Mit „In Gmail öffnen“ wird der Entwurf an Google übergeben. Alternativ den Text kopieren und an ${site.email} senden.</p><p id="copy-status" role="status" class="small"></p></section></div>
    <noscript><div class="note"><h2>Termin per E-Mail anfragen</h2><p>Bitte nenne bis zu drei Wunschtermine mit mindestens sieben Tagen Vorlauf: Montag bis Freitag 17–19 Uhr oder Samstag 9–13 Uhr. Anna-Lena bestätigt dir einen passenden Termin.</p><a href="mailto:${site.email}" class="button">E-Mail schreiben</a><p><a href="mailto:${site.email}">${site.email}</a></p></div></noscript><p class="small fallback-contact">Wenn die Terminauswahl nicht angezeigt wird oder nicht funktioniert: <a href="mailto:${site.email}">Schreibe mir direkt eine E-Mail</a>.</p></div></section>`,
  },
  'baby-einschlafen.html': {
    title: 'Baby einschlafen: sanft begleiten statt kämpfen | Ratgeber', label: 'Baby einschlafen',
    description: 'Euer Baby schläft abends schwer ein? Müdigkeitszeichen erkennen, ein Abendritual, das trägt, und kleine Schritte ohne Schreienlassen. Ratgeber von Babyschlafberaterin Anna-Lena Korb.',
    faq: einschlafenFaq,
    article: { headline: 'Baby einschlafen: sanft begleiten statt jeden Abend kämpfen', published: '2026-10-09', image: 'einschlafen' },
    content: `${pageHead('Ratgeber · Einschlafen', 'Baby einschlafen: <em>sanft begleiten</em> statt jeden Abend kämpfen.', 'Wenn das Einschlafen eine Stunde oder länger dauert, kostet das Kraft. Hier findet ihr, was hinter schwierigen Abenden stecken kann und welche kleinen Schritte oft mehr bewirken als ein radikaler Umbruch.')}
    ${article({ minutes: 6, related: 'baby-einschlafen.html', image: 'einschlafen',
      toc: [['warum', 'Warum Einschlafen anspruchsvoll ist'], ['muedigkeit', 'Müdigkeit erkennen'], ['ritual', 'Ein Abendritual, das trägt'], ['nur-mit-mama', 'Wenn es nur mit einer Person klappt'], ['schritte', 'Veränderung in kleinen Schritten'], ['sicher', 'Sicher einschlafen'], ['hilfe', 'Wann Hilfe sinnvoll ist'], ['fragen', 'Häufige Fragen']],
      body: `<h2 id="warum">Warum Einschlafen für Babys so anspruchsvoll ist</h2><p>Einschlafen ist ein Übergang: vom wachen, aufmerksamen Zustand in den Schlaf. Dafür muss ein Kind zur Ruhe kommen und sich sicher fühlen. Babys und kleine Kinder können das noch nicht allein regulieren. Sie brauchen dafür Erwachsene, die ihnen Halt geben.</p><p>Dass euer Kind Nähe zum Einschlafen sucht, ist deshalb kein Erziehungsfehler und keine „schlechte Angewohnheit“. Es wird erst dann zum Thema, wenn der Ablauf euch dauerhaft überfordert oder ihr euch mehr Flexibilität wünscht.</p>
      <h2 id="muedigkeit">Müdigkeit erkennen, bevor sie kippt</h2><p>Viele lange Abende haben weniger mit dem Einschlafen selbst zu tun als mit dem Zeitpunkt. Ist ein Kind noch nicht müde genug, wird es unruhig. Ist es übermüdet, wirkt es oft paradoxerweise aufgedreht.</p><ul><li>Gähnen, Augenreiben, Ziehen an den Ohren</li><li>Ein starrer, abwesender Blick oder Wegdrehen</li><li>Quengeln und weniger Interesse an Spiel und Umgebung</li></ul><p>Achtet eine Woche lang darauf, wann diese Zeichen auftreten. Ein einfaches Schlafprotokoll hilft, Muster zu sehen, die im Alltag untergehen. Beobachtet dabei euer Kind, nicht nur die Uhr: Wachphasen sind von Kind zu Kind verschieden.</p>
      <h2 id="ritual">Ein Abendritual, das wirklich trägt</h2><p>Ein gutes Abendritual ist kurz, vorhersehbar und ruhig. Es kündigt dem Kind an: Jetzt kommt der Schlaf. Entscheidend ist weniger, was ihr macht, sondern dass es jeden Abend ähnlich abläuft.</p><ul><li>Gleiche Reihenfolge, zum Beispiel Wickeln, Schlafanzug, Licht dimmen, ein Lied</li><li>Etwa 20 bis 30 Minuten statt eines langen Programms</li><li>Wenig Bildschirm, wenig Trubel, gedämpftes Licht</li><li>Ein Ablauf, den auch der andere Elternteil übernehmen kann</li></ul>
      <h2 id="nur-mit-mama">Wenn Einschlafen nur mit einer Person klappt</h2><p>Sehr viele Familien kennen das: Einschlafen funktioniert nur mit Mama – oder nur mit Papa. Für die betreffende Person bedeutet das oft, keinen Abend mehr für sich zu haben.</p><p>Hilfreich ist ein schrittweiser Wechsel. Der andere Elternteil übernimmt zuerst Teile des Rituals, später ist er beim Einschlafen dabei und schließlich allein zuständig. Dass ein Kind die Veränderung erst einmal nicht gut findet und das zeigt, ist normal. Es darf dabei getröstet werden. Begleitet wird es weiterhin von einer vertrauten Person.</p>
      <h2 id="schritte">Veränderung in kleinen Schritten</h2><p>Statt alles auf einmal umzustellen, verändert ihr immer nur eine Sache und bleibt dabei ein paar Tage verlässlich. So kann sich euer Kind auf das Neue einstellen, und ihr seht, was tatsächlich wirkt.</p><p>Kontrolliertes Schreienlassen ist dafür nicht nötig. Ihr bleibt ansprechbar und tröstet, wenn euer Kind euch braucht. Konsequent zu sein heißt, freundlich bei der vereinbarten Veränderung zu bleiben – nicht, Signale zu ignorieren.</p>
      <h2 id="sicher">Sicher einschlafen</h2><p>Bei Säuglingen hat ein sicherer Schlafplatz immer Vorrang. Das Bundesinstitut für Öffentliche Gesundheit (BIÖG) empfiehlt unter anderem die Rückenlage, einen Schlafsack statt Decke, eine eher feste Matratze ohne Kissen, Nestchen oder Felle, ein eigenes Bett im Elternschlafzimmer, eine rauchfreie Umgebung und keine zu warme Kleidung.</p><p>Die vollständigen Empfehlungen: <a href="https://www.kindergesundheit-info.de/themen/schlafen/0-12-monate/schlafumgebung/">BIÖG: Die richtige Schlafumgebung für das Baby</a>.</p>
      <h2 id="hilfe">Wann Hilfe sinnvoll ist</h2><p>Wenn die Abende euch über Wochen alle Kraft kosten, wenn ihr euch im Kreis dreht oder euch zwischen widersprüchlichen Ratschlägen nicht entscheiden könnt, kann ein Blick von außen helfen. In einer <a href="schlafberatung.html">Schlafberatung</a> schauen wir gemeinsam auf euren Alltag und entwickeln einen Plan, der zu euch passt.</p><p>Wenn ihr gesundheitliche Ursachen vermutet, etwa Atemauffälligkeiten, Schmerzen oder Trinkschwierigkeiten, ist zuerst die Kinderarztpraxis die richtige Anlaufstelle.</p>
      <h2 id="fragen">Häufige Fragen zum Einschlafen</h2>${questions(einschlafenFaq)}` })}${closing('Ihr wünscht euch <em>ruhigere Abende?</em>')}`,
  },
  'baby-durchschlafen.html': {
    title: 'Baby schläft nicht durch: Was normal ist & was hilft | Ratgeber', label: 'Baby schläft nicht durch',
    description: 'Euer Baby wacht nachts oft auf? Was „Durchschlafen“ wirklich bedeutet, häufige Gründe für nächtliches Aufwachen und was ihr ausprobieren könnt. Ohne Schreienlassen.',
    faq: durchschlafenFaq,
    article: { headline: 'Baby schläft nicht durch: Was normal ist und was helfen kann', published: '2026-10-09', image: 'babybett' },
    content: `${pageHead('Ratgeber · Durchschlafen', 'Baby schläft nicht durch: <em>Was normal ist</em> und was helfen kann.', 'Nächtliches Aufwachen gehört zur Entwicklung. Trotzdem darf es euch zu viel werden. Hier lest ihr, was hinter häufigem Aufwachen stecken kann und wo ihr ansetzen könnt.')}
    ${article({ minutes: 7, related: 'baby-durchschlafen.html', image: 'babybett',
      toc: [['bedeutung', 'Was „Durchschlafen“ bedeutet'], ['gruende', 'Häufige Gründe für Aufwachen'], ['ausprobieren', 'Was ihr ausprobieren könnt'], ['limit', 'Wenn ihr am Limit seid'], ['arzt', 'Wann ärztlich abklären?'], ['fragen', 'Häufige Fragen']],
      body: `<h2 id="bedeutung">Was „Durchschlafen“ eigentlich bedeutet</h2><p>Wenn Eltern von Durchschlafen sprechen, meinen sie oft zehn bis zwölf Stunden am Stück. In Studien wird der Begriff oft viel bescheidener verwendet: als längere Schlafphase von etwa fünf bis sechs Stunden.</p><p>Auch Erwachsene wachen nachts zwischen ihren Schlafzyklen kurz auf, erinnern sich aber meist nicht daran. Babys haben kürzere Schlafzyklen und brauchen beim Übergang häufiger Unterstützung. Viele Kinder wachen deshalb im ersten Lebensjahr und auch danach noch nachts auf. Das ist entwicklungsbedingt normal.</p>
      <h2 id="gruende">Häufige Gründe für nächtliches Aufwachen</h2><ul><li><strong>Hunger:</strong> Gerade in den ersten Monaten sind nächtliche Mahlzeiten normal und wichtig.</li><li><strong>Entwicklungsschritte:</strong> Krabbeln, Laufen, Sprechen, Zahnen oder Trennungsangst können Nächte vorübergehend unruhiger machen.</li><li><strong>Einschlafbedingungen:</strong> Ein Kind, das mit bestimmter Hilfe einschläft, erwartet sie oft auch beim nächtlichen Aufwachen.</li><li><strong>Tagesrhythmus:</strong> Zu wenig oder sehr später Tagschlaf und eine unpassende Schlafenszeit wirken sich auf die Nacht aus.</li><li><strong>Umgebung:</strong> Zu warm, zu hell oder zu laut. Das BIÖG nennt etwa 18 °C als günstige Schlafzimmertemperatur.</li><li><strong>Krankheit:</strong> Infekte oder Schmerzen. Hier geht Versorgung vor Veränderung.</li></ul>
      <h2 id="ausprobieren">Was ihr ausprobieren könnt</h2><p><strong>Beobachten statt raten.</strong> Notiert eine Woche lang Schlafzeiten, Aufwachzeiten und was euer Kind gebraucht hat. Oft zeigt sich ein Muster, etwa ein zu später Mittagsschlaf oder ein Abend, der zu spät beginnt.</p><p><strong>Abend und Nacht angleichen.</strong> Wenn sich die Bedingungen beim Einschlafen und beim nächtlichen Aufwachen stark unterscheiden, fällt das Weiterschlafen schwerer. Kleine Veränderungen beim Einschlafen wirken sich häufig auch auf die Nacht aus.</p><p><strong>Nächte ruhig und reizarm halten.</strong> Wenig Licht, wenig Sprechen, keine Spielangebote. So bleibt die Nacht für euer Kind klar als Nacht erkennbar.</p><p><strong>Aufgaben teilen.</strong> Wenn möglich, wechselt euch ab oder verteilt die Nacht in Schichten, damit jede Person einmal einen längeren Schlafblock bekommt.</p>
      <h2 id="limit">Wenn ihr am Limit seid</h2><p>Dauerhafter Schlafmangel ist belastend. Wenn ihr merkt, dass euch die Kraft ausgeht, nehmt das ernst und holt euch Unterstützung: im Umfeld, bei eurer Hebamme oder Kinderarztpraxis oder bei den Frühen Hilfen eurer Stadt oder eures Landkreises, die Familien mit kleinen Kindern begleiten.</p><p>Eine <a href="schlafberatung.html">Schlafberatung</a> kann euch helfen, eure Situation zu sortieren und realistische nächste Schritte zu finden – ohne Schreienlassen und ohne Durchschlafgarantie.</p>
      <h2 id="arzt">Wann ihr ärztlich abklären solltet</h2><p>Lasst euer Kind kinderärztlich anschauen, wenn ihr zum Beispiel lautes Schnarchen, Atempausen oder angestrengtes Atmen im Schlaf bemerkt, wenn euer Kind Schmerzen zu haben scheint, schlecht trinkt oder isst oder sich sein Schlaf plötzlich stark verändert, ohne dass ihr einen Grund erkennt.</p><p>Hintergrund zum Schlaf im ersten Lebensjahr: <a href="https://www.kindergesundheit-info.de/themen/schlafen/0-12-monate/">BIÖG: Schlafen im ersten Lebensjahr</a>.</p>
      <h2 id="fragen">Häufige Fragen zum Durchschlafen</h2>${questions(durchschlafenFaq)}` })}${closing('Ihr wünscht euch <em>ruhigere Nächte?</em>')}`,
  },
  'schlafwissen.html': {
    title: 'Babyschlaf-Ratgeber: Einschlafen, Durchschlafen, sicherer Schlaf', label: 'Ratgeber',
    description: 'Erste Orientierung zu Babyschlaf: Einschlafbegleitung, nächtliches Aufwachen und sichere Schlafumgebung. Eigenständig geschrieben, mit Quellen von BIÖG und WHO.',
    content: `${pageHead('Ratgeber', 'Weniger widersprüchliche Tipps. <em>Mehr Orientierung.</em>', 'Eine erste Einordnung für müde Eltern. Diese Informationen ersetzen keine individuelle Beratung oder ärztliche Untersuchung.')}
    <section class="wrap section-bottom">${guideCards('schlafwissen.html')}</section>
    <section class="soft-section"><div class="wrap"><div class="section-heading" data-reveal><p class="kicker">Grundlagen</p><h2>Vier Dinge, <em>die ihr wissen solltet.</em></h2></div><div class="knowledge-list"><article data-reveal><span class="tag">Erwartungen</span><h3>Nicht jedes Aufwachen ist ein Problem.</h3><p>Wie Schlaf sich entwickelt, ist individuell. Statt alle Kinder an einer festen Stundenzahl zu messen, lohnt der Blick auf Alter, Entwicklung und die Belastung im Familienalltag. Welche Veränderung wäre für euch tatsächlich hilfreich?</p><p>Hintergrund und altersbezogene Informationen: <a href="https://www.kindergesundheit-info.de/themen/schlafen/0-12-monate/">BIÖG: Schlafen im ersten Lebensjahr</a>.</p></article>
    <article data-reveal style="--i:1"><span class="tag">Einschlafgewohnheiten</span><h3>Nähe ist keine schlechte Gewohnheit.</h3><p>Wenn Einschlafbegleitung belastend wird, darf sich etwas verändern. Das ist kein Anlass, Eltern Vorwürfe zu machen. Ein Beratungsziel kann sein, neue Abläufe zu finden oder die Begleitung auf mehrere vertraute Personen zu verteilen.</p><p>Stillen nach dem ersten Geburtstag ist nicht automatisch ein Problem. Die WHO empfiehlt neben passender Beikost weiteres Stillen bis zum Alter von zwei Jahren oder darüber hinaus. Daraus folgt keine Verpflichtung für einzelne Familien – und auch keine pauschale Pflicht zum Abstillen für eine Schlafberatung. <a href="https://www.who.int/news-room/fact-sheets/detail/infant-and-young-child-feeding">WHO: Infant and young child feeding</a>.</p></article>
    <article data-reveal id="sicher"><span class="tag">Sicherer Babyschlaf</span><h3>Der sichere Schlafplatz hat Vorrang.</h3><p>Für Säuglinge empfiehlt das BIÖG die Rückenlage, eine feste, ebene Matratze und einen eigenen Schlafplatz im Elternschlafzimmer. Kissen und weiche Nestchen gehören nicht ins Babybett. Selbstständigeres Einschlafen bedeutet nicht, dass ein Baby allein in einem anderen Zimmer schlafen soll.</p><p>Die vollständigen Empfehlungen findet ihr beim <a href="https://www.kindergesundheit-info.de/themen/schlafen/0-12-monate/schlafumgebung/">BIÖG: Die richtige Schlafumgebung für das Baby</a>.</p></article>
    <article data-reveal style="--i:1"><span class="tag">Grenzen der Beratung</span><h3>Manche Fragen gehören in die Kinderarztpraxis.</h3><p>Die Schlafberatung beschäftigt sich mit Alltag, Routinen und Begleitung. Sie ist keine medizinische Diagnostik oder Therapie. Bei gesundheitlichen Beschwerden lasst mögliche Ursachen kinderärztlich abklären, bevor ihr sie als reine Schlafgewohnheit einordnet.</p>${link('schlafberatung.html#fragen', 'Fragen zur Beratung')}</article></div></div></section>
    <section class="section wrap"><div class="story" data-reveal><p class="kicker">Quellen statt Erfolgsversprechen</p><h2>Nachvollziehbar bleiben.</h2><p>Die verlinkten Fachinformationen stammen vom Bundesinstitut für Öffentliche Gesundheit und der Weltgesundheitsorganisation. Die Texte in diesem Ratgeber sind eigenständige Zusammenfassungen, keine übernommenen Ratgeberartikel. Stand der Quellenprüfung: 9. Oktober 2026 (Schlafumgebung) und 13. September 2026 (übrige Quellen).</p></div></section>${closing()}`,
  },
  '404.html': {
    title: 'Seite nicht gefunden | Anna-Lena Korb', description: 'Zurück zur Babyschlafberatung von Anna-Lena Korb.', label: 'Seite nicht gefunden', noindex: true,
    content: `${pageHead('404 · Hier geht es nicht weiter', 'Zurück zu einem <em>guten Anfang.</em>', 'Diese Seite existiert nicht oder wurde verschoben. Auf der Startseite findest du alle Informationen zur Schlafberatung.')}<div class="wrap section-bottom actions"><a href="index.html" class="button">Zur Startseite${arrow}</a>${contact('Kennenlernen', 'button secondary')}</div>`,
  },
};
