import { site, offers } from '../assets/config.js';
import { contact, link, arrow, closing, pageHead, portrait, photo, questions, childcare, updated } from './layout.mjs';

const faq = [
  ['Für welches Alter ist die Beratung gedacht?', 'Ich begleite Familien mit Kindern von 0 bis 6 Jahren; ältere Kinder nach Absprache. Bei Neugeborenen geht es um Orientierung, sichere Schlafbedingungen und die Entlastung der Eltern – nicht darum, selbstständiges Einschlafen oder Durchschlafen zu verlangen. Ziele und Vorgehen richten sich nach Alter und Entwicklung.'],
  ['Muss mein Kind alleine weinen?', 'Nein. Kontrolliertes Schreienlassen gehört nicht zu meiner Beratung. Wir entwickeln einen klaren Plan und begleiten Veränderungen. Wenn euer Kind Trost braucht, bleibt ihr ansprechbar. Nähe ist kein Fehler.'],
  ['Müssen wir abstillen oder alles sofort verändern?', 'Nein. Stillen, Schnuller oder Einschlafbegleitung sind nicht automatisch ein Problem. Wir schauen ehrlich darauf, was euch belastet und was ihr verändern möchtet. Es gibt keine pauschale Pflicht zum Abstillen oder zum Wechsel des Schlafplatzes. Bei Säuglingen haben Ernährung und sichere Schlafbedingungen Vorrang.'],
  ['Versprichst du, dass unser Kind danach durchschläft?', 'Nein. Ich verspreche euch eine persönliche Begleitung und nachvollziehbare Schritte, aber keinen bestimmten Erfolg in einer festen Zahl von Nächten. Schlaf entwickelt sich individuell. Wir vereinbaren realistische Ziele und prüfen gemeinsam, was euch hilft.'],
  ['Wie funktioniert das Kennenlernen?', 'Ihr fragt einen Termin mindestens sieben Tage im Voraus an. Das Gespräch dauert 20 Minuten und ist kostenlos. Danach entscheidet ihr in Ruhe, ob ihr weitermachen möchtet und welches Angebot zu euch passt. Eine Anfrage löst keine Zahlungspflicht aus.'],
  ['Funktioniert die Beratung auch, wenn wir nicht in der Nähe wohnen?', 'Ja. Die Gespräche finden per Zoom oder Telefon statt, deshalb ist es egal, wo in Deutschland ihr wohnt. In Würzburg und im Umkreis von etwa 10 bis 15 Kilometern sind zusätzlich persönliche Termine nach Absprache möglich, ohne zusätzliche Anfahrtskosten.'],
  ['Wann bekomme ich eine Antwort?', 'Beratungszeiten sind Montag bis Freitag von 17 bis 19 Uhr und Samstag von 9 bis 13 Uhr. Auf Anfragen und begleitende WhatsApp-Nachrichten antworte ich in der Regel innerhalb von 24 Stunden; sonntags und an Feiertagen erfolgt die Antwort am nächsten Beratungstag. Chatbegleitung ist keine ständige Erreichbarkeit.'],
  ['Was ist bei gesundheitlichen Beschwerden?', 'Meine Schlafberatung ersetzt keine ärztliche Untersuchung, Diagnose oder Behandlung. Bei möglichen gesundheitlichen Ursachen ist eure Kinderarztpraxis die richtige Anlaufstelle. Die Beratung ist kein Notfalldienst.'],
];

const onlineFaq = [
  ['Brauchen wir für Zoom ein eigenes Konto?', 'Nein. Ihr bekommt einen Link und könnt über Smartphone, Tablet oder Laptop teilnehmen. Wenn euch ein Videogespräch nicht liegt, sprechen wir bei den Begleitungspaketen auch gern per Telefon.'],
  ['Ist eine Beratung per Video genauso persönlich?', 'Für Schlafberatung ja. Wir sprechen ausführlich über euren Alltag, euren Abend und eure Nächte. Ihr sitzt dabei in eurer gewohnten Umgebung und müsst mit Baby nirgendwohin fahren. Wenn ihr möchtet, könnt ihr mir den Schlafplatz auch kurz per Kamera zeigen.'],
  ['Können beide Elternteile teilnehmen?', 'Sehr gern, auch von zwei verschiedenen Orten aus. Gerade wenn ihr euch das Einschlafen künftig besser aufteilen möchtet, ist es hilfreich, wenn beide dabei sind.'],
  ['Wie bekommen wir den Schlafplan?', 'Bei Basis, Intensiv und Premium erhaltet ihr euren schriftlichen Plan innerhalb von 24 Stunden nach dem Beratungsgespräch, sofern die vereinbarten Unterlagen vollständig vorliegen. Rückfragen klären wir in der vereinbarten Begleitzeit per WhatsApp.'],
];

const packages = [
  { id: 'basis', name: 'Basis', price: 149, duration: 'Beratung + 7 Tage Begleitung', text: 'Ihr möchtet eure Situation verstehen und mit einem konkreten Plan loslegen.', items: ['Ausführlicher Fragebogen und Auswertung', '60 Minuten per Zoom oder Telefon', 'Individueller schriftlicher Schlafplan innerhalb von 24 Stunden nach dem Gespräch', '7 Tage WhatsApp-Begleitung für Rückfragen'] },
  { id: 'intensiv', name: 'Intensiv', price: 299, duration: '3 Wochen an eurer Seite', text: 'Ihr möchtet neue Routinen ausprobieren und dabei regelmäßig Rückmeldung bekommen.', items: ['Fragebogen, Schlafprotokoll und Auswertung', '60 Minuten Erstberatung per Zoom oder Telefon', 'Individueller Plan innerhalb von 24 Stunden', '3 Folgegespräche à 30 Minuten', '3 Wochen WhatsApp-Begleitung', 'Anpassungen des Plans während der Begleitung'] },
  { id: 'premium', name: 'Premium', price: 479, duration: '6 Wochen persönliche Begleitung', text: 'Ihr wünscht euch über einen längeren Zeitraum Orientierung und kontinuierlichen Austausch.', items: ['Fragebogen, Schlafprotokoll und Auswertung', '60 Minuten Erstberatung per Zoom oder Telefon', 'Individueller Plan innerhalb von 24 Stunden', '5 Folgegespräche à 30 Minuten', '6 Wochen WhatsApp-Begleitung', 'Regelmäßige Auswertung und Plananpassungen'] },
];

const check = `<svg class="icon-check" aria-hidden="true" viewBox="0 0 20 20" width="18" height="18"><path d="M4.5 10.5l3.5 3.5 7.5-8" fill="none" stroke="currentColor" stroke-width="1.7" stroke-linecap="round" stroke-linejoin="round"/></svg>`;
const cross = `<svg class="icon-cross" aria-hidden="true" viewBox="0 0 20 20" width="18" height="18"><path d="M6 6l8 8M14 6l-8 8" fill="none" stroke="currentColor" stroke-width="1.7" stroke-linecap="round"/></svg>`;

// Home page FAQ: own questions, so no answer appears on two pages.
const homeFaq = [
  ['Für welche Familien ist die Babyschlafberatung gedacht?', 'Für Eltern von Babys und Kindern bis sechs Jahre, die sich ruhigere Abende oder Nächte wünschen und dabei keinen Weg über Schreienlassen gehen möchten. Ob Neugeborenes, Baby im ersten Jahr oder Kindergartenkind: Ziele und Tempo richten sich nach eurem Kind und eurem Alltag.'],
  ['Wie läuft die Beratung online ab?', 'Nach dem kostenlosen Kennenlernen bekommt ihr je nach Paket einen Fragebogen und bei Intensiv und Premium ein Schlafprotokoll. Das Beratungsgespräch findet per Zoom oder Telefon statt, danach erhaltet ihr euren schriftlichen Plan. Alle Schritte im Detail findet ihr unter <a href="ablauf.html">Ablauf</a>.'],
  ['Was unterscheidet deine Beratung von Schlafprogrammen?', 'Bei mir gibt es kein festes Programm, das für alle Kinder gleich abläuft. Wir schauen auf euer Kind, euren Tagesablauf und darauf, was ihr verändern möchtet. Daraus entsteht ein Plan in kleinen Schritten, den ihr mit Nähe und Trost umsetzen könnt.'],
  ['Wie schnell ist ein Termin möglich?', 'Für das Kennenlernen braucht es mindestens sieben Tage Vorlauf. Weil ich höchstens drei Familien gleichzeitig begleite, klären wir im Gespräch, wann eure Beratung starten kann.'],
];
const generalExtraFaq = [
  ['Was kostet die Schlafberatung?', 'Das Kennenlernen ist kostenlos. Die Schlafsprechstunde kostet 89 €, die Pakete Basis 149 €, Intensiv 299 € und Premium 479 €. Alle Beträge sind Gesamtpreise ohne Abo. Was jeweils enthalten ist, steht unter <a href="preise.html">Kosten</a>.'],
  ['Was ist, wenn wir einen Termin verschieben müssen?', 'Das kommt mit kleinen Kindern vor. Sagt mir bitte so früh wie möglich Bescheid. Bis 24 Stunden vor einem Termin ist eine Verschiebung kostenfrei möglich. Die Einzelheiten stehen in den <a href="agb.html">AGB</a>.'],
  ['Wie viele Familien begleitest du gleichzeitig?', 'Höchstens drei. So bleibt genug Zeit für eure Rückfragen und für Anpassungen am Plan. Ob gerade ein Platz frei ist, besprechen wir im Kennenlernen.'],
];
const babyFaq = [
  ['Ab wann ist eine Babyschlafberatung sinnvoll?', 'Eine Beratung ist ab den ersten Lebenswochen möglich. Bei Neugeborenen geht es um Orientierung, sichere Schlafbedingungen und darum, wie ihr euch die Nächte aufteilen könnt. Ab etwa vier Monaten rücken Tagesrhythmus und Einschlafbegleitung stärker in den Blick.'],
  ['Darf mein Baby beim Stillen oder im Arm einschlafen?', 'Ja. Im ersten Lebensjahr ist das verbreitet und kein Fehler. Wenn es euch belastet, verändern wir Abläufe schrittweise und ohne Druck zum Abstillen. Ernährung und ein sicherer Schlafplatz haben dabei immer Vorrang.'],
  ['Muss unser Baby im eigenen Zimmer schlafen?', 'Nein. Für das erste Lebensjahr empfiehlt das BIÖG ein eigenes Bett im Elternschlafzimmer. Selbstständigeres Einschlafen heißt nicht, dass euer Baby allein in einem anderen Raum schlafen soll.'],
];
const toddlerFaq = [
  ['Unser Kind kommt jede Nacht ins Elternbett. Ist das ein Problem?', 'Nur wenn es euch stört. Viele Familien schlafen gern nah beieinander. Wenn ihr euch mehr Platz oder ruhigere Nächte wünscht, entwickeln wir einen Weg, den euer Kind versteht und der ohne Strafen auskommt.'],
  ['Hilft eine Schlafberatung beim Kita-Start?', 'Ein neuer Alltag bringt den Schlaf oft durcheinander, etwa wenn sich der Mittagsschlaf verschiebt oder ganz wegfällt. Gemeinsam passen wir Tagesablauf, Schlafenszeit und Abendritual an die neue Situation an. Aus der Kindertagespflege kenne ich diese Übergänge gut.'],
  ['Wie lange dauert eine Umstellung bei Kleinkindern?', 'Das ist von Kind zu Kind verschieden, eine feste Zahl an Nächten verspreche ich nicht. Bei Kleinkindern ist eine Begleitung über mehrere Wochen oft sinnvoll, damit wir den Plan nach euren Erfahrungen anpassen können.'],
];

// Detailed steps live on the Ablauf page only; home and online page use their own short versions.
const steps = [
  ['Erst einmal erzählen.', '20 Minuten kostenlos kennenlernen. Was ist gerade schwierig? Was wünscht ihr euch? Danach entscheidet ihr, ob ihr eine Beratung möchtet.'],
  ['Eure Situation verstehen.', 'Fragebogen, Schlafprotokoll und ein persönliches Gespräch helfen uns, genauer hinzusehen. Auch eure Familiengeschichte darf dabei Raum bekommen.'],
  ['Einen klaren Plan bekommen.', 'Bei Basis, Intensiv und Premium bekommt ihr innerhalb von 24 Stunden nach dem Gespräch euren schriftlichen Plan mit konkreten nächsten Schritten.'],
  ['Ausprobieren. Nachfragen. Anpassen.', 'Je nach Angebot bleibe ich sieben Tage, drei oder sechs Wochen an eurer Seite. Ein Plan soll im echten Leben funktionieren – nicht nur auf Papier.'],
];
const homeSteps = [
  ['Kennenlernen', 'Ein kostenloses Gespräch von 20 Minuten, in dem ihr erzählt, was euch gerade belastet.'],
  ['Verstehen', 'Mit Fragebogen und Beratungsgespräch verschaffen wir uns ein genaues Bild von eurem Alltag.'],
  ['Plan', 'Ihr bekommt konkrete nächste Schritte, schriftlich und passend zum Alter eures Kindes.'],
  ['Begleitung', 'Ich bleibe in der gebuchten Zeit ansprechbar, und wir passen den Plan gemeinsam an.'],
];
const onlineSteps = [
  ['Termin vereinbaren', 'Nach eurer Anfrage bestätige ich den Termin und schicke euch den Zoom-Link, oder wir vereinbaren ein Telefonat.'],
  ['Gespräch von zu Hause', 'Ihr nehmt am Smartphone, Tablet oder Laptop teil, gern beide Elternteile gemeinsam.'],
  ['Plan ohne Weg nach draußen', 'Euer schriftlicher Schlafplan kommt zu euch, ohne dass ihr mit Baby irgendwohin fahren müsst.'],
  ['Rückfragen per WhatsApp', 'In der gebuchten Begleitzeit stellt ihr eure Fragen genau dann, wenn sie im Alltag auftauchen.'],
];
const einschlafenFaq = [
  ['Ist es schlimm, wenn mein Baby nur an der Brust oder mit Fläschchen einschläft?', 'Nein. Gerade in den ersten Lebensmonaten ist das sehr verbreitet und kein Fehler. Es wird erst dann ein Thema, wenn es euch belastet oder ihr euch mehr Flexibilität wünscht. Dann lassen sich die Abläufe schrittweise verändern, ohne abzustillen.'],
  ['Wie lange darf das Einschlafen dauern?', 'Eine feste Norm gibt es nicht. Wenn das Einschlafen über Wochen regelmäßig sehr lange dauert und euch den Abend kostet, lohnt ein Blick auf Schlafenszeit, Tagschlaf und den Ablauf davor. Oft liegt der Schlüssel im Timing.'],
  ['Ab wann kann ein Kind selbstständig einschlafen?', 'Dafür gibt es kein festes Alter. Manche Kinder schlafen früh allein ein, andere brauchen lange Begleitung. Selbstständigeres Einschlafen kann ein Ziel sein, ist aber keine Pflicht und bei Neugeborenen kein sinnvolles Ziel.'],
];
const durchschlafenFaq = [
  ['Ab wann schlafen Babys durch?', 'Das ist sehr unterschiedlich. Viele Kinder wachen im ersten Lebensjahr und auch danach nachts noch auf. Das ist entwicklungsbedingt normal. Wichtiger als ein Stichtag ist, ob die Nächte für eure Familie tragbar sind.'],
  ['Muss ich abstillen, damit mein Kind durchschläft?', 'Nein. Stillen ist nicht automatisch der Grund für häufiges Aufwachen, und Abstillen ist keine Voraussetzung für eine Schlafberatung. Wenn nächtliches Stillen euch belastet, finden wir gemeinsam Wege, die zu euch passen.'],
  ['Kann eine Schlafberatung Durchschlafen garantieren?', 'Nein, und niemand sollte das versprechen. Schlaf entwickelt sich individuell. Was eine gute Beratung leisten kann: eure Situation verstehen, realistische Ziele setzen und euch bei der Umsetzung begleiten.'],
];

// ---------- Building blocks ----------
// Section intro: a real heading and one paragraph. No eyebrow labels.
const intro = (h, p = '', cls = '') => `<div class="intro${cls ? ` ${cls}` : ''}" data-reveal><h2>${h}</h2>${p ? `<p>${p}</p>` : ''}</div>`;
// Full-bleed photo/text halves.
const split = ({ img, pos = '50% 50%', body, reverse = false, tone = '' }) => `<section class="split${reverse ? ' reverse' : ''}${tone ? ` ${tone}` : ''}"><figure class="split-media" style="--pos:${pos}">${photo(img, { sizes: '(max-width: 900px) 100vw, 50vw' })}</figure><div class="split-body" data-reveal>${body}</div></section>`;
const checks = items => `<ul class="checks">${items.map(i => `<li>${check}<span>${i}</span></li>`).join('')}</ul>`;
const crosses = items => `<ul class="checks no">${items.map(i => `<li>${cross}<span>${i}</span></li>`).join('')}</ul>`;

const services = [
  ['schlafberatung-baby.html', 'Schlafberatung für Babys', 'Von den ersten Wochen bis zum ersten Geburtstag', 'hero', '50% 72%'],
  ['schlafberatung-kleinkind.html', 'Schlafberatung für Kleinkinder', 'Für Kinder von 1 bis 6 Jahren', 'troesten', '40% 40%'],
  ['online-schlafberatung.html', 'Online-Schlafberatung', 'Per Zoom oder Telefon, deutschlandweit', 'online', '50% 40%'],
  ['schlafberatung-wuerzburg.html', 'Schlafberatung in Würzburg', 'Persönliche Termine im Raum Würzburg', 'nacht', '50% 30%'],
];
const serviceTeasers = (exclude = '') => `<div class="teasers">${services.filter(([href]) => href !== exclude).map(([href, h, p, img, pos], i) => `<a class="teaser" href="${href}" data-reveal style="--i:${i};--pos:${pos}">${photo(img, { sizes: '(max-width: 760px) 100vw, (max-width: 1100px) 50vw, 25vw' })}<span class="teaser-body"><span class="teaser-title">${h}</span><span class="teaser-text">${p}</span><span class="teaser-more">Mehr erfahren${arrow}</span></span></a>`).join('')}</div>`;

const guides = [
  ['baby-einschlafen.html', 'Baby einschlafen: sanft begleiten statt jeden Abend kämpfen', 'Müdigkeitszeichen, ein tragfähiges Abendritual und kleine Schritte, wenn Einschlafen nur noch mit einer Person klappt.', 'einschlafen'],
  ['baby-durchschlafen.html', 'Baby schläft nicht durch: Was normal ist und was helfen kann', 'Warum nächtliches Aufwachen dazugehört, welche Gründe es haben kann und wann ihr ärztlich abklären solltet.', 'nacht'],
  ['schlafwissen.html', 'Sicherer Babyschlaf und verlässliche Quellen', 'Rückenlage, Schlafsack, eigenes Bett im Elternschlafzimmer: die wichtigsten Empfehlungen und wo ihr sie nachlest.', 'babybett'],
];
const guideCards = (exclude = '') => `<div class="articles">${guides.filter(([href]) => href !== exclude).map(([href, h, , img], i) => `<a class="article-teaser" href="${href}" data-reveal style="--i:${i}"><span class="article-img">${photo(img, { sizes: '(max-width: 760px) 100vw, 33vw' })}</span><h3>${h}</h3><span class="teaser-more">Weiterlesen${arrow}</span></a>`).join('')}</div>`;

const priceCards = () => `<div class="price-cards">${packages.map(p => `<article class="price-card${p.id === 'intensiv' ? ' featured' : ''}" id="${p.id}" data-reveal>${p.id === 'intensiv' ? '<p class="price-flag">Mit regelmäßigen Folgegesprächen</p>' : ''}<h2>${p.name}</h2><p class="price-duration">${p.duration}</p><p class="price-value">${p.price} €</p><p class="package-description">${p.text}</p>${checks(p.items)}${contact(`${p.name} anfragen`, `button${p.id === 'intensiv' ? '' : ' secondary'}`, `?paket=${p.name}#anfrage`)}<p class="tiny">Gesamtpreis, kein Abo</p></article>`).join('')}</div>`;

const priceTable = () => `<table class="price-table"><caption class="visually-hidden">Angebote und Gesamtpreise</caption><thead><tr><th scope="col">Angebot</th><th scope="col">Leistung</th><th scope="col">Preis</th></tr></thead><tbody><tr><th scope="row">Kennenlernen</th><td>20 Minuten per Zoom oder Telefon</td><td>kostenlos</td></tr>${offers.slice(1).map((o, i) => `<tr><th scope="row"><a href="preise.html#${o.id.toLowerCase()}">${o.name}</a></th><td>${['45 Minuten für ein konkretes Thema mit kurzer schriftlicher Zusammenfassung', '60 Minuten Beratung, schriftlicher Plan und 7 Tage Begleitung', '60 Minuten Beratung, Plan, 3 Folgegespräche und 3 Wochen Begleitung', '60 Minuten Beratung, Plan, 5 Folgegespräche und 6 Wochen Begleitung'][i]}</td><td>${o.price} €</td></tr>`).join('')}</tbody></table>`;

const process = (list = steps) => `<ol class="steps">${list.map(([h, p], i) => `<li data-reveal style="--i:${i}"><span class="step-no" aria-hidden="true">${i + 1}</span><div><h3>${h}</h3><p>${p}</p></div></li>`).join('')}</ol>`;

const promiseLists = `<div class="promise"><div><h3>Darauf könnt ihr euch verlassen</h3>${checks(['Ein Plan, der zu Alter, Entwicklung und eurem Alltag passt', 'Begleitung bei der Umsetzung, nicht nur ein PDF', 'Ehrliche, verständliche Worte statt Fachchinesisch', 'Höchstens drei Familien gleichzeitig, damit Zeit für euch bleibt'])}</div><div><h3>Was es bei mir nicht gibt</h3>${crosses(['Kein kontrolliertes Schreienlassen', 'Keine Durchschlafgarantie in X Nächten', 'Kein pauschales Abstillen oder Umziehen ins Kinderzimmer', 'Keine Schuldzuweisungen, denn Nähe ist kein Fehler'])}</div></div>`;

const certificate = (cls = '', full = true) => `<figure class="certificate ${cls}" data-reveal><a href="assets/zertifikat-anna-lena-korb.pdf" aria-label="Abschlusszertifikat als PDF öffnen"><img src="assets/zertifikat-anna-lena-korb.png" alt="Abschlusszertifikat: Anna-Lena Korb hat die Ausbildung zur Babyschlafberaterin am 11.03.2026 erfolgreich absolviert. Ausbildungsleitung Melanie Heift-Budde." width="1200" height="849" loading="lazy"></a><figcaption>${full ? 'Abschlusszertifikat vom 11. März 2026. Laut Zertifikat ist die Ausbildung vom Gesundheitsamt der Stadt Aachen zertifiziert. ' : 'Mein Abschluss als Babyschlafberaterin, März 2026. '}<a href="assets/zertifikat-anna-lena-korb.pdf">Zertifikat als PDF ansehen</a></figcaption></figure>`;

const safeSleep = `<p>Bei Säuglingen hat ein sicherer Schlafplatz immer Vorrang. Das Bundesinstitut für Öffentliche Gesundheit (BIÖG) empfiehlt unter anderem die Rückenlage, einen Schlafsack statt Decke, eine eher feste Matratze ohne Kissen, Nestchen oder Felle, ein eigenes Bett im Elternschlafzimmer, eine rauchfreie Umgebung und keine zu warme Kleidung. Die vollständigen Empfehlungen: <a href="https://www.kindergesundheit-info.de/themen/schlafen/0-12-monate/schlafumgebung/">BIÖG: Die richtige Schlafumgebung für das Baby</a>.</p>`;

function article({ minutes, toc, body, related, image, note }) {
  return `<div class="wrap article-layout"><aside class="article-aside"><div class="byline"><img src="assets/logo.png" alt="Logo der Babyschlafberatung Anna-Lena Korb" width="44" height="44" loading="lazy"><div><span class="byline-name">Anna-Lena Korb</span><span>Zertifizierte Babyschlafberaterin</span></div></div><p class="meta">Aktualisiert am <time datetime="${updated}">9. Oktober 2026</time><br>Lesezeit etwa ${minutes} Minuten</p><nav class="toc" aria-label="Inhalt dieses Artikels"><p>Inhalt</p><ol>${toc.map(([id, t]) => `<li><a href="#${id}">${t}</a></li>`).join('')}</ol></nav></aside><article class="prose article-body">${image ? `<figure class="article-figure">${photo(image, { sizes: '(max-width: 760px) 100vw, 720px' })}</figure>` : ''}${body}<aside class="callout"><p>${note}</p></aside></article></div><section class="section soft"><div class="wrap">${intro('Mehr aus dem Ratgeber')}${guideCards(related)}</div></section>`;
}

const allFaq = [...faq, ...generalExtraFaq];

export const pages = {
  'index.html': {
    title: 'Babyschlafberatung online & deutschlandweit | Anna-Lena Korb', label: 'Startseite',
    description: 'Babyschlafberatung ohne Schreienlassen: persönliche Begleitung per Zoom und Telefon in ganz Deutschland. Kostenloses Kennenlernen in 20 Minuten.',
    faq: homeFaq,
    content: `<section class="hero"><div class="hero-media"><picture><source media="(max-width: 760px)" srcset="assets/hero-640.webp 640w, assets/hero-960.webp 960w, assets/hero-1440.webp 1440w" sizes="100vw" width="960" height="1440">${photo('einschlafen', { priority: true, sizes: '100vw' })}</picture></div><div class="wrap hero-inner"><p class="hero-title">Ruhigere Nächte.<br>Mit Nähe und einem klaren Plan.</p><p class="hero-text">Persönliche Schlafberatung für Familien mit Babys und Kleinkindern. Ohne Schreienlassen, online in ganz Deutschland.</p><div class="actions">${contact('Kostenloses Kennenlernen', 'button light')}<a class="button outline-light" href="schlafberatung.html">Zur Schlafberatung${arrow}</a></div></div></section>
    <section class="section wrap welcome"><div class="welcome-text" data-reveal><h1>Babyschlafberatung online in ganz Deutschland – mit Nähe statt Schreienlassen</h1><p class="lead">Wenn das Einschlafen den ganzen Abend bestimmt und die Nächte zerstückelt sind, braucht ihr nicht noch mehr gut gemeinte Tipps. Ihr braucht jemanden, der zuhört, ehrlich hinschaut und euch Schritt für Schritt begleitet.</p><p>Ich bin <strong>Anna-Lena Korb, zertifizierte Babyschlafberaterin</strong> und seit 2010 Tagesmutter. Ich begleite Familien mit Kindern von 0 bis 6 Jahren: bei <a href="baby-einschlafen.html">langen Einschlafabenden</a>, <a href="baby-durchschlafen.html">häufigem nächtlichen Aufwachen</a>, beim Tagschlaf oder wenn das Einschlafen nur mit einer Person klappt.</p><p>Die Beratung läuft deutschlandweit <a href="online-schlafberatung.html">online per Zoom oder Telefon</a>, egal ob ihr in Hamburg, Berlin, Köln, München oder auf dem Land wohnt. Im <a href="schlafberatung-wuerzburg.html">Raum Würzburg</a> sind auch persönliche Termine möglich. Das erste Gespräch ist <strong>kostenlos und unverbindlich</strong>.</p><div class="actions">${contact()}${link('ueber-mich.html', 'Mehr über mich')}</div></div>${certificate('', false)}</section>
    <section class="section soft"><div class="wrap">${intro('Meine Schlafberatung im Überblick', 'Jedes Alter braucht etwas anderes. Wählt aus, was zu eurer Familie passt.')}${serviceTeasers()}</div></section>
    ${split({ img: 'nacht', pos: '50% 35%', body: `<h2>Wenn Schlaf alles andere bestimmt</h2><p class="lead">Ihr seid müde. Und vielleicht auch müde von widersprüchlichen Ratschlägen.</p><p>Der Abend zieht sich über Stunden. Die Nächte sind zerstückelt. Einschlafen klappt nur mit Mama oder nur mit Papa. Oder Kita-Start, Tagschlaf und ein neuer Alltag bringen alles durcheinander.</p><p>Wir schauen gemeinsam auf eure Situation, ohne Schuldzuweisungen und ohne ein Programm für alle. Bei Neugeborenen stehen Orientierung und sichere Schlafbedingungen im Mittelpunkt.</p><p>Was ihr bei mir bekommt und was es bei mir bewusst nicht gibt, lest ihr auf der Seite zur Schlafberatung.</p>${link('schlafberatung.html', 'Meine Arbeitsweise')}` })}
    <section class="section wrap">${intro('So läuft die Schlafberatung ab', 'Ein persönlicher Weg statt einer Sammlung weiterer Schlaftipps. Ihr wisst jederzeit, was als Nächstes kommt.', 'row')}${process(homeSteps)}<div class="actions center">${link('ablauf.html', 'Ablauf im Detail')}</div></section>
    ${split({ img: 'online', pos: '50% 30%', reverse: true, tone: 'dark', body: `<h2>Beratung bei euch zu Hause, wo immer ihr wohnt</h2><p>Die Gespräche laufen per Zoom oder Telefon. Ihr bleibt in eurer gewohnten Umgebung, beide Elternteile können dabei sein, auch von zwei Orten aus. Kein Packen, keine Anfahrt mit müdem Baby.</p><p>Zwischen den Terminen könnt ihr eure Fragen im gebuchten Zeitraum per WhatsApp stellen. Ich antworte in der Regel innerhalb von 24 Stunden.</p><div class="actions">${contact('Kennenlernen anfragen', 'button light')}<a class="button outline-light" href="online-schlafberatung.html">Online-Beratung${arrow}</a></div>` })}
    <section class="section wrap prices-home"><div data-reveal><h2>Klare Gesamtpreise, ohne Abo</h2><p>Das Kennenlernen ist kostenlos. Danach entscheidet ihr euch in Ruhe für eine einzelne Sprechstunde oder eine Begleitung über mehrere Wochen. Ohne automatische Verlängerung.</p>${link('preise.html', 'Alle Leistungen und Pakete')}</div><div data-reveal style="--i:1">${priceTable()}</div></section>
    <section class="section soft about-home"><div class="wrap about-home-inner">${portrait('Nähe ist kein Fehler. Ihr dürft euch trotzdem ruhigere Abende wünschen.', 'zertifizierte Babyschlafberaterin')}<div data-reveal><h2>Ich bin Anna-Lena, herzlich, ehrlich und nah am Alltag</h2><p>Seit 2010 begleite ich als qualifizierte Kindertagespflegeperson Babys und Kleinkinder. Rund 100 Kinder habe ich in dieser Zeit beim Ankommen, Wachsen und Zur-Ruhe-Kommen erlebt. Als Mutter kenne ich lange Einschlafabende auch selbst.</p><p>Heute verbinde ich diese Erfahrung mit meiner Ausbildung zur Babyschlafberaterin. Ihr bekommt von mir klare Worte, einen konkreten Plan und Unterstützung bei der Umsetzung.</p><div class="actions">${link('ueber-mich.html', 'Meine Geschichte')}${link('ueber-mich.html#qualifikationen', 'Qualifikationen')}</div></div></div></section>
    <section class="section wrap">${intro('Ratgeber für müde Eltern', 'Eigenständig geschrieben, mit Verweisen auf verlässliche Quellen. Kein Ersatz für eine Beratung, aber ein guter Anfang.', 'row')}${guideCards()}</section>
    <section class="section wrap faq-layout"><div data-reveal><h2>Häufige Fragen zur Schlafberatung</h2><p>Unsicherheit gehört dazu. Hier findet ihr erste Antworten.</p>${link('fragen.html', 'Alle Fragen und Antworten')}</div>${questions(homeFaq)}</section>${closing()}`,
  },
  'schlafberatung.html': {
    title: 'Schlafberatung für Babys & Kleinkinder | Anna-Lena Korb', label: 'Schlafberatung',
    description: 'Schlafberatung für Kinder von 0 bis 6 Jahren: individueller Plan und Begleitung ohne Schreienlassen. Online deutschlandweit, vor Ort in Würzburg.',
    service: { name: 'Schlafberatung für Babys und Kleinkinder', offers: offers.slice(1) },
    content: `${pageHead('Schlafberatung für Babys und Kleinkinder', 'Euer Ziel muss nicht „perfekt durchschlafen“ heißen. Es darf erst einmal heißen: weniger Belastung, mehr Orientierung und ein Abend, der sich wieder bewältigen lässt.', 'troesten', '50% 35%')}
    <section class="section wrap content-grid"><div class="prose" data-reveal><h2>Was soll für euch leichter werden?</h2><p>Vielleicht möchtest du nicht mehr jeden Abend stundenlang begleiten. Vielleicht soll auch ein anderer Elternteil beim Einschlafen helfen können. Oder ihr braucht einen Blick von außen auf euren Tagesablauf.</p><p>Wir vereinbaren ein Ziel, das zu Alter, Entwicklung und Bedürfnissen eures Kindes passt. <strong>Selbstständigeres Einschlafen kann ein Ziel sein</strong>, ist aber keine Pflicht für jedes Kind und nicht das Ziel der Neugeborenenberatung.</p><p>Ich arbeite <strong>ohne kontrolliertes Schreienlassen</strong>. Ihr bleibt ansprechbar, wenn euer Kind euch braucht. Konsequent sein heißt bei mir: freundlich bei dem bleiben, was wir gemeinsam vereinbart haben.</p></div><aside class="aside-box" data-reveal style="--i:1"><h3>Auf einen Blick</h3><dl><div><dt>Alter</dt><dd>0 bis 6 Jahre, ältere Kinder nach Absprache</dd></div><div><dt>Ort</dt><dd>Online deutschlandweit, persönlich im Raum Würzburg</dd></div><div><dt>Erstgespräch</dt><dd>20 Minuten, kostenlos</dd></div><div><dt>Kosten</dt><dd>ab 89 €, Gesamtpreise ohne Abo</dd></div></dl>${contact('Termin anfragen', 'button full')}</aside></section>
    <section class="section soft"><div class="wrap">${intro('Für welches Alter und welche Situation?', 'Wählt die Seite, die zu eurer Familie passt. Dort findet ihr, worauf es in diesem Alter ankommt.')}${serviceTeasers()}</div></section>
    <section class="section wrap age-table"><div data-reveal><h2>Jedes Alter braucht etwas anderes</h2></div><dl data-reveal style="--i:1"><div><dt>0–3 Monate · Neugeborene</dt><dd>Orientierung, sichere Schlafbedingungen und Entlastung für euch. Kein Schlaftraining. <a href="schlafberatung-baby.html">Schlafberatung für Babys</a></dd></div><div><dt>4–12 Monate · Babys</dt><dd>Tagesrhythmus, Einschlafbegleitung und häufiges nächtliches Aufwachen. <a href="schlafberatung-baby.html">Schlafberatung für Babys</a></dd></div><div><dt>1–3 Jahre · Kleinkinder</dt><dd>Einschlafen nur mit einer Person, Tagschlaf, Kita-Start und neue Abläufe. <a href="schlafberatung-kleinkind.html">Schlafberatung für Kleinkinder</a></dd></div><div><dt>3–6 Jahre · Kindergartenkinder</dt><dd>Abendroutinen, Ängste beim Einschlafen und nächtliches Wandern ins Elternbett. <a href="schlafberatung-kleinkind.html">Schlafberatung für Kleinkinder</a></dd></div></dl></section>
    ${split({ img: 'einschlafen', body: `<h2>Eure Geschichte gehört dazu</h2><p>Der Fragebogen beschäftigt sich mit eurem Alltag, Schlafgewohnheiten und euren Wünschen. Schwangerschaft, Geburt und die erste Zeit mit eurem Kind können dabei ebenfalls angesprochen werden, soweit sie für eure Beratung relevant sind und ihr darüber sprechen möchtet.</p><p>Aus einer Geburtsgeschichte allein lässt sich keine Ursache für ein Schlafproblem ableiten. Die Schlafberatung stellt keine Diagnosen und ersetzt keine medizinische oder therapeutische Behandlung.</p>${link('ablauf.html', 'So läuft die Beratung ab')}` })}
    <section class="section wrap">${intro('Klar in der Sache, warm im Umgang', 'Ihr sollt vorher wissen, worauf ihr euch einlasst.')}${promiseLists}</section>${closing()}`,
  },
  'schlafberatung-baby.html': {
    title: 'Schlafberatung für Babys (0–12 Monate) | Anna-Lena Korb', label: 'Für Babys', parent: ['schlafberatung.html', 'Schlafberatung'],
    description: 'Babyschlafberatung im ersten Lebensjahr: Orientierung für Neugeborene, Einschlafbegleitung und nächtliches Aufwachen. Sanft und ohne Schreienlassen.',
    faq: babyFaq,
    service: { name: 'Schlafberatung für Babys', offers: offers.slice(1) },
    content: `${pageHead('Schlafberatung für Babys im ersten Lebensjahr', 'Im ersten Jahr verändert sich der Schlaf fast jeden Monat. Ich helfe euch, euer Baby besser zu verstehen, sicher zu schlafen und Abende zu finden, die sich wieder bewältigen lassen.', 'einschlafen', '50% 45%')}
    <section class="section wrap content-grid"><div class="prose" data-reveal><h2>Neugeborene: Orientierung statt Schlaftraining</h2><p>In den ersten drei Monaten geht es nicht darum, dass euer Baby allein einschläft oder durchschläft. Es geht um <strong>Orientierung, sichere Schlafbedingungen und Entlastung</strong> für euch als Eltern.</p><p>Wir schauen auf Müdigkeitszeichen, auf den Tag und auf die Frage, wie ihr euch die Nächte aufteilen könnt. Nähe beim Einschlafen, Stillen oder Fläschchen sind in diesem Alter kein Fehler.</p><h2>Babys von 4 bis 12 Monaten</h2><p>Jetzt entstehen erste Rhythmen. Häufige Themen in der Beratung sind:</p>${checks(['Ein Tagesrhythmus, der zum Alter passt', 'Einschlafen, das jeden Abend sehr lange dauert', 'Häufiges nächtliches Aufwachen', 'Einschlafen nur an der Brust, im Arm oder mit einer Person', 'Kurze Tagschläfe und übermüdete Abende'])}<p>Wir verändern immer nur so viel, wie euer Baby und ihr gut mitgehen könnt. Euer Kind wird dabei getröstet, wenn es euch braucht.</p><h2>Sicherer Schlaf hat Vorrang</h2>${safeSleep}</div><aside class="aside-box" data-reveal style="--i:1"><h3>Passend für euch</h3><p>Für die meisten Familien mit Babys passt das Paket <a href="preise.html#basis">Basis</a> oder <a href="preise.html#intensiv">Intensiv</a>. Für eine einzelne Frage gibt es die <a href="preise.html#sprechstunde">Schlafsprechstunde</a>.</p>${contact('Kennenlernen anfragen', 'button full')}<p class="small">20 Minuten, kostenlos und unverbindlich</p></aside></section>
    <section class="section soft"><div class="wrap">${intro('Zum Weiterlesen')}${guideCards()}</div></section>
    <section class="section wrap faq-layout"><div data-reveal><h2>Häufige Fragen zum Babyschlaf</h2>${link('fragen.html', 'Alle Fragen')}</div>${questions(babyFaq)}</section>${closing()}`,
  },
  'schlafberatung-kleinkind.html': {
    title: 'Schlafberatung für Kleinkinder (1–6 Jahre) | Anna-Lena Korb', label: 'Für Kleinkinder', parent: ['schlafberatung.html', 'Schlafberatung'],
    description: 'Schlafberatung für Kinder von 1 bis 6 Jahren: Einschlafen nur mit Mama, Tagschlaf, Kita-Start und Wandern ins Elternbett. Ohne Schreienlassen.',
    faq: toddlerFaq,
    service: { name: 'Schlafberatung für Kleinkinder', offers: offers.slice(1) },
    content: `${pageHead('Schlafberatung für Kleinkinder von 1 bis 6 Jahren', 'Kleinkinder wollen mitreden, haben Ideen, Ängste und einen eigenen Kopf. Mit einem klaren Plan und viel Verständnis findet ihr wieder ruhigere Abende.', 'troesten', '40% 35%')}
    <section class="section wrap content-grid"><div class="prose" data-reveal><h2>Kleinkinder von 1 bis 3 Jahren</h2><p>In diesem Alter verändert sich viel: Laufen, Sprechen, Kita-Start, der Abschied vom Vormittagsschlaf. Häufige Anliegen sind:</p>${checks(['Einschlafen klappt nur mit Mama oder nur mit Papa', 'Der Tagschlaf passt nicht mehr zum Alltag', 'Kita-Start und neue Abläufe bringen den Schlaf durcheinander', 'Häufiges Aufwachen und lange Wachphasen in der Nacht'])}<p>Hilfreich ist oft ein schrittweiser Wechsel: Der andere Elternteil übernimmt zuerst Teile des Rituals, später ist er beim Einschlafen dabei und schließlich allein zuständig. Dass ein Kind die Veränderung erst einmal nicht gut findet und das zeigt, ist normal. Es darf dabei getröstet werden.</p><h2>Kindergartenkinder von 3 bis 6 Jahren</h2><p>Ältere Kinder können schon gut mitmachen, wenn sie verstehen, was sich ändert. Typische Themen sind:</p>${checks(['Abendroutinen, die jeden Abend länger werden', 'Ängste beim Einschlafen', 'Nächtliches Wandern ins Elternbett', 'Unterschiedliche Bedürfnisse bei Geschwistern'])}<p>Wir entwickeln einen Plan, den ihr wirklich umsetzen könnt, und der euer Kind ernst nimmt. Ohne Strafen, ohne Schreienlassen und ohne Schuldzuweisungen.</p></div><aside class="aside-box" data-reveal style="--i:1"><h3>Passend für euch</h3><p>Bei Kleinkindern lohnt sich meist eine Begleitung über mehrere Wochen, zum Beispiel <a href="preise.html#intensiv">Intensiv</a> mit drei Folgegesprächen.</p>${contact('Kennenlernen anfragen', 'button full')}<p class="small">20 Minuten, kostenlos und unverbindlich</p></aside></section>
    ${split({ img: 'online', pos: '50% 30%', tone: 'soft', body: `<h2>Beide Eltern an einem Tisch</h2><p>Gerade wenn sich das Einschlafen künftig besser aufteilen soll, ist es hilfreich, wenn beide Elternteile beim Gespräch dabei sind. Online geht das auch von zwei Orten aus.</p>${link('online-schlafberatung.html', 'So funktioniert die Online-Beratung')}` })}
    <section class="section wrap faq-layout"><div data-reveal><h2>Häufige Fragen zum Kleinkindschlaf</h2>${link('fragen.html', 'Alle Fragen')}</div>${questions(toddlerFaq)}</section>${closing()}`,
  },
  'online-schlafberatung.html': {
    title: 'Babyschlafberatung online per Zoom | Anna-Lena Korb', label: 'Online-Beratung', parent: ['schlafberatung.html', 'Schlafberatung'],
    description: 'Online-Schlafberatung per Zoom oder Telefon, egal wo in Deutschland ihr wohnt: für Babys und Kleinkinder, ohne Schreienlassen.',
    faq: onlineFaq,
    service: { name: 'Babyschlafberatung online', offers: offers.slice(1) },
    content: `${pageHead('Babyschlafberatung online, wo immer ihr wohnt', 'Ihr müsst nicht in meiner Nähe wohnen, um von mir begleitet zu werden. Kennenlernen, Beratung und Folgegespräche laufen per Zoom oder Telefon, Rückfragen in der Begleitzeit per WhatsApp.', 'online', '50% 30%')}
    <section class="section wrap content-grid"><div class="prose" data-reveal><h2>Schlafberatung findet im Alltag statt</h2><p>Schlaf passiert zu Hause. Deshalb funktioniert Schlafberatung online besonders gut: Ihr sprecht in eurer gewohnten Umgebung, und wenn ihr möchtet, zeigt ihr mir Schlafplatz und Abendablauf kurz per Kamera.</p>${checks(['<strong>Bei euch zu Hause:</strong> keine Anfahrt, kein Termin außer Haus mit müdem Baby', '<strong>Beide Eltern dabei:</strong> auch von zwei Orten aus', '<strong>Ohne Technikhürde:</strong> Smartphone, Tablet oder Laptop genügt, ein Zoom-Konto braucht ihr nicht', '<strong>Begleitung im Alltag:</strong> Rückfragen per WhatsApp, Antwort in der Regel innerhalb von 24 Stunden'])}<h2>Für Familien in ganz Deutschland</h2><p>Die Beratung ist deutschlandweit gleich. Familien aus allen Bundesländern können die Beratung vollständig online nutzen, ob in Hamburg, Berlin, Köln, Frankfurt, Stuttgart, München oder auf dem Land. Gesprächszeiten sind Montag bis Freitag von 17 bis 19 Uhr und Samstag von 9 bis 13 Uhr.</p><p>Ich lebe in Eisingen bei Würzburg. Wer in der Nähe wohnt, kann auch einen <a href="schlafberatung-wuerzburg.html">persönlichen Termin im Raum Würzburg</a> vereinbaren.</p></div><aside class="aside-box" data-reveal style="--i:1"><h3>Das braucht ihr</h3><p>Ein Gerät mit Kamera oder ein Telefon, etwa eine Stunde Ruhe für das Erstgespräch und, bei den Begleitungspaketen, einen ausgefüllten Fragebogen.</p>${contact('Kennenlernen anfragen', 'button full')}</aside></section>
    <section class="section soft"><div class="wrap">${intro('So läuft die Online-Beratung', 'Von der ersten Nachricht bis zur Begleitung.', 'row')}${process(onlineSteps)}</div></section>
    <section class="section wrap faq-layout" id="fragen"><div data-reveal><h2>Fragen zur Online-Beratung</h2>${link('fragen.html', 'Alle Fragen')}</div>${questions(onlineFaq)}</section>${closing()}`,
  },
  'schlafberatung-wuerzburg.html': {
    title: 'Schlafberatung Würzburg: vor Ort & online | Anna-Lena Korb', label: 'Vor Ort in Würzburg', parent: ['schlafberatung.html', 'Schlafberatung'],
    description: 'Babyschlafberatung in Würzburg und Umgebung: persönliche Termine nach Absprache, ohne Anfahrtskosten. Babyschlafberaterin aus Eisingen.',
    service: { name: 'Babyschlafberatung in Würzburg', offers: offers.slice(1) },
    content: `${pageHead('Schlafberatung in Würzburg und Umgebung', 'Ich lebe in Eisingen bei Würzburg. Familien aus der Region kann ich nach Absprache auch persönlich begleiten, ohne zusätzliche Anfahrtskosten.', 'nacht', '50% 30%')}
    <section class="section wrap content-grid"><div class="prose" data-reveal><h2>Persönlich vor Ort, wenn ihr das möchtet</h2><p>Innerhalb von Würzburg und im Umkreis von etwa 10 bis 15 Kilometern sind <strong>persönliche Termine nach Absprache</strong> möglich. Eine zusätzliche Anfahrtspauschale gibt es dafür nicht. Eine offene Sprechstunde vor Ort biete ich nicht an.</p><p>Viele Familien aus der Region entscheiden sich trotzdem für die <a href="online-schlafberatung.html">Online-Beratung</a>: Sie ist zeitlich flexibler, und beide Elternteile können leichter dabei sein. Ihr könnt beides auch kombinieren, zum Beispiel ein persönliches Erstgespräch und Folgegespräche per Zoom.</p><h2>Seit 2010 mit Kindern aus der Region</h2><p>Seit 2010 bin ich Tagesmutter in meiner Kindertagespflege Kinderkörbchen in Eisingen und habe rund 100 Kinder begleitet. Seit 2026 bin ich zertifizierte Babyschlafberaterin. Ich kenne den Alltag von Familien hier, mit Kita-Start, Arbeit und langen Abenden.</p><p>Die Beratung, die Preise und der Ablauf sind dieselben wie online. Mehr dazu findet ihr unter <a href="ablauf.html">Ablauf</a> und <a href="preise.html">Kosten</a>.</p></div><aside class="aside-box" data-reveal style="--i:1"><h3>Kontakt</h3><address>Anna-Lena Korb<br>Babyschlafberatung<br>Müllersweg 15<br>97249 Eisingen</address><p><a href="tel:${site.telephone}">${site.telephoneDisplay}</a><br><a href="mailto:${site.email}">${site.email}</a></p><p class="small">Termine nur nach Vereinbarung. Gesprächszeiten Mo–Fr 17–19 Uhr, Sa 9–13 Uhr.</p>${contact('Termin anfragen', 'button full')}</aside></section>
    <section class="section soft"><div class="wrap content-grid"><div class="prose" data-reveal><h2>Für Familien in Würzburg und Umgebung</h2><p>Persönliche Termine biete ich in Würzburg und Umgebung an, im Umkreis von etwa 10 bis 15 Kilometern. Das betrifft zum Beispiel die Würzburger Stadtteile von der Zellerau bis Heidingsfeld, Lengfeld und Versbach, aber auch Orte wie Eisingen, Höchberg, Waldbüttelbrunn, Kist, Gerbrunn, Veitshöchheim, Zell am Main oder Randersacker. Wohnt ihr weiter entfernt, ist die Online-Beratung die einfachere Lösung.</p><h2>Wo der persönliche Termin stattfindet</h2><p>Wo wir uns treffen, stimmen wir gemeinsam ab. Wichtig ist, dass ihr in Ruhe erzählen könnt und euer Kind gut versorgt ist. Folgegespräche können wir auch per Zoom oder Telefon führen, wenn das im Alltag leichter für euch ist.</p><h2>Typische Anliegen von Familien aus der Region</h2><p>Die Themen sind dieselben wie überall: lange Einschlafabende, häufiges Aufwachen, ein Tagschlaf, der nicht mehr passt, oder der Start in Krippe, Kita und Tagespflege. Durch meine Arbeit im Kinderkörbchen kenne ich viele dieser Übergänge aus dem Alltag von Familien hier.</p></div><aside class="aside-box" data-reveal style="--i:1"><h3>Lieber erst online?</h3><p>Auch Familien aus Würzburg starten oft mit dem kostenlosen Kennenlernen per Zoom oder Telefon. Danach entscheidet ihr, ob ihr euch persönlich treffen möchtet.</p>${link('online-schlafberatung.html', 'Zur Online-Beratung')}</aside></div></section>
    <section class="section"><div class="wrap">${intro('Weitere Schwerpunkte')}${serviceTeasers('schlafberatung-wuerzburg.html')}</div></section>${closing()}`,
  },
  'ablauf.html': {
    title: 'Ablauf der Babyschlafberatung | Anna-Lena Korb', label: 'Ablauf',
    description: 'So läuft die Schlafberatung ab: kostenloses Kennenlernen, Fragebogen, persönliches Gespräch, schriftlicher Plan und Begleitung per WhatsApp.',
    content: `${pageHead('So läuft die Schlafberatung ab', 'Ein nachvollziehbarer Ablauf, kein Rätselraten. Die Schlafsprechstunde beantwortet eine einzelne Frage, bei den Begleitungspaketen gehen wir ausführlicher vor.')}
    <section class="section wrap">${intro('Die vier Schritte im Überblick', 'So läuft die Beratung bei mir ab, vom ersten Gespräch bis zur Begleitung im Alltag.', 'row')}${process()}</section>
    ${split({ img: 'troesten', pos: '40% 40%', tone: 'soft', body: `<h2>Was ihr vor dem Gespräch bekommt</h2><p>Bei den Paketen Basis, Intensiv und Premium erhaltet ihr vorab einen <strong>ausführlichen Fragebogen</strong>. Bei Intensiv und Premium kommt ein <strong>Schlafprotokoll</strong> dazu, in dem ihr einige Tage lang Schlafzeiten, Aufwachen und Abläufe notiert.</p><p>Vertrauliche Informationen gehören nicht in die öffentliche Terminanfrage. Den passenden Rahmen für ausführliche Angaben stimmen wir persönlich ab.</p>` })}
    <section class="section wrap content-grid"><div class="prose" data-reveal><h2>Euer schriftlicher Plan</h2><p>Innerhalb von 24 Stunden nach dem Beratungsgespräch bekommt ihr euren schriftlichen Schlafplan, sofern die vereinbarten Unterlagen vollständig vorliegen. Er beschreibt konkrete nächste Schritte, die zu Alter, Entwicklung und eurem Alltag passen.</p><h2>Begleitung zwischen den Gesprächen</h2><p>In den Begleitungspaketen könnt ihr Fragen per WhatsApp stellen. Ich antworte in der Regel innerhalb von 24 Stunden; sonntags und an Feiertagen am nächsten Beratungstag. Die Begleitung ist kein Live-Chat und keine Rund-um-die-Uhr-Betreuung.</p><h2>Welches Angebot zu euch passt</h2><p>Die Schlafsprechstunde passt, wenn ihr eine einzelne, klar umrissene Frage habt: 45 Minuten und eine kurze schriftliche Zusammenfassung. Mit Basis bekommt ihr einen vollständigen Plan und sieben Tage Begleitung. Intensiv und Premium sind für Familien gedacht, die neue Routinen über drei oder sechs Wochen mit regelmäßigen Folgegesprächen ausprobieren möchten. Wenn ihr unsicher seid, klären wir das im Kennenlernen.</p><h2>Nach der Begleitung</h2><p>Am Ende der gebuchten Zeit endet die Begleitung ohne automatische Verlängerung. Euer schriftlicher Plan bleibt bei euch, sodass ihr auch später darauf zurückgreifen könnt. Wenn neue Themen auftauchen, etwa durch einen Entwicklungsschritt oder den Kita-Start, könnt ihr jederzeit wieder anfragen.</p><h2>Gesprächszeiten</h2><p>Montag bis Freitag 17–19 Uhr und Samstag 9–13 Uhr, per Zoom oder Telefon in ganz Deutschland. Im Raum Würzburg auch persönlich nach Absprache.</p></div><aside class="aside-box" data-reveal style="--i:1"><h3>Der erste Schritt</h3><p>Fragt einen Termin für das kostenlose Kennenlernen an. Mindestens sieben Tage Vorlauf, 20 Minuten, ohne Zahlungspflicht.</p>${contact('Termin anfragen', 'button full')}${link('preise.html', 'Pakete vergleichen')}</aside></section>${closing()}`,
  },
  'preise.html': {
    title: 'Babyschlafberatung Kosten & Preise: ab 89 € | Anna-Lena Korb', label: 'Kosten',
    description: 'Gesamtpreise ohne Abo: Sprechstunde 89 €, Basis 149 €, Intensiv 299 €, Premium 479 €. Mit Schlafplan, Begleitung und kostenlosem Kennenlernen.',
    service: { name: 'Babyschlafberatung', offers: offers.slice(1) },
    content: `${pageHead('Kosten und Pakete der Schlafberatung', 'Ein konkretes Thema oder Unterstützung über mehrere Wochen: Ihr entscheidet nach dem kostenlosen Kennenlernen in Ruhe. Alle genannten Beträge sind Gesamtpreise.')}
    <section class="section wrap"><div class="notice" data-reveal><div><h2>Das Kennenlernen ist kostenlos</h2><p>20 Minuten, in denen wir eure Situation besprechen und schauen, ob mein Angebot passt. Keine Zahlungspflicht, keine Paketpflicht. Die drei Pakete unterscheiden sich vor allem darin, wie lange ich euch begleite.</p></div>${contact()}</div>${priceCards()}<article class="single-offer" id="sprechstunde" data-reveal><div><h2>Schlafsprechstunde</h2><p>Lieber erst eine konkrete Frage klären? 45 Minuten per Zoom, ein klar abgegrenztes Thema und eine kurze schriftliche Zusammenfassung. Ohne vollständigen Schlafplan und ohne anschließende WhatsApp-Begleitung.</p></div><div class="single-price"><p class="price-value">89 €</p>${contact('Sprechstunde anfragen', 'button secondary', '?paket=Sprechstunde#anfrage')}</div></article></section>
    <section class="section soft"><div class="wrap content-grid"><div class="prose" data-reveal><h2>Klare Leistungen, klare Grenzen</h2><h3>Persönlich, aber nicht rund um die Uhr</h3><p>WhatsApp-Begleitung gilt nur im gebuchten Zeitraum. Antworten in der Regel innerhalb von 24 Stunden; sonntags und an Feiertagen am nächsten Beratungstag. Keine Live- oder Notfallbetreuung.</p><h3>Ein Plan, der auf eure Angaben aufbaut</h3><p>Der schriftliche Schlafplan folgt innerhalb von 24 Stunden nach dem Beratungsgespräch, sofern die vereinbarten Unterlagen vollständig vorliegen. Die Begleitdauer startet zum gemeinsam vereinbarten Termin.</p><h3>Keine automatische Verlängerung</h3><p>Vor einer kostenpflichtigen Vereinbarung erhaltet ihr Leistungsumfang, Preis und Vertragsinformationen. Zahlungsweise, eine mögliche Ratenzahlung und Terminänderungen werden persönlich vereinbart. Die Anfrage auf dieser Seite ist noch kein Vertrag.</p><p>Ich begleite höchstens drei Familien gleichzeitig. Ob gerade ein Platz frei ist, klären wir persönlich. Es gelten die <a href="agb.html">AGB</a> und das <a href="widerruf.html">Widerrufsrecht</a>.</p></div><aside class="aside-box" data-reveal style="--i:1"><h3>Unsicher, was passt?</h3><p>Genau dafür ist das Kennenlernen da. Wir finden gemeinsam heraus, ob eine Sprechstunde reicht oder eine Begleitung sinnvoll ist.</p>${contact('Kennenlernen anfragen', 'button full')}</aside></div></section>${closing()}`,
  },
  'ueber-mich.html': {
    title: 'Über Anna-Lena Korb – Babyschlafberaterin & Tagesmutter', label: 'Über mich',
    description: 'Zertifizierte Babyschlafberaterin aus Eisingen bei Würzburg: Kindertagespflege seit 2010, rund 100 betreute Kinder, Montessori-Diplom und Kinderyoga.',
    content: `${pageHead('Über mich: Anna-Lena Korb', 'Zertifizierte Babyschlafberaterin, qualifizierte Kindertagespflegeperson und Mama seit 2005. Zu Hause in Eisingen bei Würzburg, als Beraterin online für Familien in ganz Deutschland da.')}
    <section class="section wrap about-home-inner">${portrait()}<div class="prose" data-reveal><h2>Ich kenne Kinder nicht nur aus Lehrbüchern</h2><p>Seit 2010 bin ich Tagesmutter in meiner Kindertagespflege, dem <a href="${site.childcareUrl}" target="_blank" rel="noopener">Kinderkörbchen in Eisingen</a>. Rund 100 Kinder, überwiegend zwischen null und drei Jahren, habe ich seitdem begleitet. Jedes bringt sein eigenes Tempo, seine Gewohnheiten und sein Bedürfnis nach Nähe mit.</p><p>Im Alltag gehören Schlafen und Ruhen genauso dazu wie Spielen und Entdecken. Ich erlebe, wie unterschiedlich Kinder zur Ruhe finden, und wie wichtig es ist, aufmerksam hinzusehen.</p><p>Meine Ausbildung zur Babyschlafberaterin habe ich gemacht, um Eltern auch über den Betreuungsalltag hinaus gezielt unterstützen zu können.</p></div></section>
    ${childcare}
    ${split({ img: 'nacht', pos: '50% 35%', body: `<h2>Auch bei uns war Einschlafen nicht einfach „Augen zu“</h2><p class="lead">Als mein Kind etwa eineinhalb Jahre alt war, klappte das Einschlafen nur mit mir. Ich kenne das Gefühl, gebraucht zu werden und sich gleichzeitig Entlastung zu wünschen.</p><p>Diese Erfahrung macht nicht jede Familiengeschichte gleich. Sie erinnert mich daran, erst zuzuhören. Ich möchte verstehen, was euch belastet, bevor wir über Veränderungen sprechen.</p><p class="signature">Anna-Lena, ehrlich, direkt und authentisch</p>` })}
    <section class="section wrap" id="qualifikationen">${intro('Praxis und Ausbildung', 'Die langjährige Erfahrung stammt aus der Kindertagespflege. Meine zusätzliche Qualifikation für die Schlafberatung habe ich 2026 abgeschlossen.', 'row')}<div class="credential-layout"><dl class="credentials" data-reveal><div><dt>Zertifizierte Babyschlafberaterin</dt><dd>Ausbildung erfolgreich abgeschlossen am 11. März 2026. Ausbildungsleitung: Melanie Heift-Budde.</dd></div><div><dt>Qualifizierte Kindertagespflegeperson</dt><dd>Seit 2010 tätig. Rund 100 Kinder in der Tagespflege begleitet.</dd></div><div><dt>Montessori-Diplom</dt><dd>Absolviert in Schweinfurt. Ergänzende pädagogische Qualifikation.</dd></div><div><dt>Kinderyogalehrerin</dt><dd>Ausbildung 2017. Bewegung und Ruhe als Teil des Alltags.</dd></div><div><dt>Fortbildungen und Erste Hilfe</dt><dd>Regelmäßige Fortbildungen und alle zwei Jahre ein Erste-Hilfe-Kurs für Kinder.</dd></div></dl>${certificate()}</div></section>
    <section class="section soft"><div class="wrap narrow" data-reveal><h2>Meine Haltung: klar in der Sache, warm im Umgang</h2><p>Ich arbeite ohne kontrolliertes Schreienlassen und ohne Durchschlafgarantie. Was ich euch geben kann, sind Zeit, ehrliche Einschätzungen und einen Plan, der zu eurem Kind passt. Weil ich höchstens drei Familien gleichzeitig begleite, bleibt Raum für eure Fragen.</p><p>Nähe beim Einschlafen sehe ich nicht als Fehler, sondern als Ausgangspunkt. Wir verändern nur so viel, wie euer Kind und ihr gut mitgehen könnt.</p></div></section>${closing()}`,
  },
  'fragen.html': {
    title: 'Häufige Fragen zur Schlafberatung (FAQ) | Anna-Lena Korb', label: 'Häufige Fragen',
    description: 'Antworten auf häufige Fragen zur Babyschlafberatung: Alter, Schreienlassen, Abstillen, Kosten, Termine, Antwortzeiten und Grenzen der Beratung.',
    faq: allFaq,
    content: `${pageHead('Häufige Fragen zur Schlafberatung', 'Unsicherheit gehört dazu. Hier findet ihr Antworten auf die Fragen, die Eltern mir am häufigsten stellen. Eure Frage ist nicht dabei? Schreibt mir einfach.')}
    <section class="section wrap faq-layout"><div data-reveal><h2>Zur Beratung</h2><p>In diesen FAQ beantworte ich häufige Fragen zu Alter, Vorgehen, Erwartungen und Grenzen der Schlafberatung.</p></div>${questions(faq)}</section>
    <section class="section soft"><div class="wrap faq-layout"><div data-reveal><h2>Kosten, Plätze und Termine</h2><p>Was die Beratung kostet und wie ihr einen Platz bekommt.</p></div>${questions(generalExtraFaq)}</div></section>
    <section class="section wrap narrow" data-reveal><h2>Fragen zur Online-Beratung</h2><p>Ob ihr für Zoom ein Konto braucht, ob beide Elternteile teilnehmen können und wie ihr den Schlafplan bekommt, beantworte ich auf der Seite zur <a href="online-schlafberatung.html#fragen">Online-Schlafberatung</a>.</p></section>${closing('Eure Frage ist nicht dabei?')}`,
  },
  'kontakt.html': {
    title: 'Kostenlos kennenlernen & Termin anfragen | Anna-Lena Korb', label: 'Termin anfragen',
    description: 'Kostenloses 20-Minuten-Gespräch zur Babyschlafberatung anfragen. Per Zoom oder Telefon aus ganz Deutschland. Mo–Fr 17–19 Uhr, Sa 9–13 Uhr.',
    content: `${pageHead('Termin anfragen und kostenlos kennenlernen', '20 Minuten, in denen ihr erzählen könnt. Ihr müsst noch nicht wissen, welches Angebot zu euch passt. Wir schauen gemeinsam darauf.')}
    <section class="section wrap contact-grid"><aside class="contact-aside"><h2>So erreicht ihr mich</h2><dl class="contact-details"><div><dt>Telefon</dt><dd><a href="tel:${site.telephone}">${site.telephoneDisplay}</a></dd></div><div><dt>E-Mail</dt><dd><a href="mailto:${site.email}">${site.email}</a></dd></div><div><dt>Gesprächszeiten</dt><dd>Montag–Freitag: 17–19 Uhr<br>Samstag: 9–13 Uhr<br>Sonntag: geschlossen</dd></div><div><dt>Wo wir sprechen</dt><dd>Per Zoom oder Telefon, deutschlandweit.<br>Vor Ort in Würzburg und ca. 10–15 km Umkreis nach Absprache.</dd></div><div><dt>Rückmeldung</dt><dd>In der Regel innerhalb von 24 Stunden; sonntags und an Feiertagen am nächsten Beratungstag.</dd></div><div><dt>Anschrift</dt><dd>Anna-Lena Korb<br>Müllersweg 15, 97249 Eisingen</dd></div></dl><p class="small">Eine Anfrage ist keine feste Buchung und löst keine Zahlungspflicht aus.</p></aside>
    <div id="anfrage"><div data-booking hidden><form id="booking-form" class="booking-form"><div class="form-heading"><h2>Eure Terminanfrage</h2><p>Wähle bis zu drei Wunschzeiten. Ich bestätige dir anschließend einen passenden Termin per E-Mail.</p></div>
    <div class="field"><label for="interest">Worum geht es?</label><select id="interest" name="interest">${offers.map(o => `<option value="${o.id}">${o.name} · ${o.price ? `${o.price} €` : 'kostenlos'}</option>`).join('')}</select></div>
    <fieldset class="calendar-fieldset"><legend>1. Wunschtermine auswählen</legend><p id="calendar-help" class="form-help">Mindestens sieben Tage Vorlauf. Alle Zeiten sind deutsche Ortszeit. Die angezeigten Zeiten sind anfragbar, aber noch nicht reserviert.</p><div class="calendar"><div class="calendar-toolbar"><button type="button" class="icon-button" data-prev aria-label="Vorheriger Monat">←</button><h3 id="calendar-month" aria-live="polite"></h3><button type="button" class="icon-button" data-next aria-label="Nächster Monat">→</button></div><div class="weekdays" aria-hidden="true"><span>Mo</span><span>Di</span><span>Mi</span><span>Do</span><span>Fr</span><span>Sa</span><span>So</span></div><div class="calendar-days" id="calendar-days" role="group" aria-label="Tag auswählen"></div></div><details class="date-alternative"><summary>Datum direkt eingeben</summary><label for="request-date">Wunschdatum</label><input type="date" id="request-date" aria-describedby="calendar-help"></details><div id="time-options" class="time-options" role="group" aria-label="Uhrzeit auswählen"></div><p id="time-hint" class="form-help" aria-live="polite"></p><div class="proposals"><h3>Deine Wunschzeiten <span id="proposal-count">0 / 3</span></h3><ul id="proposal-list"></ul><p id="selection-status" role="status" aria-live="polite" class="small">Noch keine Zeit ausgewählt.</p></div></fieldset>
    <fieldset><legend>2. So erreiche ich dich</legend><div class="form-row"><div class="field"><label for="name">Dein Name</label><input id="name" name="name" autocomplete="name" required minlength="2" maxlength="100"></div><div class="field"><label for="email">Deine E-Mail-Adresse</label><input id="email" name="email" type="email" autocomplete="email" required maxlength="254"></div></div><div class="field"><label for="format">Gesprächsformat</label><select id="format" name="format"><option>Zoom</option><option>Telefon</option></select><p class="form-help">Bei einem Telefongespräch stimmen wir die Rufnummer per E-Mail ab.</p></div><div class="field"><label for="message">Was möchtest du mir vorab sagen? <span>(optional)</span></label><textarea id="message" name="message" rows="3" maxlength="1200" placeholder="Zum Beispiel: Das Einschlafen dauert gerade sehr lange."></textarea><p class="form-help">Bitte keine Diagnosen, Befunde oder Details zu Schwangerschaft und Geburt. Ausführliche Angaben besprechen wir vertraulich im Beratungsprozess.</p></div></fieldset>
    <p class="form-help">Diese Auswahl wird nur in deinem Browser vorbereitet. Erst wenn du die E-Mail in deinem Mailprogramm oder Gmail selbst absendest, erreicht sie Anna-Lena. <a href="datenschutz.html">Datenschutzhinweise</a></p><button type="submit" class="button full">Anfrage als E-Mail vorbereiten${arrow}</button><p id="booking-status" class="form-status" role="status" tabindex="-1"></p></form>
    <section id="request-result" class="request-result" aria-labelledby="result-title" hidden><p class="result-note">Schritt 3 · Noch nicht versendet</p><h2 id="result-title" tabindex="-1">Deine Anfrage ist vorbereitet.</h2><p>Öffne den Entwurf und sende die E-Mail selbst ab. Erst nach Anna-Lenas persönlicher Bestätigung ist ein Termin vereinbart.</p><label for="request-preview">Dein E-Mail-Entwurf</label><textarea id="request-preview" readonly rows="12"></textarea><div class="actions"><a id="open-mail" class="button" href="mailto:${site.email}">Im E-Mail-Programm öffnen</a><a id="open-gmail" class="button secondary" href="https://mail.google.com/" target="_blank" rel="noopener noreferrer">In Gmail öffnen</a><button type="button" class="button secondary" id="copy-request">Text kopieren</button><button type="button" class="text-button" id="edit-request">Auswahl bearbeiten</button></div><p class="small">Mit „In Gmail öffnen“ wird der Entwurf an Google übergeben. Alternativ den Text kopieren und an ${site.email} senden.</p><p id="copy-status" role="status" class="small"></p></section></div>
    <noscript><div class="note"><h2>Termin per E-Mail anfragen</h2><p>Bitte nenne bis zu drei Wunschtermine mit mindestens sieben Tagen Vorlauf: Montag bis Freitag 17–19 Uhr oder Samstag 9–13 Uhr. Anna-Lena bestätigt dir einen passenden Termin.</p><a href="mailto:${site.email}" class="button">E-Mail schreiben</a><p><a href="mailto:${site.email}">${site.email}</a></p></div></noscript><p class="small fallback-contact">Wenn die Terminauswahl nicht angezeigt wird oder nicht funktioniert: <a href="mailto:${site.email}">Schreibe mir direkt eine E-Mail</a>.</p></div></section>
    <section class="section"><div class="wrap content-grid"><div class="prose" data-reveal><h2>So geht es nach eurer Anfrage weiter</h2><p>Ihr könnt mich 20 Minuten kostenlos kennenlernen. Nach eurer Anfrage melde ich mich in der Regel innerhalb von 24 Stunden und bestätige euch per E-Mail einen passenden Termin, sonntags und an Feiertagen am nächsten Beratungstag.</p><p>Im Gespräch erzählt ihr, was euch gerade belastet und was ihr euch wünscht. Ich erkläre euch, wie ich arbeite, und wir schauen gemeinsam, ob eine Schlafsprechstunde reicht oder eine längere Begleitung sinnvoll ist. Ihr entscheidet danach in Ruhe, ganz ohne Zahlungspflicht.</p><h2>Für wen das Kennenlernen gedacht ist</h2><p>Das Kennenlernen ist für alle Familien mit Kindern von 0 bis 6 Jahren gedacht, die überlegen, ob eine Schlafberatung zu ihnen passt. Ihr müsst dafür noch keine Entscheidung getroffen und kein Paket ausgewählt haben. Viele Eltern wissen vorher nur, dass es so nicht weitergehen soll, und das reicht völlig. Gemeinsam sortieren wir, was euch am meisten belastet, welche Ziele realistisch sind und welche nächsten Schritte für euch infrage kommen. Ob ihr in Hamburg, München oder im Raum Würzburg wohnt, spielt dafür keine Rolle.</p><h2>Was ihr für das Kennenlernen braucht</h2><p>Für ein Gespräch per Zoom genügt ein Smartphone, Tablet oder Laptop mit Kamera, ein eigenes Zoom-Konto braucht ihr nicht. Lieber telefonieren? Dann stimmen wir die Rufnummer per E-Mail ab. Es hilft, wenn ihr euch vorher kurz notiert, wann euer Kind gerade schläft und was euch am meisten belastet.</p><h2>Lieber direkt anrufen?</h2><p>Zu den Gesprächszeiten erreicht ihr mich auch telefonisch. Wenn ich gerade nicht rangehen kann, schreibt mir eine kurze E-Mail mit eurem Namen und eurem Anliegen, dann melde ich mich zurück.</p></div><aside class="aside-box" data-reveal style="--i:1"><h3>Gut zu wissen</h3><p>Ich begleite höchstens drei Familien gleichzeitig. Ob und ab wann ein Platz frei ist, besprechen wir im Kennenlernen.</p>${link('ablauf.html', 'Zum Ablauf')}</aside></div></section>`,
  },
  'baby-einschlafen.html': {
    title: 'Baby einschlafen: sanft begleiten statt kämpfen | Ratgeber', label: 'Baby einschlafen', parent: ['schlafwissen.html', 'Ratgeber'],
    description: 'Euer Baby schläft abends schwer ein? Müdigkeitszeichen erkennen, ein Abendritual, das trägt, und kleine Schritte ohne Schreienlassen.',
    faq: einschlafenFaq,
    article: { headline: 'Baby einschlafen: sanft begleiten statt jeden Abend kämpfen', published: '2026-10-09', image: 'einschlafen' },
    content: `${pageHead('Baby einschlafen: sanft begleiten statt jeden Abend kämpfen', 'Wenn das Einschlafen eine Stunde oder länger dauert, kostet das Kraft. Hier findet ihr, was hinter schwierigen Abenden stecken kann und welche kleinen Schritte oft mehr bewirken als ein radikaler Umbruch.')}
    ${article({ minutes: 6, related: 'baby-einschlafen.html', image: 'einschlafen', note: 'Dieser Ratgeber gibt Orientierung für eure Abende, ersetzt aber keine persönliche Beratung. Wenn ihr euch um die Gesundheit eures Babys sorgt, sprecht bitte mit eurer Kinderarztpraxis.',
      toc: [['warum', 'Warum Einschlafen anspruchsvoll ist'], ['muedigkeit', 'Müdigkeit erkennen'], ['ritual', 'Ein Abendritual, das trägt'], ['nur-mit-mama', 'Wenn es nur mit einer Person klappt'], ['schritte', 'Veränderung in kleinen Schritten'], ['sicher', 'Sicher einschlafen'], ['hilfe', 'Wann Hilfe sinnvoll ist'], ['fragen', 'Häufige Fragen']],
      body: `<h2 id="warum">Warum Einschlafen für Babys so anspruchsvoll ist</h2><p>Einschlafen ist ein Übergang: vom wachen, aufmerksamen Zustand in den Schlaf. Dafür muss ein Kind zur Ruhe kommen und sich sicher fühlen. Babys und kleine Kinder können das noch nicht allein regulieren. Sie brauchen dafür Erwachsene, die ihnen Halt geben. Ihr müsst also nicht jeden Abend gegen das Einschlafen kämpfen, sondern könnt euer Kind sanft durch diesen Übergang begleiten.</p><p>Dass euer Kind Nähe zum Einschlafen sucht, ist deshalb kein Erziehungsfehler und keine „schlechte Angewohnheit“. Es wird erst dann zum Thema, wenn der Ablauf euch dauerhaft überfordert oder ihr euch mehr Flexibilität wünscht.</p>
      <h2 id="muedigkeit">Müdigkeit erkennen, bevor sie kippt</h2><p>Viele lange Abende haben weniger mit dem Einschlafen selbst zu tun als mit dem Zeitpunkt. Ist ein Kind noch nicht müde genug, wird es unruhig. Ist es übermüdet, wirkt es oft paradoxerweise aufgedreht.</p><ul><li>Gähnen, Augenreiben, Ziehen an den Ohren</li><li>Ein starrer, abwesender Blick oder Wegdrehen</li><li>Quengeln und weniger Interesse an Spiel und Umgebung</li></ul><p>Achtet eine Woche lang darauf, wann diese Zeichen auftreten. Ein einfaches Schlafprotokoll hilft, Muster zu sehen, die im Alltag untergehen. Beobachtet dabei euer Kind, nicht nur die Uhr: Wachphasen sind von Kind zu Kind verschieden.</p>
      <h2 id="ritual">Ein Abendritual, das wirklich trägt</h2><p>Ein gutes Abendritual ist kurz, vorhersehbar und ruhig. Es kündigt dem Kind an: Jetzt kommt der Schlaf. Entscheidend ist weniger, was ihr macht, sondern dass es jeden Abend ähnlich abläuft.</p><ul><li>Gleiche Reihenfolge, zum Beispiel Wickeln, Schlafanzug, Licht dimmen, ein Lied</li><li>Etwa 20 bis 30 Minuten statt eines langen Programms</li><li>Wenig Bildschirm, wenig Trubel, gedämpftes Licht</li><li>Ein Ablauf, den auch der andere Elternteil übernehmen kann</li></ul>
      <h2 id="nur-mit-mama">Wenn Einschlafen nur mit einer Person klappt</h2><p>Sehr viele Familien kennen das: Einschlafen funktioniert nur mit Mama – oder nur mit Papa. Für die betreffende Person bedeutet das oft, keinen Abend mehr für sich zu haben.</p><p>Hilfreich ist ein schrittweiser Wechsel. Der andere Elternteil übernimmt zuerst Teile des Rituals, später ist er beim Einschlafen dabei und schließlich allein zuständig. Dass ein Kind die Veränderung erst einmal nicht gut findet und das zeigt, ist normal. Es darf dabei getröstet werden. Begleitet wird es weiterhin von einer vertrauten Person.</p>
      <h2 id="schritte">Veränderung in kleinen Schritten</h2><p>Statt alles auf einmal umzustellen, verändert ihr immer nur eine Sache und bleibt dabei ein paar Tage verlässlich. So kann sich euer Kind auf das Neue einstellen, und ihr seht, was tatsächlich wirkt.</p><p>Kontrolliertes Schreienlassen ist dafür nicht nötig. Ihr bleibt ansprechbar und tröstet, wenn euer Kind euch braucht. Konsequent zu sein heißt, freundlich bei der vereinbarten Veränderung zu bleiben – nicht, Signale zu ignorieren.</p>
      <h2 id="sicher">Sicher einschlafen</h2><p>Egal, wie ihr euer Baby in den Schlaf begleitet: Hingelegt wird es auf den Rücken, im Schlafsack statt unter einer Decke und auf einer eher festen Matratze ohne Kissen, Nestchen oder Felle. Das eigene Bett steht am besten im Elternschlafzimmer, die Luft ist rauchfrei, und euer Baby ist nicht zu warm angezogen. So fasst das Bundesinstitut für Öffentliche Gesundheit (BIÖG) die wichtigsten Punkte zusammen.</p><p>Alles im Detail: <a href="https://www.kindergesundheit-info.de/themen/schlafen/0-12-monate/schlafumgebung/">BIÖG: Die richtige Schlafumgebung für das Baby</a>.</p>
      <h2 id="hilfe">Wann Hilfe sinnvoll ist</h2><p>Wenn die Abende euch über Wochen alle Kraft kosten, wenn ihr euch im Kreis dreht oder euch zwischen widersprüchlichen Ratschlägen nicht entscheiden könnt, kann ein Blick von außen helfen. In einer <a href="schlafberatung-baby.html">Schlafberatung für Babys</a> schauen wir gemeinsam auf euren Alltag und entwickeln einen Plan, der zu euch passt.</p><p>Wenn ihr gesundheitliche Ursachen vermutet, etwa Atemauffälligkeiten, Schmerzen oder Trinkschwierigkeiten, ist zuerst die Kinderarztpraxis die richtige Anlaufstelle.</p>
      <h2 id="fragen">Häufige Fragen zum Einschlafen</h2>${questions(einschlafenFaq)}` })}${closing('Ihr wünscht euch ruhigere Abende?')}`,
  },
  'baby-durchschlafen.html': {
    title: 'Baby schläft nicht durch: Was normal ist & was hilft | Ratgeber', label: 'Baby schläft nicht durch', parent: ['schlafwissen.html', 'Ratgeber'],
    description: 'Euer Baby wacht nachts oft auf? Was Durchschlafen wirklich bedeutet, häufige Gründe für nächtliches Aufwachen und was ihr ausprobieren könnt.',
    faq: durchschlafenFaq,
    article: { headline: 'Baby schläft nicht durch: Was normal ist und was helfen kann', published: '2026-10-09', image: 'babybett' },
    content: `${pageHead('Baby schläft nicht durch: Was normal ist und was helfen kann', 'Nächtliches Aufwachen gehört zur Entwicklung. Trotzdem darf es euch zu viel werden. Hier lest ihr, was hinter häufigem Aufwachen stecken kann und wo ihr ansetzen könnt.')}
    ${article({ minutes: 7, related: 'baby-durchschlafen.html', image: 'babybett', note: 'Die Hinweise in diesem Artikel sind allgemein gehalten. Bei Sorgen um Atmung, Gewicht oder Gesundheit eures Kindes ist eure Kinderarztpraxis die erste Anlaufstelle, nicht eine Schlafberatung.',
      toc: [['bedeutung', 'Was „Durchschlafen“ bedeutet'], ['gruende', 'Häufige Gründe für Aufwachen'], ['ausprobieren', 'Was ihr ausprobieren könnt'], ['limit', 'Wenn ihr am Limit seid'], ['arzt', 'Wann ärztlich abklären?'], ['fragen', 'Häufige Fragen']],
      body: `<h2 id="bedeutung">Was „Durchschlafen“ eigentlich bedeutet</h2><p>Wenn Eltern von Durchschlafen sprechen, meinen sie oft zehn bis zwölf Stunden am Stück. In Studien wird der Begriff oft viel bescheidener verwendet: als längere Schlafphase von etwa fünf bis sechs Stunden.</p><p>Auch Erwachsene wachen nachts zwischen ihren Schlafzyklen kurz auf, erinnern sich aber meist nicht daran. Babys haben kürzere Schlafzyklen und brauchen beim Übergang häufiger Unterstützung. Viele Kinder wachen deshalb im ersten Lebensjahr und auch danach noch nachts auf. Das ist entwicklungsbedingt normal.</p>
      <h2 id="gruende">Häufige Gründe für nächtliches Aufwachen</h2><ul><li><strong>Hunger:</strong> Gerade in den ersten Monaten sind nächtliche Mahlzeiten normal und wichtig.</li><li><strong>Entwicklungsschritte:</strong> Krabbeln, Laufen, Sprechen, Zahnen oder Trennungsangst können Nächte vorübergehend unruhiger machen.</li><li><strong>Einschlafbedingungen:</strong> Ein Kind, das mit bestimmter Hilfe einschläft, erwartet sie oft auch beim nächtlichen Aufwachen.</li><li><strong>Tagesrhythmus:</strong> Zu wenig oder sehr später Tagschlaf und eine unpassende Schlafenszeit wirken sich auf die Nacht aus.</li><li><strong>Umgebung:</strong> Zu warm, zu hell oder zu laut. Das BIÖG nennt etwa 18 °C als günstige Schlafzimmertemperatur.</li><li><strong>Krankheit:</strong> Infekte oder Schmerzen. Hier geht Versorgung vor Veränderung.</li></ul>
      <h2 id="ausprobieren">Was ihr ausprobieren könnt</h2><p>Was hilft, ist von Familie zu Familie verschieden. Diese vier Ansätze sind oft ein guter Anfang.</p><h3>Beobachten statt raten</h3><p>Notiert eine Woche lang Schlafzeiten, Aufwachzeiten und was euer Kind gebraucht hat. Oft zeigt sich ein Muster, etwa ein zu später Mittagsschlaf oder ein Abend, der zu spät beginnt.</p><h3>Abend und Nacht angleichen</h3><p>Wenn sich die Bedingungen beim Einschlafen und beim nächtlichen Aufwachen stark unterscheiden, fällt das Weiterschlafen schwerer. Kleine Veränderungen beim Einschlafen wirken sich häufig auch auf die Nacht aus.</p><h3>Nächte ruhig und reizarm halten</h3><p>Wenig Licht, wenig Sprechen, keine Spielangebote. So bleibt die Nacht für euer Kind klar als Nacht erkennbar.</p><h3>Aufgaben teilen</h3><p>Wenn möglich, wechselt euch ab oder verteilt die Nacht in Schichten, damit jede Person einmal einen längeren Schlafblock bekommt.</p>
      <h2 id="limit">Wenn ihr am Limit seid</h2><p>Dauerhafter Schlafmangel ist belastend. Wenn ihr merkt, dass euch die Kraft ausgeht, nehmt das ernst und holt euch Unterstützung: im Umfeld, bei eurer Hebamme oder Kinderarztpraxis oder bei den Frühen Hilfen eurer Stadt oder eures Landkreises, die Familien mit kleinen Kindern begleiten.</p><p>Eine <a href="schlafberatung.html">Schlafberatung</a> kann euch helfen, eure Situation zu sortieren und realistische nächste Schritte zu finden – ohne Schreienlassen und ohne Durchschlafgarantie.</p>
      <h2 id="arzt">Wann ihr ärztlich abklären solltet</h2><p>Lasst euer Kind kinderärztlich anschauen, wenn ihr zum Beispiel lautes Schnarchen, Atempausen oder angestrengtes Atmen im Schlaf bemerkt, wenn euer Kind Schmerzen zu haben scheint, schlecht trinkt oder isst oder sich sein Schlaf plötzlich stark verändert, ohne dass ihr einen Grund erkennt.</p><p>Hintergrund zum Schlaf im ersten Lebensjahr: <a href="https://www.kindergesundheit-info.de/themen/schlafen/0-12-monate/">BIÖG: Schlafen im ersten Lebensjahr</a>.</p>
      <h2 id="fragen">Häufige Fragen zum Durchschlafen</h2>${questions(durchschlafenFaq)}` })}${closing('Ihr wünscht euch ruhigere Nächte?')}`,
  },
  'schlafwissen.html': {
    title: 'Babyschlaf-Ratgeber: Einschlafen & Durchschlafen', label: 'Ratgeber',
    description: 'Orientierung zu Babyschlaf: Einschlafen, nächtliches Aufwachen und sichere Schlafumgebung. Eigenständig geschrieben, mit Quellen von BIÖG und WHO.',
    content: `${pageHead('Ratgeber Babyschlaf: Einschlafen, Durchschlafen und sicherer Schlaf', 'Weniger widersprüchliche Tipps, mehr Orientierung. Diese Informationen ersetzen keine individuelle Beratung oder ärztliche Untersuchung.')}
    <section class="section wrap">${intro('Babyschlaf-Ratgeber für Eltern', 'In diesem Babyschlaf-Ratgeber findet ihr Orientierung zu den Themen, die Eltern am häufigsten beschäftigen: Einschlafen, Durchschlafen und ein sicherer Schlafplatz.', 'row')}${guideCards('schlafwissen.html')}</section>
    <section class="section soft"><div class="wrap">${intro('Vier Dinge, die ihr wissen solltet')}<div class="knowledge-list"><article data-reveal><h3>Nicht jedes Aufwachen ist ein Problem</h3><p>Wie Schlaf sich entwickelt, ist individuell. Statt alle Kinder an einer festen Stundenzahl zu messen, lohnt der Blick auf Alter, Entwicklung und die Belastung im Familienalltag. Welche Veränderung wäre für euch tatsächlich hilfreich?</p><p>Hintergrund und altersbezogene Informationen: <a href="https://www.kindergesundheit-info.de/themen/schlafen/0-12-monate/">BIÖG: Schlafen im ersten Lebensjahr</a>.</p></article>
    <article data-reveal style="--i:1"><h3>Nähe ist keine schlechte Gewohnheit</h3><p>Wenn Einschlafbegleitung belastend wird, darf sich etwas verändern. Das ist kein Anlass, Eltern Vorwürfe zu machen. Ein Beratungsziel kann sein, neue Abläufe zu finden oder die Begleitung auf mehrere vertraute Personen zu verteilen.</p><p>Stillen nach dem ersten Geburtstag ist nicht automatisch ein Problem. Die WHO empfiehlt neben passender Beikost weiteres Stillen bis zum Alter von zwei Jahren oder darüber hinaus. Daraus folgt keine Verpflichtung für einzelne Familien, und auch keine pauschale Pflicht zum Abstillen für eine Schlafberatung. <a href="https://www.who.int/news-room/fact-sheets/detail/infant-and-young-child-feeding">WHO: Infant and young child feeding</a>.</p></article>
    <article data-reveal id="sicher"><h3>Der sichere Schlafplatz hat Vorrang</h3><p>Für Säuglinge empfiehlt das BIÖG die Rückenlage, eine feste, ebene Matratze und einen eigenen Schlafplatz im Elternschlafzimmer. Kissen und weiche Nestchen gehören nicht ins Babybett. Selbstständigeres Einschlafen bedeutet nicht, dass ein Baby allein in einem anderen Zimmer schlafen soll.</p><p>Die vollständigen Empfehlungen findet ihr beim <a href="https://www.kindergesundheit-info.de/themen/schlafen/0-12-monate/schlafumgebung/">BIÖG: Die richtige Schlafumgebung für das Baby</a>.</p></article>
    <article data-reveal style="--i:1"><h3>Manche Fragen gehören in die Kinderarztpraxis</h3><p>Die Schlafberatung beschäftigt sich mit Alltag, Routinen und Begleitung. Sie ist keine medizinische Diagnostik oder Therapie. Bei gesundheitlichen Beschwerden lasst mögliche Ursachen kinderärztlich abklären, bevor ihr sie als reine Schlafgewohnheit einordnet.</p><p><a href="fragen.html">Häufige Fragen zur Beratung</a></p></article></div></div></section>
    <section class="section wrap narrow" data-reveal><h2>Quellen statt Erfolgsversprechen</h2><p>Die verlinkten Fachinformationen stammen vom Bundesinstitut für Öffentliche Gesundheit und der Weltgesundheitsorganisation. Die Texte in diesem Ratgeber sind eigenständige Zusammenfassungen, keine übernommenen Ratgeberartikel. Stand der Quellenprüfung: 9. Oktober 2026 (Schlafumgebung) und 13. September 2026 (übrige Quellen).</p></section>${closing()}`,
  },
  '404.html': {
    title: 'Seite nicht gefunden | Anna-Lena Korb', description: 'Zurück zur Babyschlafberatung von Anna-Lena Korb.', label: 'Seite nicht gefunden', noindex: true,
    content: `${pageHead('Diese Seite gibt es leider nicht', 'Die Seite existiert nicht oder wurde verschoben. Auf der Startseite findest du alle Informationen zur Schlafberatung.')}<div class="wrap section actions"><a href="index.html" class="button">Zur Startseite${arrow}</a>${contact('Termin anfragen', 'button secondary')}</div>`,
  },
};
