import { site, offers } from '../assets/config.js';
import { contact, closing, pageHead, portrait, hands, questions, childcare } from './layout.mjs';

const faq = [
  ['Für welches Alter ist die Beratung gedacht?', 'Ich begleite Familien mit Kindern von 0 bis 6 Jahren; ältere Kinder nach Absprache. Bei Neugeborenen geht es um Orientierung, sichere Schlafbedingungen und die Entlastung der Eltern – nicht darum, selbstständiges Einschlafen oder Durchschlafen zu verlangen. Ziele und Vorgehen richten sich nach Alter und Entwicklung.'],
  ['Muss mein Kind alleine weinen?', 'Nein. Kontrolliertes Schreienlassen gehört nicht zu meiner Beratung. Wir entwickeln einen klaren Plan und begleiten Veränderungen. Wenn euer Kind Trost braucht, bleibt ihr ansprechbar. Nähe ist kein Fehler.'],
  ['Müssen wir abstillen oder alles sofort verändern?', 'Nein. Stillen, Schnuller oder Einschlafbegleitung sind nicht automatisch ein Problem. Wir schauen ehrlich darauf, was euch belastet und was ihr verändern möchtet. Es gibt keine pauschale Pflicht zum Abstillen oder zum Wechsel des Schlafplatzes. Bei Säuglingen haben Ernährung und sichere Schlafbedingungen Vorrang.'],
  ['Versprichst du, dass unser Kind danach durchschläft?', 'Nein. Ich verspreche euch eine persönliche Begleitung und nachvollziehbare Schritte, aber keinen bestimmten Erfolg in einer festen Zahl von Nächten. Schlaf entwickelt sich individuell. Wir vereinbaren realistische Ziele und prüfen gemeinsam, was euch hilft.'],
  ['Wie funktioniert das Kennenlernen?', 'Ihr fragt einen Termin mindestens sieben Tage im Voraus an. Das Gespräch dauert 20 Minuten und ist kostenlos. Danach entscheidet ihr in Ruhe, ob ihr weitermachen möchtet und welches Angebot zu euch passt. Eine Anfrage löst keine Zahlungspflicht aus.'],
  ['Geht die Beratung auch persönlich in Würzburg?', 'Die Gespräche finden normalerweise per Zoom oder Telefon statt. In Würzburg und im Umkreis von etwa 10 bis 15 Kilometern sind persönliche Termine nach Absprache möglich, ohne zusätzliche Anfahrtskosten. Es gibt keine offene Sprechstunde vor Ort.'],
  ['Wann bekomme ich eine Antwort?', 'Beratungszeiten sind Montag bis Freitag von 17 bis 19 Uhr und Samstag von 9 bis 13 Uhr. Auf Anfragen und begleitende WhatsApp-Nachrichten antworte ich in der Regel innerhalb von 24 Stunden; sonntags und an Feiertagen erfolgt die Antwort am nächsten Beratungstag. Chatbegleitung ist keine ständige Erreichbarkeit.'],
  ['Was ist bei gesundheitlichen Beschwerden?', 'Meine Schlafberatung ersetzt keine ärztliche Untersuchung, Diagnose oder Behandlung. Bei möglichen gesundheitlichen Ursachen ist eure Kinderarztpraxis die richtige Anlaufstelle. Die Beratung ist kein Notfalldienst.'],
];

const packages = [
  { id: 'basis', name: 'Basis', price: 149, eyebrow: 'Ein klarer Anfang', duration: 'Beratung + 7 Tage Begleitung', text: 'Ihr möchtet eure Situation verstehen und mit einem konkreten Plan loslegen.', items: ['Ausführlicher Fragebogen und Auswertung', '60 Minuten per Zoom oder Telefon', 'Individueller schriftlicher Schlafplan innerhalb von 24 Stunden nach dem Gespräch', '7 Tage WhatsApp-Begleitung für Rückfragen'] },
  { id: 'intensiv', name: 'Intensiv', price: 299, eyebrow: 'Veränderung mit Begleitung', duration: '3 Wochen an eurer Seite', text: 'Ihr möchtet neue Routinen ausprobieren und dabei regelmäßig Rückmeldung bekommen.', items: ['Fragebogen, Schlafprotokoll und Auswertung', '60 Minuten Erstberatung per Zoom oder Telefon', 'Individueller Plan innerhalb von 24 Stunden', '3 Folgegespräche à 30 Minuten', '3 Wochen WhatsApp-Begleitung', 'Anpassungen des Plans während der Begleitung'] },
  { id: 'premium', name: 'Premium', price: 479, eyebrow: 'Mehr Zeit für euren Weg', duration: '6 Wochen persönliche Begleitung', text: 'Ihr wünscht euch über einen längeren Zeitraum Orientierung und kontinuierlichen Austausch.', items: ['Fragebogen, Schlafprotokoll und Auswertung', '60 Minuten Erstberatung per Zoom oder Telefon', 'Individueller Plan innerhalb von 24 Stunden', '5 Folgegespräche à 30 Minuten', '6 Wochen WhatsApp-Begleitung', 'Regelmäßige Auswertung und Plananpassungen'] },
];

const priceCards = () => `<div class="price-cards">${packages.map(p => `<article class="price-card ${p.id === 'intensiv' ? 'featured' : ''}" id="${p.id}"><p class="eyebrow">${p.eyebrow}</p><h2>${p.name}</h2><p class="price-value">${p.price}<span> €</span></p><p class="price-duration">${p.duration}</p><p class="package-description">${p.text}</p><ul class="check-list">${p.items.map(item => `<li>${item}</li>`).join('')}</ul>${contact(`${p.name} anfragen`, `button ${p.id === 'intensiv' ? '' : 'secondary'}`, `?paket=${p.name}#anfrage`)}<p class="tiny">Gesamtpreis · kein Abo</p></article>`).join('')}</div>`;

const process = () => `<ol class="steps"><li><span class="step-number">01</span><div><h3>Erst einmal erzählen.</h3><p>20 Minuten kostenlos kennenlernen. Was ist gerade schwierig? Was wünscht ihr euch? Danach entscheidet ihr, ob ihr eine Beratung möchtet.</p></div></li><li><span class="step-number">02</span><div><h3>Eure Situation verstehen.</h3><p>Fragebogen, Schlafprotokoll und ein persönliches Gespräch helfen uns, genauer hinzusehen. Auch eure Familiengeschichte darf dabei Raum bekommen.</p></div></li><li><span class="step-number">03</span><div><h3>Einen klaren Plan bekommen.</h3><p>Bei Basis, Intensiv und Premium bekommt ihr innerhalb von 24 Stunden nach dem Gespräch euren schriftlichen Plan mit konkreten nächsten Schritten.</p></div></li><li><span class="step-number">04</span><div><h3>Ausprobieren. Rückfragen. Anpassen.</h3><p>Je nach Angebot bleibe ich sieben Tage, drei oder sechs Wochen an eurer Seite. Ein Plan soll im echten Leben funktionieren – nicht nur auf Papier.</p></div></li></ol>`;

export const pages = {
  'index.html': {
    title: 'Babyschlafberatung Würzburg & online | Anna-Lena Korb', label: 'Startseite',
    description: 'Ruhigere Nächte mit Nähe und einem klaren Plan. Zertifizierte Babyschlafberaterin, Kindertagespflege seit 2010. Kostenloses 20-Minuten-Kennenlernen.',
    content: `<section class="wrap hero"><div class="hero-copy"><p class="eyebrow"><span class="small-dot" aria-hidden="true"></span> Babyschlafberatung · Würzburg & online</p><h1>Ruhigere Nächte.<br>Mit Nähe.<br><span>Und einem klaren Plan.</span></h1><p class="lead">Wenn das Einschlafen den ganzen Abend bestimmt, braucht ihr nicht noch mehr gut gemeinte Tipps. Sondern jemanden, der zuhört, ehrlich hinschaut und euch begleitet.</p><div class="hero-action">${contact()}<a class="text-link" href="preise.html">Angebote & Preise <span aria-hidden="true">→</span></a><p class="small">20 Minuten · unverbindlich · ohne Schreienlassen</p></div></div><figure class="hero-figure">${hands(true)}<div class="photo-note"><span class="note-symbol" aria-hidden="true">✦</span><div><strong>Kleine Schritte. Gemeinsam.</strong><span>Dein Kind muss dafür nicht allein weinen.</span></div></div><figcaption>Symbolbild · Anna-Lenas persönliches Porträt folgt weiter unten.</figcaption></figure></section>
    <section class="trust-strip" aria-label="Erfahrung und Qualifikation"><div class="wrap trust-grid"><div><strong>Seit 2010</strong><span>qualifizierte Kindertagespflege</span></div><div><strong>Rund 100 Kinder</strong><span>in der Tagespflege begleitet</span></div><div><strong>Zertifiziert</strong><span>als Babyschlafberaterin</span></div><div><strong>Mama seit 2005</strong><span>Erfahrung auch aus eigener Familie</span></div></div></section>
    <section class="section wrap"><div class="section-heading"><div><p class="eyebrow">Kommt dir das bekannt vor?</p><h2>Wenn Schlaf alles<br>andere bestimmt.</h2></div><p>Ihr seid müde. Und vielleicht auch müde von widersprüchlichen Ratschlägen. Wir schauen auf eure Situation – ohne Schuldzuweisungen und ohne ein Programm für alle.</p></div><div class="situation-grid"><article><span class="small-number">01</span><h3>Der Abend zieht sich.</h3><p>Du begleitest lange beim Einschlafen. Sobald du aufstehst, beginnt alles von vorn.</p></article><article><span class="small-number">02</span><h3>Die Nächte sind zerstückelt.</h3><p>Dein Kind wacht häufig auf und du findest selbst kaum noch in den Schlaf.</p></article><article><span class="small-number">03</span><h3>Eine Person trägt alles.</h3><p>Einschlafen klappt nur mit Mama – oder nur mit Papa. Ihr wünscht euch mehr Entlastung.</p></article><article><span class="small-number">04</span><h3>Neue Schritte, neue Fragen.</h3><p>Tagschlaf, Kita-Start oder ein veränderter Alltag: Was passt jetzt zu eurem Kind?</p></article></div><p class="section-note">Für Familien mit Kindern von 0 bis 6 Jahren. Ältere Kinder nach Absprache. Bei Neugeborenen stehen Orientierung und sichere Schlafbedingungen im Mittelpunkt.</p></section>
    <section class="soft-section"><div class="wrap personal-layout">${portrait()}<div class="personal-copy"><p class="eyebrow">Die Person an eurer Seite</p><h2>Ich bin Anna-Lena.<br>Herzlich. Ehrlich.<br>Ganz nah am Alltag.</h2><p>Seit 2010 begleite ich als qualifizierte Kindertagespflegeperson Babys und Kleinkinder. Rund 100 Kinder habe ich in dieser Zeit beim Ankommen, Wachsen und Zur-Ruhe-Kommen erlebt.</p><p>Als Mutter eines 2005 geborenen Kindes kenne ich lange Einschlafabende auch selbst. Heute verbinde ich diese Erfahrung mit meiner Ausbildung zur Babyschlafberaterin.</p><p>Ihr bekommt von mir klare Worte, einen konkreten Plan und Unterstützung bei der Umsetzung. Mit Verständnis für eure Erschöpfung – und Respekt vor eurem Kind.</p><a class="text-link" href="ueber-mich.html">Meine Geschichte & Qualifikationen <span aria-hidden="true">→</span></a></div></div></section>
    <section class="section wrap process-layout"><div><p class="eyebrow">So arbeiten wir zusammen</p><h2>Von „Was sollen wir tun?“<br>zu eurem nächsten Schritt.</h2><p>Ein persönlicher Weg statt einer Sammlung weiterer Schlaftipps.</p><a class="text-link" href="schlafberatung.html">Mehr über die Beratung <span aria-hidden="true">→</span></a></div>${process()}</section>
    <section class="soft-section"><div class="wrap"><div class="section-heading"><div><p class="eyebrow">So viel Begleitung, wie ihr braucht</p><h2>Ein überschaubarer Start.<br>Klare Gesamtpreise.</h2></div><p>Das Kennenlernen ist kostenlos. Danach könnt ihr euch für eine einzelne Sprechstunde oder eine persönliche Begleitung entscheiden. Ohne automatische Verlängerung.</p></div><div class="price-preview">${offers.slice(1).map((o, i) => `<a href="preise.html#${o.id.toLowerCase()}" class="preview-row"><span class="preview-number">0${i + 1}</span><span><strong>${o.name}</strong><span>${['45 Minuten für ein konkretes Thema', '60 Minuten Beratung + 7 Tage Begleitung', '3 Wochen mit regelmäßigen Folgegesprächen', '6 Wochen mit persönlicher Begleitung'][i]}</span></span><span class="preview-value">${o.price} € <span aria-hidden="true">↗</span></span></a>`).join('')}</div><a href="preise.html" class="text-link">Was in den Angeboten enthalten ist <span aria-hidden="true">→</span></a></div></section>
    <section class="section wrap faq-layout"><div><p class="eyebrow">Bevor wir sprechen</p><h2>Deine Fragen<br>haben Platz.</h2><p>Unsicherheit gehört dazu. Hier findest du erste Antworten.</p></div>${questions([faq[1], faq[2], faq[3], faq[4]])}</section>${closing()}`,
  },
  'ueber-mich.html': {
    title: 'Über Anna-Lena Korb | Erfahrung & Qualifikationen', label: 'Über mich',
    description: 'Zertifizierte Babyschlafberaterin aus Eisingen. Kindertagespflege seit 2010, rund 100 betreute Kinder, Montessori-Diplom und Kinderyoga.',
    content: `${pageHead('Anna-Lena Korb', 'Echte Erfahrung.<br>Ein ehrlicher Blick.<br>Ein offenes Ohr.', 'Zertifizierte Babyschlafberaterin, qualifizierte Kindertagespflegeperson und Mama seit 2005. Zu Hause in Eisingen bei Würzburg.')}
    <section class="wrap personal-layout section-bottom">${portrait()}<div class="personal-copy"><h2>Ich kenne Kinder<br>nicht nur aus Lehrbüchern.</h2><p>Seit 2010 bin ich Tagesmutter im Kinderkörbchen. Rund 100 Kinder, überwiegend zwischen null und drei Jahren, habe ich seitdem begleitet. Jedes bringt sein eigenes Tempo, seine Gewohnheiten und sein Bedürfnis nach Nähe mit.</p><p>Im Alltag gehören Schlafen und Ruhen genauso dazu wie Spielen und Entdecken. Ich erlebe, wie unterschiedlich Kinder zur Ruhe finden – und wie wichtig es ist, aufmerksam hinzusehen.</p><p>Meine Ausbildung zur Babyschlafberaterin habe ich gemacht, um Eltern auch über den Betreuungsalltag hinaus gezielt unterstützen zu können.</p>${childcare}</div></section>
    <section class="soft-section"><div class="wrap story"><p class="eyebrow">Was ich aus eigener Erfahrung mitbringe</p><h2>Auch bei uns war Einschlafen<br>nicht einfach „Augen zu“.</h2><p class="lead">Als mein Kind etwa eineinhalb Jahre alt war, klappte das Einschlafen nur mit mir. Ich kenne das Gefühl, gebraucht zu werden – und sich gleichzeitig Entlastung zu wünschen.</p><p>Diese Erfahrung macht nicht jede Familiengeschichte gleich. Sie erinnert mich daran, erst zuzuhören. Ich möchte verstehen, was euch belastet, bevor wir über Veränderungen sprechen.</p><div class="signature">Anna-Lena <span>ehrlich · direkt · authentisch</span></div></div></section>
    <section class="section wrap" id="qualifikationen"><div class="section-heading"><div><p class="eyebrow">Das bringe ich mit</p><h2>Praxis und Ausbildung.<br>Beides zählt.</h2></div><p>Die langjährige Erfahrung stammt aus der Kindertagespflege. Meine zusätzliche Qualifikation für die Schlafberatung habe ich 2026 abgeschlossen.</p></div><div class="credential-layout"><div><dl class="credentials"><div><dt>Zertifizierte Babyschlafberaterin</dt><dd>Ausbildung erfolgreich abgeschlossen am 11. März 2026. Ausbildungsleitung: Melanie Heift-Budde.</dd></div><div><dt>Qualifizierte Kindertagespflegeperson</dt><dd>Seit 2010 tätig. Rund 100 Kinder in der Tagespflege begleitet.</dd></div><div><dt>Montessori-Diplom</dt><dd>Absolviert in Schweinfurt. Ergänzende pädagogische Qualifikation.</dd></div><div><dt>Kinderyogalehrerin</dt><dd>Ausbildung 2017. Bewegung und Ruhe als Teil des Alltags.</dd></div><div><dt>Fortbildungen & Erste Hilfe</dt><dd>Regelmäßige Fortbildungen und alle zwei Jahre ein Erste-Hilfe-Kurs für Kinder.</dd></div></dl></div><figure class="certificate"><a href="assets/zertifikat-anna-lena-korb.pdf" aria-label="Abschlusszertifikat als PDF öffnen"><img src="assets/zertifikat-anna-lena-korb.png" alt="Abschlusszertifikat: Anna-Lena Korb hat die Ausbildung zur Babyschlafberaterin am 11.03.2026 erfolgreich absolviert. Ausbildungsleitung Melanie Heift-Budde." width="1200" height="849" loading="lazy"></a><figcaption>Laut Abschlusszertifikat ist die Ausbildung vom Gesundheitsamt der Stadt Aachen zertifiziert. Diese Angabe bezieht sich auf die Ausbildung.<br><a href="assets/zertifikat-anna-lena-korb.pdf">Zertifikat als PDF ansehen</a></figcaption></figure></div></section>
    <section class="soft-section"><div class="wrap section-heading"><div><p class="eyebrow">Meine Haltung</p><h2>Klar in der Sache.<br>Warm im Umgang.</h2></div><div><p>Ich rede Schwierigkeiten nicht klein. Wenn ein Ablauf euch belastet, schauen wir ihn uns ehrlich an. Gemeinsam vereinbarte Schritte setzen wir verlässlich um und passen sie an, wenn sie nicht funktionieren.</p><p>Konsequent bedeutet für mich nicht, Signale zu ignorieren. Es bedeutet, verständlich und verlässlich zu begleiten. Ohne kontrolliertes Schreienlassen, ohne Schuldzuweisungen und ohne Durchschlafgarantie.</p></div></div></section>${closing()}`,
  },
  'schlafberatung.html': {
    title: 'Babyschlafberatung: Ablauf & Haltung | Anna-Lena Korb', label: 'So helfe ich',
    description: 'Persönliche Schlafberatung für Familien mit Kindern von 0 bis 6 Jahren: Fragebogen, Schlafprotokoll, klarer Plan und Begleitung ohne Schreienlassen.',
    content: `${pageHead('So helfe ich euch', 'Schlaf verstehen.<br>Veränderung begleiten.', 'Euer Ziel muss nicht „perfekt durchschlafen“ heißen. Es darf erst einmal heißen: weniger Belastung, mehr Orientierung und ein Abend, der sich wieder bewältigen lässt.')}
    <section class="wrap advice-intro section-bottom"><div><h2>Was soll für euch<br>leichter werden?</h2><p>Vielleicht möchtest du nicht mehr jeden Abend stundenlang begleiten. Vielleicht soll auch ein anderer Elternteil beim Einschlafen helfen können. Oder ihr braucht einen Blick von außen auf euren Tagesablauf.</p><p>Wir vereinbaren ein Ziel, das zu Alter, Entwicklung und Bedürfnissen eures Kindes passt. Selbstständigeres Einschlafen kann ein Ziel sein – ist aber keine Pflicht für jedes Kind und nicht das Ziel der Neugeborenenberatung.</p><p class="note">Für Kinder von 0 bis 6 Jahren. Ältere Kinder nach Absprache. Online per Zoom oder Telefon, regional nach Vereinbarung.</p></div><figure>${hands()}<figcaption>Nähe und Veränderung schließen sich nicht aus. Symbolbild.</figcaption></figure></section>
    <section class="soft-section"><div class="wrap process-layout"><div><p class="eyebrow">Vom Kennenlernen zur Umsetzung</p><h2>Ein nachvollziehbarer Ablauf.<br>Kein Rätselraten.</h2><p>Die Schlafsprechstunde beantwortet eine einzelne Frage. Bei den Begleitungspaketen gehen wir ausführlicher vor.</p></div>${process()}</div></section>
    <section class="section wrap section-heading"><div><p class="eyebrow">Ein genauer Blick – ohne Druck</p><h2>Eure Geschichte<br>gehört dazu.</h2></div><div><p>Der Fragebogen beschäftigt sich mit eurem Alltag, Schlafgewohnheiten und euren Wünschen. Schwangerschaft, Geburt und die erste Zeit mit eurem Kind können dabei ebenfalls angesprochen werden, soweit sie für eure Beratung relevant sind und ihr darüber sprechen möchtet.</p><p>Aus einer Geburtsgeschichte allein lässt sich keine Ursache für ein Schlafproblem ableiten. Die Schlafberatung stellt keine Diagnosen und ersetzt keine medizinische oder therapeutische Behandlung.</p><p>Vertrauliche Informationen gehören nicht in die öffentliche Terminanfrage. Den passenden Rahmen für ausführliche Angaben stimmen wir persönlich ab.</p></div></section>
    <section class="soft-section"><div class="wrap section-heading"><div><p class="eyebrow">Persönlich erreichbar</p><h2>Ein fester Rahmen.<br>Auch für Rückfragen.</h2></div><div><p>In den Begleitungspaketen könnt ihr Fragen per WhatsApp stellen. Ich antworte in der Regel innerhalb von 24 Stunden; sonntags und an Feiertagen am nächsten Beratungstag. Die Begleitung ist kein Live-Chat und keine Rund-um-die-Uhr-Betreuung.</p><p>Gespräche: Montag bis Freitag 17–19 Uhr und Samstag 9–13 Uhr. Innerhalb Würzburgs und im Umkreis von etwa 10 bis 15 Kilometern sind persönliche Termine nach Absprache ohne zusätzliche Anfahrtskosten möglich.</p><a class="text-link" href="preise.html">Begleitung auswählen <span aria-hidden="true">→</span></a></div></div></section>
    <section class="section wrap faq-layout" id="fragen"><div><p class="eyebrow">Häufige Fragen</p><h2>Gut zu wissen,<br>bevor wir starten.</h2></div>${questions(faq)}</section>${closing()}`,
  },
  'preise.html': {
    title: 'Babyschlafberatung: Preise ab 89 € | Anna-Lena Korb', label: 'Angebote & Preise',
    description: '45-Minuten-Sprechstunde 89 €, Basis 149 €, Intensiv 299 €, Premium 479 €. Klare Gesamtpreise, persönlicher Plan und kostenloses Kennenlernen.',
    content: `${pageHead('Angebote & Preise', 'Ein guter Anfang.<br>So viel Begleitung,<br>wie ihr braucht.', 'Ein konkretes Thema oder Unterstützung über mehrere Wochen: Ihr entscheidet nach dem kostenlosen Kennenlernen in Ruhe. Alle genannten Beträge sind Gesamtpreise.')}
    <section class="wrap intro-band"><div><p class="eyebrow">20 Minuten nur für euch</p><h2>Das Kennenlernen geht auf mich.</h2><p>Wir besprechen eure Situation und schauen, ob mein Angebot passt. Keine Zahlungspflicht, keine Paketpflicht.</p></div>${contact()}</section>
    <section class="wrap section-bottom" aria-label="Beratungspakete">${priceCards()}<article class="single-offer" id="sprechstunde"><div><p class="eyebrow">Lieber erst eine konkrete Frage klären?</p><h2>Schlafsprechstunde</h2><p>45 Minuten per Zoom, ein klar abgegrenztes Thema und eine kurze schriftliche Zusammenfassung. Ohne vollständigen Schlafplan und ohne anschließende WhatsApp-Begleitung.</p></div><div><p class="price-value">89<span> €</span></p>${contact('Sprechstunde anfragen', 'button secondary', '?paket=Sprechstunde#anfrage')}<p class="tiny">Gesamtpreis</p></div></article></section>
    <section class="soft-section"><div class="wrap section-heading"><div><p class="eyebrow">Damit alles transparent bleibt</p><h2>Klare Leistungen.<br>Klare Grenzen.</h2></div><div><h3>Persönlich, aber nicht rund um die Uhr.</h3><p>WhatsApp-Begleitung gilt nur im gebuchten Zeitraum. Antworten in der Regel innerhalb von 24 Stunden; sonntags und an Feiertagen am nächsten Beratungstag. Keine Live- oder Notfallbetreuung.</p><h3>Ein Plan, der auf eure Angaben aufbaut.</h3><p>Der schriftliche Schlafplan folgt innerhalb von 24 Stunden nach dem Beratungsgespräch, sofern die vereinbarten Unterlagen vollständig vorliegen. Die Begleitdauer startet zum gemeinsam vereinbarten Termin.</p><h3>Keine automatische Verlängerung.</h3><p>Vor einer kostenpflichtigen Vereinbarung erhaltet ihr Leistungsumfang, Preis und Vertragsinformationen. Zahlungsweise, eine mögliche Ratenzahlung und Terminänderungen werden persönlich vereinbart. Die Anfrage auf dieser Seite ist noch kein Vertrag.</p><p>Ich begleite höchstens drei Familien gleichzeitig. Ob gerade ein Platz frei ist, klären wir persönlich.</p><p class="small"><a href="agb.html">AGB</a> · <a href="widerruf.html">Widerrufsrecht</a></p></div></div></section>${closing()}`,
  },
  'kontakt.html': {
    title: 'Kostenlos kennenlernen & Termin anfragen | Anna-Lena Korb', label: 'Kennenlernen',
    description: 'Kostenloses 20-Minuten-Gespräch anfragen. Mo–Fr 17–19 Uhr, Sa 9–13 Uhr, sieben Tage Vorlauf. Babyschlafberatung per Zoom und Telefon.',
    content: `${pageHead('Ein erster Schritt', 'Erzähl mir von euch.', '20 Minuten kostenlos kennenlernen. Du musst noch nicht wissen, welches Angebot zu euch passt. Wir schauen gemeinsam darauf.')}
    <section class="wrap contact-grid section-bottom"><aside class="contact-aside"><h2>Hier ist Zeit<br>für eure Fragen.</h2><dl class="contact-details"><div><dt>Gesprächszeiten</dt><dd>Montag–Freitag: 17–19 Uhr<br>Samstag: 9–13 Uhr<br>Sonntag: geschlossen</dd></div><div><dt>Wo wir sprechen</dt><dd>Per Zoom oder Telefon.<br>Vor Ort in Würzburg und ca. 10–15 km Umkreis nach Absprache.</dd></div><div><dt>Rückmeldung</dt><dd>In der Regel innerhalb von 24 Stunden; sonntags und an Feiertagen am nächsten Beratungstag.</dd></div></dl><p>Du kannst mir auch direkt schreiben oder mich zu den Gesprächszeiten anrufen:</p><a class="email" href="mailto:${site.email}">${site.email}</a><a class="phone" href="tel:${site.telephone}">${site.telephoneDisplay}</a><p class="small">Eine Anfrage ist keine feste Buchung und löst keine Zahlungspflicht aus.</p></aside>
    <div id="anfrage"><div data-booking hidden><form id="booking-form" class="booking-form"><div class="form-heading"><p class="eyebrow">Deine Terminanfrage</p><h2>Was passt in euren Alltag?</h2><p>Wähle bis zu drei Wunschzeiten. Ich bestätige dir anschließend einen passenden Termin per E-Mail.</p></div>
    <div class="field"><label for="interest">Worum geht es?</label><select id="interest" name="interest">${offers.map(o => `<option value="${o.id}">${o.name} · ${o.price ? `${o.price} €` : 'kostenlos'}</option>`).join('')}</select></div>
    <fieldset class="calendar-fieldset"><legend>1. Wunschtermine auswählen</legend><p id="calendar-help" class="form-help">Mindestens sieben Tage Vorlauf. Alle Zeiten sind deutsche Ortszeit. Die angezeigten Zeiten sind anfragbar, aber noch nicht reserviert.</p><div class="calendar"><div class="calendar-toolbar"><button type="button" class="icon-button" data-prev aria-label="Vorheriger Monat">←</button><h3 id="calendar-month" aria-live="polite"></h3><button type="button" class="icon-button" data-next aria-label="Nächster Monat">→</button></div><div class="weekdays" aria-hidden="true"><span>Mo</span><span>Di</span><span>Mi</span><span>Do</span><span>Fr</span><span>Sa</span><span>So</span></div><div class="calendar-days" id="calendar-days" role="group" aria-label="Tag auswählen"></div></div><details class="date-alternative"><summary>Datum direkt eingeben</summary><label for="request-date">Wunschdatum</label><input type="date" id="request-date" aria-describedby="calendar-help"></details><div id="time-options" class="time-options" role="group" aria-label="Uhrzeit auswählen"></div><p id="time-hint" class="form-help" aria-live="polite"></p><div class="proposals"><h3>Deine Wunschzeiten <span id="proposal-count">0 / 3</span></h3><ul id="proposal-list"></ul><p id="selection-status" role="status" aria-live="polite" class="small">Noch keine Zeit ausgewählt.</p></div></fieldset>
    <fieldset><legend>2. So erreiche ich dich</legend><div class="form-row"><div class="field"><label for="name">Dein Name</label><input id="name" name="name" autocomplete="name" required minlength="2" maxlength="100"></div><div class="field"><label for="email">Deine E-Mail-Adresse</label><input id="email" name="email" type="email" autocomplete="email" required maxlength="254"></div></div><div class="field"><label for="format">Gesprächsformat</label><select id="format" name="format"><option>Zoom</option><option>Telefon</option></select><p class="form-help">Bei einem Telefongespräch stimmen wir die Rufnummer per E-Mail ab.</p></div><div class="field"><label for="message">Was möchtest du mir vorab sagen? <span>(optional)</span></label><textarea id="message" name="message" rows="3" maxlength="1200" placeholder="Zum Beispiel: Das Einschlafen dauert gerade sehr lange."></textarea><p class="form-help">Bitte keine Diagnosen, Befunde oder Details zu Schwangerschaft und Geburt. Ausführliche Angaben besprechen wir vertraulich im Beratungsprozess.</p></div></fieldset>
    <p class="form-help">Diese Auswahl wird nur in deinem Browser vorbereitet. Erst wenn du die E-Mail in deinem Mailprogramm oder Gmail selbst absendest, erreicht sie Anna-Lena. <a href="datenschutz.html">Datenschutzhinweise</a></p><button type="submit" class="button full">Anfrage als E-Mail vorbereiten <span aria-hidden="true">→</span></button><p id="booking-status" class="form-status" role="status" tabindex="-1"></p></form>
    <section id="request-result" class="request-result" aria-labelledby="result-title" hidden><p class="eyebrow">Schritt 3 · Noch nicht versendet</p><h2 id="result-title" tabindex="-1">Deine Anfrage ist vorbereitet.</h2><p>Öffne den Entwurf und sende die E-Mail selbst ab. Erst nach Anna-Lenas persönlicher Bestätigung ist ein Termin vereinbart.</p><label for="request-preview">Dein E-Mail-Entwurf</label><textarea id="request-preview" readonly rows="12"></textarea><div class="actions"><a id="open-mail" class="button" href="mailto:${site.email}">Im E-Mail-Programm öffnen ↗</a><a id="open-gmail" class="button secondary" href="https://mail.google.com/" target="_blank" rel="noopener noreferrer">In Gmail öffnen ↗</a><button type="button" class="button secondary" id="copy-request">Text kopieren</button><button type="button" class="text-button" id="edit-request">Auswahl bearbeiten</button></div><p class="small">Mit „In Gmail öffnen“ wird der Entwurf an Google übergeben. Alternativ den Text kopieren und an ${site.email} senden.</p><p id="copy-status" role="status" class="small"></p></section></div>
    <noscript><div class="note"><h2>Termin per E-Mail anfragen</h2><p>Bitte nenne bis zu drei Wunschtermine mit mindestens sieben Tagen Vorlauf: Montag bis Freitag 17–19 Uhr oder Samstag 9–13 Uhr. Anna-Lena bestätigt dir einen passenden Termin.</p><a href="mailto:${site.email}" class="button">E-Mail schreiben ↗</a><p><a href="mailto:${site.email}">${site.email}</a></p></div></noscript><p class="small fallback-contact">Wenn die Terminauswahl nicht angezeigt wird oder nicht funktioniert: <a href="mailto:${site.email}">Schreibe mir direkt eine E-Mail</a>.</p></div></section>`,
  },
  'schlafwissen.html': {
    title: 'Babyschlaf: Orientierung & verlässliche Quellen | Anna-Lena Korb', label: 'Schlafwissen',
    description: 'Erste Orientierung zu Babyschlaf, Einschlafbegleitung und sicherer Schlafumgebung. Mit weiterführenden Informationen von BIÖG und WHO.',
    content: `${pageHead('Schlafwissen', 'Weniger widersprüchliche Tipps.<br>Mehr Orientierung.', 'Eine erste Einordnung für müde Eltern. Diese Informationen ersetzen keine individuelle Beratung oder ärztliche Untersuchung.')}
    <section class="wrap knowledge-list section-bottom"><article><span class="small-number">01 / Erwartungen</span><h2>Nicht jedes Aufwachen<br>ist ein Problem.</h2><p>Wie Schlaf sich entwickelt, ist individuell. Statt alle Kinder an einer festen Stundenzahl zu messen, lohnt der Blick auf Alter, Entwicklung und die Belastung im Familienalltag. Welche Veränderung wäre für euch tatsächlich hilfreich?</p><p>Hintergrund und altersbezogene Informationen: <a href="https://www.kindergesundheit-info.de/themen/schlafen/0-12-monate/">BIÖG: Schlafen im ersten Lebensjahr</a>.</p></article>
    <article><span class="small-number">02 / Einschlafgewohnheiten</span><h2>Nähe ist keine<br>schlechte Gewohnheit.</h2><p>Wenn Einschlafbegleitung belastend wird, darf sich etwas verändern. Das ist kein Anlass, Eltern Vorwürfe zu machen. Ein Beratungsziel kann sein, neue Abläufe zu finden oder die Begleitung auf mehrere vertraute Personen zu verteilen.</p><p>Stillen nach dem ersten Geburtstag ist nicht automatisch ein Problem. Die WHO empfiehlt neben passender Beikost weiteres Stillen bis zum Alter von zwei Jahren oder darüber hinaus. Daraus folgt keine Verpflichtung für einzelne Familien – und auch keine pauschale Pflicht zum Abstillen für eine Schlafberatung. <a href="https://www.who.int/news-room/fact-sheets/detail/infant-and-young-child-feeding">WHO: Infant and young child feeding</a>.</p></article>
    <article><span class="small-number">03 / Sicherer Babyschlaf</span><h2>Der sichere Schlafplatz<br>hat Vorrang.</h2><p>Für Säuglinge empfiehlt das BIÖG die Rückenlage, eine feste, ebene Matratze und einen eigenen Schlafplatz im Elternschlafzimmer. Kissen und weiche Nestchen gehören nicht ins Babybett. Selbstständigeres Einschlafen bedeutet nicht, dass ein Baby allein in einem anderen Zimmer schlafen soll.</p><p>Die vollständigen Empfehlungen findet ihr beim <a href="https://www.kindergesundheit-info.de/themen/schlafen/0-12-monate/schlafumgebung/">BIÖG: Die richtige Schlafumgebung für das Baby</a>.</p></article>
    <article><span class="small-number">04 / Grenzen der Beratung</span><h2>Manche Fragen gehören<br>in die Kinderarztpraxis.</h2><p>Die Schlafberatung beschäftigt sich mit Alltag, Routinen und Begleitung. Sie ist keine medizinische Diagnostik oder Therapie. Bei gesundheitlichen Beschwerden lasst mögliche Ursachen kinderärztlich abklären, bevor ihr sie als reine Schlafgewohnheit einordnet.</p><a href="schlafberatung.html#fragen" class="text-link">Fragen zur Beratung <span aria-hidden="true">→</span></a></article></section>
    <section class="soft-section"><div class="wrap story"><p class="eyebrow">Quellen statt Erfolgsversprechen</p><h2>Nachvollziehbar bleiben.</h2><p>Die verlinkten Fachinformationen stammen vom Bundesinstitut für Öffentliche Gesundheit und der Weltgesundheitsorganisation. Die Texte auf dieser Seite sind eigenständige Zusammenfassungen, keine übernommenen Ratgeberartikel. Stand der Quellenprüfung: 13. September 2026.</p></div></section>${closing()}`,
  },
  '404.html': {
    title: 'Seite nicht gefunden | Anna-Lena Korb', description: 'Zurück zur Babyschlafberatung von Anna-Lena Korb.', label: 'Seite nicht gefunden', noindex: true,
    content: `${pageHead('404 · Hier geht es nicht weiter', 'Zurück zu einem<br>guten Anfang.', 'Diese Seite existiert nicht oder wurde verschoben. Auf der Startseite findest du alle Informationen zur Schlafberatung.')}<div class="wrap section-bottom actions"><a href="index.html" class="button">Zur Startseite →</a>${contact()}</div>`,
  },
};
